### ISSUE TITLE
[iOS] Can I change the name of background process?

### ISSUE THREAD

**Issue by GrupoDO** [ekasetiawans/flutter_background_service#100]
Hello! Is there any way to change the name of the background process (current is bgRefresh-dev.flutter.background.refresh) for something with the name of my app? Something like bgRefresh-myAppName will be great.

Thank you!

**Comment by ekasetiawans** [comment]
hi @GrupoDO currently is not possible to do that, but I'm planning to add that feature in the future.

**Comment by huseyinemreuslu** [comment]
You can do it, if you sneak in this library

**Comment by GrupoDO** [comment]
> You can do it, if you sneak in this library

Yes, but with every update of package I will need to repeat the change.

**Comment by ekasetiawans** [comment]
@GrupoDO fork this repository and modify it, then use git reference in your project pubspec.yaml
