### ISSUE TITLE
Can i add periodical call in background for ios and android 

### ISSUE THREAD

**Issue by vitulgoyani** [ekasetiawans/flutter_background_service#105]
hello, I have to save location data every 1 minute even if the app is killed can we do that using your plugin

**Comment by ekasetiawans** [comment]
you can do it in android as far system doesn't kill your app.
In ios, we use background fetch that not possible to execute any task faster than 15 minutes once.

**Comment by ekasetiawans** [comment]
You can't call any code if your app is killed.

**Comment by vitulgoyani** [comment]
really, can you suggest to me any plugin thank you🙏🏻
