### ISSUE TITLE
Is it possible for a service to stop itself?

### ISSUE THREAD

**Issue by lucasarcouto** [ekasetiawans/flutter_background_service#106]
So, I have a background service that, after it's done, I want it to be stopped without any user interaction. Any calls to stop it just gets ignored and it keeps running. 
Already tried creating a Future.delayed, using sendData or calling stopBackgroundService() directly, nothing works.

**Comment by ekasetiawans** [comment]
the `stopBackgroundService()` method should stop the service, you should call the method inside service initialization method. See the example here https://github.com/ekasetiawans/flutter_background_service/blob/master/example/lib/main.dart

**Comment by thfr69** [comment]
I also need the background service to stop without user interaction. But neither the call to "stopBackgroundService" directly nor "service.sendData(
                    {"action": "stopService"},
                  ); "
will cause the service to stop.

**Comment by ekasetiawans** [comment]
@thfr69 you can call `stopBackgroundService()` by any events inside background service method.

**Comment by lucasarcouto** [comment]
I got the stopBackgroundService() to work, but I had to wrap it inside a Timer and add a little delay to it. From what I see, if my task finishes before the first "runService" log message shows up, it just gets ignored. 

If that's your case, just do something like this:

```
Timer(Duration(seconds: 10), () {
    final service = FlutterBackgroundService();
    service.stopBackgroundService();
});
```
