### ISSUE TITLE
Background Service, Preparing (Foreground mode)

### ISSUE THREAD

**Issue by abbiyuarsyah** [ekasetiawans/flutter_background_service#107]
First of all, I would like to thank you for this plugin, it's very useful for our team.
I have a question, if I set setForegroundMode(true) there will be a notification showing up with the title and body 
"Background Service, preparing". Is it an issue or not? Because that would be good for me if I set it with true, but the notification won't show up.. is there any way to do that? Thank you :)

**Comment by ekasetiawans** [comment]
hi @abbiyuarsyah, that is the intended behavior, a foreground service requires notification. You can modify notification by calling `setNotificationInfo()` inside service initialization method.

**Comment by abbiyuarsyah** [comment]
Ok, got it @ekasetiawans thank you for the help
