### ISSUE TITLE
Use with flutter_downloader

### ISSUE THREAD

**Issue by shinewanna** [ekasetiawans/flutter_background_service#108]
If u don't mind, can u create me a dummy project by linking flutter_backgroud_service with [flutter_downloader](https://pub.dev/packages/flutter_downloader).
After I migrate and when download in background service, the app is crashed.

**Comment by ekasetiawans** [comment]
you don't need to combine flutter downloader with background service, because the flutter downloader is already use its own isolate.

**Comment by shinewanna** [comment]
So, why flutter_downloader is not working more than 10 minutes?? It can't download large file, it failed or canceled after 10 minutes.

**Comment by ekasetiawans** [comment]
@shinewanna I think it was flutter_downloader issue, please file an issue to the flutter_downloader repository. I close this issue because out of topic.

**Comment by shinewanna** [comment]
I already issued on flutter_downloader, but there is no respond yet, so i am trying to make it work on background more than 10 minutes. Thanks for ur time.

**Comment by ekasetiawans** [comment]
@shinewanna you can perform any http request inside background service, so you don't need to using flutter downloader, just download the file using any http client such as Dio or http.
