### ISSUE TITLE
Run in foreground without notification(not background)

### ISSUE THREAD

**Issue by whquddn55** [ekasetiawans/flutter_background_service#111]
Hi! I'm making a app peridoically crawling some websites and notifing informations.
In implement that, this package helped me a lot.

But i found that Android System kill "Background Service" periodically even if turn off battery optimization.
Yes. I could solve that with "Foreground Service". But, there is always a notification! 

Is there a solution to solved this?

**Comment by ekasetiawans** [comment]
@whquddn55 some custom android os has additional setting to make app run in background continuously e.g MIUI, you have to allow app can start automatically via security app, disable background limitation and also lock task in task manager (recent app).

**Comment by whquddn55** [comment]
> 

I read it and understanded it. But... is really the only solution? I just don't like requiring all users to have such a cumbersome setup progress.

**Comment by ekasetiawans** [comment]
That is the best solution we can do for now. I experienced with some xiaomi app e.g Mi Wear, they provide a page that contains tutorial about background task permission.

**Comment by whquddn55** [comment]
> That is the best solution we can do for now. I experienced with some xiaomi app e.g Mi Wear, they provide a page that contains tutorial about background task permission.

I hav searched almost 1 weeks to found another solution, but i agree to the only solution is disabling battery optimization.... and I think i can try FCM to wake application periodically! thanks for quick reply.

**Comment by whquddn55** [comment]
Although battery optimization is turned off, I've found that Android system kills background services and restart services whenever Android System them to To solve this, the only solution is using FCM + Another back server.
