### ISSUE TITLE
Strongly consider using FLAG_IMMUTABLE

### ISSUE THREAD

**Issue by makda-mohammad** [ekasetiawans/flutter_background_service#112]
E/AndroidRuntime(17759): java.lang.IllegalArgumentException: com.example.demoproject: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
E/AndroidRuntime(17759): Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
E/AndroidRuntime(17759): 	at android.app.PendingIntent.checkFlags(PendingIntent.java:378)
E/AndroidRuntime(17759): 	at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:648)
E/AndroidRuntime(17759): 	at android.app.PendingIntent.getBroadcast(PendingIntent.java:635)
E/AndroidRuntime(17759): 	at androidx.work.impl.utils.ForceStopRunnable.getPendingIntent(ForceStopRunnable.java:196)
E/AndroidRuntime(17759): 	at androidx.work.impl.utils.ForceStopRunnable.isForceStopped(ForceStopRunnable.java:128)
E/AndroidRuntime(17759): 	at androidx.work.impl.utils.ForceStopRunnable.run(ForceStopRunnable.java:93)
E/AndroidRuntime(17759): 	at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
E/AndroidRuntime(17759): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime(17759): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(17759): 	at java.lang.Thread.run(Thread.java:920)

**Comment by ekasetiawans** [comment]
@makda-mohammad which version do you use?

**Comment by makda-mohammad** [comment]
I am using the latest stable version (0.2.6) from pub.dev.
Flutter version is:- Flutter (Channel stable, 2.10.2, on macOS 12.2.1 21D62 darwin-arm, locale en-IN)
