### ISSUE TITLE
MissingPluginException(No implementation found for method sendData

### ISSUE THREAD

**Issue by fbr-github** [ekasetiawans/flutter_background_service#114]
Hi,
Please, could you fix the exception on Chrome emulation target platform?
```
...
at [http://localhost:58795/dart_sdk.js:35811:9]()
Error: MissingPluginException(No implementation found for method sendData on channel id.flutter/background_service_bg)
    at Object.throw_ [as throw] ([http://localhost:58795/dart_sdk.js:5063:11]())
at MethodChannel._invokeMethod ([http://localhost:58795/packages/flutter/src/services/restoration.dart.lib.js:1555:21]())
    at _invokeMethod.next (<anonymous>)
...
```
Anyway, great plugin! Thanx

**Comment by ekasetiawans** [comment]
Only android and ios supported for now

**Comment by fbr-github** [comment]
Thanx for your reply.
Yes, I know Chrome emulation is not supported, but I use your plugin in such environment for testing purposes, and I do not expect it may work. But there are loads of exceptions happening because of sendData(), and of course I don't want that. The question is what must be done to prevent such exceptions.
Should the flutter_background_service plugin provide empty functions for target platforms other than Android and iOS?
Or how can my calling code (which is cross-platform) prevent calls to the plugin on Chrome? But I don't know something like preprocessor #defines for platforms as we have with C/C++.
Best regards

**Comment by ekasetiawans** [comment]
@fbr-github you use simple condition 

```
import 'dart:io';
...
if (Platform.isAndroid || Platform.isIOS) {
  // background service calls
}
```
