### ISSUE TITLE
Doesn't work with Sqflite

### ISSUE THREAD

**Issue by HitendraRathod10** [ekasetiawans/flutter_background_service#117]
I try to fetch data from sqlite in main.dart. If put Toast for just testing it works proper in foreground and background. But doesn't work with method which is for fetching data. it gives error of pathprovider Like(MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider)).why i not getting data in another method in  main.dart which i used for background.

**Comment by ekasetiawans** [comment]
make sure you have add path_provider_android and path_provider_ios in your pubspec.yaml
and then, try to call plugin registration like below

```
// service onStart method
void onStart(){
  WidgetsFlutterBinding.ensureInitialized();
  
  if (Platform.isAndroid){
    PathProviderAndroid.registerWith();
  } else if (Platform.isIOS){
    PathProviderIOS.registerWith();
  }
}
```

**Comment by ekasetiawans** [comment]
https://github.com/flutter/flutter/issues/99155

**Comment by HitendraRathod10** [comment]
Thank You...Issue solved !!
