### ISSUE TITLE
Error with the latest version 1.0.4

### ISSUE THREAD

**Issue by andreichiritescu** [ekasetiawans/flutter_background_service#120]
Hello ,
after the update to the latest version 1.0.4 i have the following errors :
E/flutter (21170): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method setNotificationInfo on channel id.flutter/background_service_bg)
E/flutter (21170): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:175:7)
E/flutter (21170): <asynchronous suspension>

with version 0.2.6 everything is ok.

**Comment by ekasetiawans** [comment]
hi @andreichiritescu, we have changed some file, please make sure your project has migrated as the example 
https://github.com/ekasetiawans/flutter_background_service/blob/master/packages/flutter_background_service/example/ios/Runner/AppDelegate.swift at line 3 for iOS only
and

https://github.com/ekasetiawans/flutter_background_service/blob/master/packages/flutter_background_service/example/lib/main.dart at line 50 and 51
