### ISSUE TITLE
Stop background service when hide notification 

### ISSUE THREAD

**Issue by HitendraRathod10** [ekasetiawans/flutter_background_service#121]
I want to hide notification. For that i tried many different ways but when i hide notification background service is also stop.

**Comment by HitendraRathod10** [comment]
I also saw 
FlutterBackgroundService.initialize(yourStartMethod, foreground: false);
this But in my case i m not able to do this.
May be this is old version so that i facing this issue.

how can i hide notification from foreground and background?

**Comment by ekasetiawans** [comment]
started from version 1.0.4 you can call `setAsBackgroundService()` from the `onStart` method

**Comment by HitendraRathod10** [comment]
Thanks a lot !! Issue solved..!

**Comment by HitendraRathod10** [comment]
I got an issue.
when i do setAsBackgroundService() this for notification hide but background service is also stop .
it's not work proper.
let me tell u my scenario ,

In my method which i want to call in foreground and background i put toast for testing
then its work proper in foreground and background.
but when i comment code of toast --> background service will stop.
it shouldn't stop.

**Comment by ekasetiawans** [comment]
@HitendraRathod10 you have deal with background service limitations in android and also some custom android OS (e.g MIUI from Xiaomi) policy. Sometimes, custom android OS need extra configuration to allow an app to be automatically started, battery optimizations and also they have options to keep application running in the background.

**Comment by HitendraRathod10** [comment]
But i haven't any custom android OS. And I face this issue in every device.

**Comment by ekasetiawans** [comment]
@HitendraRathod10 did you also check the example project in this repository?

**Comment by HitendraRathod10** [comment]
Yes

**Comment by HitendraRathod10** [comment]
And In my method  it's work proper with toast then why not working without toast ?
That's the main issue.

**Comment by HitendraRathod10** [comment]
And In my method  it's work proper with toast then why not working without toast ?
That's the main issue.

**Comment by HitendraRathod10** [comment]
Getting crash !! 

Fatal Exception: android.app.RemoteServiceException: Context.startForegroundService() did not 
then call Service.startForeground(): ServiceRecord{67fd813 u0 
com.example.sms_scheduler/id.flutter.flutter_background_service.BackgroundService}
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1797)
   at android.os.Handler.dispatchMessage(Handler.java:106)
   at android.os.Looper.loop(Looper.java:176)
   at android.app.ActivityThread.main(ActivityThread.java:6651)
   at java.lang.reflect.Method.invoke(Method.java)
   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)

How can i solve it?

**Comment by HitendraRathod10** [comment]
This is my Code !!    

    Future<void> initializeService() async {
      try {
        final service = FlutterBackgroundService();
    
    await service.configure(
      androidConfiguration: AndroidConfiguration(
        // this will executed when app is in foreground or background in separated isolate
        onStart: onStart,

        // auto start service
        autoStart: true,
        isForegroundMode: true,
      ),
      iosConfiguration: IosConfiguration(
        // auto start service
        autoStart: true,

        // this will executed when app is in foreground in separated isolate
        onForeground: onStart,

        // you have to enable background fetch capability on xcode project
        onBackground: onIosBackground,
      ),
    );
     } on Exception catch (e) {
      // TODO
      print(e);
     }
    }

    void onStart() {
    try {
        // WidgetsFlutterBinding.ensureInitialized();

    if (Platform.isAndroid){PathProviderAndroid.registerWith();}
    else if (Platform.isIOS){PathProviderIOS.registerWith();}

    if (Platform.isIOS) FlutterBackgroundServiceIOS.registerWith();
    if (Platform.isAndroid) FlutterBackgroundServiceAndroid.registerWith();

    final service = FlutterBackgroundService();


    service.onDataReceived.listen((event) {
        if (event!["action"] == "setAsForeground") {
          service.setAsForegroundService();
          // service.setForegroundMode(true);
          return;
        }

        if (event["action"] == "setAsBackground") {
          service.setAsBackgroundService();
          // service.setForegroundMode(false);
        }

        if (event["action"] == "stopService") {
          service.stopService();
        }
      });

    service.setAsBackgroundService();
    // service.setAsForegroundService();

    // bring to foreground
    // service.setAsForegroundService();
    // service.setForegroundMode(true);
    // service.setNotificationInfo(title: "",content:"" );


    Timer.periodic(const Duration(seconds: 05), (timer) async {
      service.sendData(
          {
            "final_sms": sendFinalSMS(),
          }
      );
    });
     } on Exception catch (e) {
        // TODO
       print(e);
     }
    }
