### ISSUE TITLE
Cannot change notification icon.

### ISSUE THREAD

**Issue by zommerberg** [ekasetiawans/flutter_background_service#13]
Hello, I am not able to change the notification icon.
Adding a `ic_bg_service_small.xml` or `ic_bg_service_small.png` to the drawable folder or even to every drawable folder(hdpi,mdpi...) does not change the icon.

**Comment by ekasetiawans** [comment]
I have updated the example to change notification icon.
Here https://github.com/ekasetiawans/flutter_background_service/commit/a50e2b245da57482cb02427a089744f9c81aa6e1

**Comment by zommerberg** [comment]
Thank you, this works!

**Comment by kmac** [comment]
I'm not too familiar with drawable-anydpi... But looking at https://stackoverflow.com/questions/34156957/what-is-the-difference-between-anydpi-and-nodpi, does it not take precendence over any of the other drawable resources? The implication of this is that none of the other drawables are used and that you need to provide a new drawable-anydpi resource which is a scalable vector? 

The reason that I'm asking is that I am trying to use this but I'm having trouble replacing the icon. I have proper ic_bg_service_small.png files across the drawable-mdpi,-hdpi,-xhdpi,-xxhdpi directories but it's always using the default, which I now thing is probably coming from the packages drawable-anydpi-v24/ic_bg_service_small.xml file.

**Comment by ekasetiawans** [comment]
@kmac make sure you added icon to these folders.
https://github.com/ekasetiawans/flutter_background_service/tree/master/android/src/main/res
