### ISSUE TITLE
Cant run a Function in background

### ISSUE THREAD

**Issue by AdelSadiq** [ekasetiawans/flutter_background_service#131]
I'm a beginner,

How can i run a function in background using this package.
eg: void example() {
  print('Hello, Dart');
}

**Comment by ekasetiawans** [comment]
@AdelSadiq please provide reproducible code or a sample project.

**Comment by AdelSadiq** [comment]
I want to run this code in background. 

code:
getCallLogs() async {
    var now = DateTime.now();
    var dt1 = DateTime.parse(dbputtime!);
    var diff = now.difference(dt1);
    int from = now.subtract(Duration(seconds: diff.inSeconds)).millisecondsSinceEpoch;

    var result = await CallLog.query(dateFrom: from);
    setState(() {
      _callLogEntries = result;
    });
  }

**Comment by AdelSadiq** [comment]
I want to run this code in background.

code:
`getCallLogs() async {
var now = DateTime.now();
var dt1 = DateTime.parse(dbputtime!);
var diff = now.difference(dt1);
int from = now.subtract(Duration(seconds: diff.inSeconds)).millisecondsSinceEpoch;
var result = await CallLog.query(dateFrom: from);
setState(() {
  _callLogEntries = result;
});
}`

**Comment by AdelSadiq** [comment]
i want to run this run code in background.

```
getCallLogs() async {
var now = DateTime.now();
var dt1 = DateTime.parse(dbputtime!);
var diff = now.difference(dt1);
int from = now.subtract(Duration(seconds: diff.inSeconds)).millisecondsSinceEpoch;
var result = await CallLog.query(dateFrom: from);
setState(() {
  _callLogEntries = result;
});
}
```

**Comment by AdelSadiq** [comment]
i want to run this run code in background every 1 minute.

getCallLogs() async { var now = DateTime.now(); var dt1 = DateTime.parse(dbputtime!); var diff = now.difference(dt1); int from = now.subtract(Duration(seconds: diff.inSeconds)).millisecondsSinceEpoch; var result = await CallLog.query(dateFrom: from); setState(() { _callLogEntries = result; }); }

**Comment by ekasetiawans** [comment]
@AdelSadiq sorry, without reproducible code or a sample project I can't help too much. FYI, we can execute any method from a background service as long as it doesn't require UI or user interaction. 
Here is a sample project to use this package, https://github.com/ekasetiawans/flutter_background_service/tree/master/packages/flutter_background_service/example
