### ISSUE TITLE
crash on IOS

### ISSUE THREAD

**Issue by mkranus** [ekasetiawans/flutter_background_service#132]
Error when stopping a service:

```
*** Assertion failure in -[FlutterEngine sendOnChannel:message:binaryReply:], FlutterEngine.mm:939
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Sending a message before the FlutterEngine has been run.'
*** First throw call stack:
(0x180ff90fc 0x199849d64 0x1828b539c 0x104f279e4 0x1029162d4 0x102916514 0x10541e744 0x104f57c78 0x1052e5b3c 0x10520d148 0x105210eac 0x18100e318 0x180f92cf0 0x180f8d4ec 0x180f6bd08 0x180f7f468 0x19cb2338c 0x1839225d0 0x1836a0f74 0x1022a4950 0x102709aa4)
libc++abi: terminating with uncaught exception of type NSException
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
    frame #0: 0x00000001b8559964 libsystem_kernel.dylib`__pthread_kill + 8
libsystem_kernel.dylib`__pthread_kill:
->  0x1b8559964 <+8>:  b.lo   0x1b8559984               ; <+40>
    0x1b8559968 <+12>: pacibsp 
    0x1b855996c <+16>: stp    x29, x30, [sp, #-0x10]!
    0x1b8559970 <+20>: mov    x29, sp
Target 0: (Runner) stopped.
```

**Flutter version: 2.10.4**
**plugin version: 2.0.0-dev.1**

**Comment by ekasetiawans** [comment]
hi @mkranus does that happen to the sample project too?

**Comment by SimonTellier** [comment]
hi
i have same problem with new test project on iOS

Flutter 2.10.4
flutter_background_service: ^2.0.0-dev.1

**Comment by mkranus** [comment]
> hi @mkranus does that happen to the sample project too?

I haven't tried on the sample project, but I copied the code from the example on pub.dev.

**Comment by ekasetiawans** [comment]
@mkranus @SimonTellier this plugins require extra settings for iOS, please read https://github.com/ekasetiawans/flutter_background_service/blob/master/packages/flutter_background_service/README.md

and also, you should test the sample project here https://github.com/ekasetiawans/flutter_background_service/tree/master/packages/flutter_background_service/example

**Comment by mkranus** [comment]
> @mkranus @SimonTellier this plugins require extra settings for iOS, please read https://github.com/ekasetiawans/flutter_background_service/blob/master/packages/flutter_background_service/README.md
> 
> and also, you should test the sample project here https://github.com/ekasetiawans/flutter_background_service/tree/master/packages/flutter_background_service/example
> 
> here is also extra step to be added in your project https://github.com/ekasetiawans/flutter_background_service/blob/master/packages/flutter_background_service/example/ios/Runner/AppDelegate.swift

I did make the IOS specific changes to my project. I will try to test the sample project when I get back to my workstation.

**Comment by SimonTellier** [comment]
@ekasetiawans same error with https://github.com/ekasetiawans/flutter_background_service/tree/master/packages/flutter_background_service/example

```*** Assertion failure in -[FlutterEngine sendOnChannel:message:binaryReply:], FlutterEngine.mm:939
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Sending a message before the FlutterEngine has been run.'
*** First throw call stack:
(0x1805590fc 0x198da9d64 0x181e1539c 0x1067539e4 0x1043a60d4 0x1043a6334 0x106c4a744 0x106783c78 0x106b11b3c 0x106a39148 0x106a3ceac 0x18056e318 0x1804f2cf0 0x1804ed4ec 0x1804cbd08 0x1804df468 0x19c08338c 0x182e825d0 0x182c00f74 0x10404b028 0x10430daa4)
libc++abi: terminating with uncaught exception of type NSException
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
    frame #0: 0x00000001b7b44964 libsystem_kernel.dylib`__pthread_kill + 8
libsystem_kernel.dylib`__pthread_kill:
->  0x1b7b44964 <+8>:  b.lo   0x1b7b44984               ; <+40>
    0x1b7b44968 <+12>: pacibsp
    0x1b7b4496c <+16>: stp    x29, x30, [sp, #-0x10]!
    0x1b7b44970 <+20>: mov    x29, sp
Target 0: (Runner) stopped.
Lost connection to device.```

info.plist
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>BGTaskSchedulerPermittedIdentifiers</key>
	<array>
		<string>dev.flutter.background.refresh</string>
	</array>
	<key>CFBundleDevelopmentRegion</key>
	<string>$(DEVELOPMENT_LANGUAGE)</string>
	<key>CFBundleDisplayName</key>
	<string>Example</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>example</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>$(FLUTTER_BUILD_NAME)</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleVersion</key>
	<string>$(FLUTTER_BUILD_NUMBER)</string>
	<key>LSRequiresIPhoneOS</key>
	<true/>
	<key>UIBackgroundModes</key>
	<array>
		<string>fetch</string>
		<string>processing</string>
	</array>
	<key>UILaunchStoryboardName</key>
	<string>LaunchScreen</string>
	<key>UIMainStoryboardFile</key>
	<string>Main</string>
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UISupportedInterfaceOrientations~ipad</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationPortraitUpsideDown</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UIViewControllerBasedStatusBarAppearance</key>
	<false/>
</dict>
</plist>

```

**Comment by ekasetiawans** [comment]
hi @SimonTellier  @mkranus I have update v2.0.0-dev.2 would you check the latest version?

Working fine in my side
<img width="561" alt="image" src="https://user-images.githubusercontent.com/20693888/162405531-897a3b12-1886-4f37-8cf7-315a79497cad.png">

**Comment by mkranus** [comment]
The update fixes the issue, thanks @ekasetiawans
