### ISSUE TITLE
MissingPluginException(No implementation found for method stopService on channel id.flutter/background_service_android_bg)

### ISSUE THREAD

**Issue by theboshy** [ekasetiawans/flutter_background_service#133]
I am trying to use the background service to receive messages even when the application is closed but I need to turn off the service as soon as my user logs out, the problem is that whenever I call the method

`_service.stopService()`

i get this error:

`MissingPluginException(No implementation found for method stopService on channel id.flutter/background_service_android_bg)`

I honestly have no idea what this means,

here is my code 

```javascript
class BackgroundServiceHandler {
  BackgroundServiceHandler();

  Function(String msg)? logger;
  final _service = FlutterBackgroundService();

  static bool _isRunning = false;
  bool get isRunning => _isRunning;

  void info(String msg) {
    final _msg = "${DateTime.now().toIso8601String()} : $msg.";
    if (logger != null) logger!(_msg);
    debugPrint(_msg);
  }

  Future<bool> config() async {
    return await _service.configure(
      iosConfiguration: IosConfiguration(
        onForeground: onForeground,
        onBackground: onBackground,
      ),
      androidConfiguration: AndroidConfiguration(
        onStart: onStart,
        isForegroundMode: false,
        autoStart: false
      ),
    );
  }

  Future<bool> start() async {
    return await _service.startService();
  }
  Future<void> stop() async {
    _service.stopService();
  }

  Future<bool> init() async {
    WidgetsFlutterBinding.ensureInitialized();
    info('running');
    if (_isRunning) {
      return false;
    }
    _isRunning = true;
    info('config');
    final configureResult = await config();
    info('configured: $configureResult');
    await start();
    return true;
  }
}
```

based on this one [here](https://github.com/ekasetiawans/flutter_background_service/issues/126)

and am implementing this class like this 

```javascript
Future initBackgroundService() async {
    await BackgroundServiceHandler().init();
  }
```

It works just fine and starts the service so I can't understand why this:

```javascript
BackgroundServiceHandler().stop();
```

 don't work??

i also tried this:

```javascript
_service.sendData({"action": "stopService"});
```

but it does nothing the service keeps running the listener is never executed,

here is the full error 

```javascript
E/flutter (14448): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method stopService on channel id.flutter/background_service_android_bg)
E/flutter (14448): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:175:7)
E/flutter (14448): <asynchronous suspension>
```

Recreate the error
- first, i call  `initBackgroundService()` to start the configuration and then start the service
- then after i while when my user press log out i `callBackgroundServiceHandler().stop()` and show me the error

am using **flutter_background_service: ^1.0.4**

**Comment by ekasetiawans** [comment]
@theboshy stopService only available from the background isolate. You can't call it from the UI isolate.
I have updated version to 2.0.0-dev to make it more easier to understand

**Comment by theboshy** [comment]
@ekasetiawans thanks for your response but i also tried calling this `_service.sendData({"action": "stopService"});`, but it never triger the `service.onDataReceived.listen`, is that what you mean?

**Comment by ekasetiawans** [comment]
@theboshy you can update to the latest plugin version, it has breaking about data sharing between service and ui.
