### ISSUE TITLE
Not receiving any 'update' callbacks

### ISSUE THREAD

**Issue by cpf5193** [ekasetiawans/flutter_background_service#134]
I'm using [awesome_notifications][1] and [flutter_background_service][2] in conjunction to update some app state when receiving data notifications from FirebaseMessaging. As noted in the awesome_notifications, the background message handler must be a top-level function, so I am using flutter_background_service to pass data to the main isolate and update app state.

```
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await initializeBackgroundService();
  FirebaseMessaging.onBackgroundMessage(_backgroundMessageHandler);
  _initLocalNotifications();
  runApp(MyApp());
}
```

I'm initializing the background service similarly to the example in flutter_background_service:

```
Future<void> initializeBackgroundService() async {
  final service = FlutterBackgroundService();
  await service.configure(
    androidConfiguration: AndroidConfiguration(
      onStart: onStart,
      autoStart: true,
      isForegroundMode: true,
    ),
    iosConfiguration: IosConfiguration(
      autoStart: true,
      onForeground: onStart,
      onBackground: onIosBackground,
    ),
  );
  await service.startService();
}
```

and invoking update in the _backgroundMessageHandler when a notification is received:

```
Future<void> _backgroundMessageHandler(
  RemoteMessage message,
) async {
  final service = FlutterBackgroundService();

  ...

  service.invoke('update', {
    'key1': 'val1',
    'key2': 'val2',
  });
}

```

And in the StatefulWidget for my app in the main isolate, I'm listening on the update call to receive the data:

```
void listenForNotificationData() {
  final backgroundService = FlutterBackgroundService();
  backgroundService.on('update').listen((event) async {
    print('received data message in feed: $event');
  }, onError: (e, s) {
    print('error listening for updates: $e, $s');
  }, onDone: () {
    print('background listen closed');
  });
}
```

It's never invoking the listen callback on the 'update' event. I can confirm it's calling the invoke('update') portion and calling on('update').listen, but never receiving the update. It also doesn't seem to be erroring out. Am I missing a step somewhere here?

  [1]: https://pub.dev/packages/awesome_notifications/example
  [2]: https://pub.dev/packages/flutter_background_service/example

**Comment by cpf5193** [comment]
I just saw the part where I need to use the ServiceInstance for all background isolate portions, but I'm unsure how I would pass it to my background message handler if the callback must be a top-level, non-anonymous function:

```
void onStart(ServiceInstance service) {
  if (Platform.isIOS) FlutterBackgroundServiceIOS.registerWith();
  if (Platform.isAndroid) FlutterBackgroundServiceAndroid.registerWith();

  FirebaseMessaging.onBackgroundMessage(_backgroundMessageHandler);
}
```

```
Future<void> _backgroundMessageHandler(
  RemoteMessage message,
) async {
  // How do I get service here?
  service.invoke('update', {
    'key1': 'val1',
    'key2': 'val2',
  });
}
```

**Comment by cpf5193** [comment]
I was able to pass it through a static instance, but still not getting the listen callback invoked

**Comment by paraslamsong** [comment]
Same here
invoke from background is sent but cannot listen from foreground
