### ISSUE TITLE
MissingPluginException - SharedPref

### ISSUE THREAD

**Issue by Christer-Muntean** [ekasetiawans/flutter_background_service#136]
I'm developing on iOS, and I'm not able to get value from SharedPref in background. Havn't tested on Android.

`[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)`

```
void onStart(ServiceInstance service) async {
   ...
   final pref = await SharedPreferences.getInstance();
   final value = pref.getString('key');
   ...
```

**Comment by ekasetiawans** [comment]
Marked as duplicated of #138
