### ISSUE TITLE
MissingPluginException when using external plugins (SharedPreferences, PathProvider, etc)

### ISSUE THREAD

**Issue by ekasetiawans** [ekasetiawans/flutter_background_service#138]
When we use external plugin in background service, MissingPluginException will be thrown. This happens because the plugin we are using is not registered in the background service isolate (flutter engine) yet. To avoiding it, we have workaround below:

For Flutter prior to version 3.0.0, we have to call this code depending what plugins you use.

```
void onStart(ServiceInstance service){
  ...
  if (Platform.isIOS) YourPluginIOS.registerWith();
  if (Platform.isAndroid) YourPluginAndroid.registerWith();
  ...
}
```

For Flutter version 3.0.0 and later, there is generated class to register all of plugins. So we can call like this
```
void onStart(ServiceInstance service){
  ...
  DartPluginRegistrant.ensureInitialized();
  ...
}
```

**Comment by ZiaUrRahmam** [comment]
> void onStart(){
>   ...
>   if (Platform.isIOS) YourPluginIOS.registerWith();
>   if (Platform.isAndroid) YourPluginAndroid.registerWith();
>   ...
> }
@ekasetiawans  I don't get  by **YourPluginAndroid**
As I am using  path provider. So please may you mention how will the  _YourPluginAndroid_ be filled?

**Comment by ekasetiawans** [comment]
@ZiaUrRahmam sorry for unclear information, you have to replace YourPluginAndroid or YourPluginIOS with the plugin you using.

**Comment by ReggieMiller1** [comment]
i faced the same issue as well but with GetStorage & i tried using shared preferences but i kept on getting an exception. otherwise this is a great plugin and it so unfortunate that i could not preform what i wanted.

**Comment by ekasetiawans** [comment]
@ReggieMiller1 the easiest way is try to use flutter beta channel. So, you will not be confused to register the plugins because you only need call DartPluginRegistrant.ensureInitialized()

**Comment by ReggieMiller1** [comment]
> @ReggieMiller1 the easiest way is try to use flutter beta channel. So, you will not be confused to register the plugins because you only need to call DartPluginRegistrant.ensureInitialized()

alright i get you bro but please give me an example on how to do it **DartPluginRegistrant.ensureInitialized()**

**Comment by ekasetiawans** [comment]
@ReggieMiller1 I already mentioned it at the top of this page. You should to call the method in `void onStart(ServiceInstance service)` method that used by FlutterBackgroundService.configure.

**Comment by ReggieMiller1** [comment]
> @ReggieMiller1 I already mentioned it at the top of this page. You should to call the method in `void onStart(ServiceInstance service)` method that used by FlutterBackgroundService.configure.

thanks bro...i did what you said, at first i didnt understand but now everything works fine. thanks once again.

**Comment by lel101** [comment]
@ekasetiawans I tried the above solution, but other error occur.
`2022-05-06 11:43:44.376688+0800 Runner[40780:421791] [VERBOSE-2:ui_dart_state.cc(198)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)`

**Comment by lel101** [comment]
btw it happens when socket IO is inside the flutter_background_service and SharedPreferences.getInstance() is called when have a coming notifications.

`Future<void> onStart(ServiceInstance service) async {  
  DartPluginRegistrant.ensureInitialized();

 socket?.on('receive-notify-user', (data) async {//If this socket is triggered
      SharedPreferences pref = await SharedPreferences.getInstance();// Error occur here.
 });
`

**Comment by lel101** [comment]
@ekasetiawans any updates ?

**Comment by hassanali2596** [comment]
What do you mean by this :

 void onStart(ServiceInstance service){
  ...
  if (Platform.isIOS) YourPluginIOS.registerWith();
  if (Platform.isAndroid) YourPluginAndroid.registerWith();
  ...
}


I tried to replace "YourPluginIOS"  and "YourPluginAndroid" by Shared prefe (for example), but the method registerWith() is not defined with any plugin.

**Comment by ekasetiawans** [comment]
@hassanali2596 You have to add https://pub.dev/packages/shared_preferences_ios and https://pub.dev/packages/shared_preferences_android depending to your target platform.

If you already using flutter 3, you can call `DartPluginRegistrant.ensureInitialized()` instead, it will register our plugins automatically.

**Comment by lel101** [comment]
@ekasetiawans 
I already tried it , but another error occur.

`2022-05-06 11:43:44.376688+0800 Runner[40780:421791] [VERBOSE-2:ui_dart_state.cc(198)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)`

**Comment by lel101** [comment]
@ekasetiawans 
I already upgrade my flutter to 3, still having issue.

`[VERBOSE-2:ui_dart_state.cc(198)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)`

**Comment by ekasetiawans** [comment]
@lel101 that is different issue

**Comment by lel101** [comment]
@ekasetiawans 
ahh I see thanks, is there any fix or workaround for this issue ?

**Comment by ekasetiawans** [comment]
@lel101 you have to make sure which plugin that throws the error

**Comment by lel101** [comment]
@ekasetiawans 

It throws error in SharedPreferences.getInstance();

Before the error was MissingPluginException but after the flutter upgrade to 3 and added the line DartPluginRegistrant.ensureInitialized(); the error change to PlatformException.

```
Future<void> onStart(ServiceInstance service) async {
    DartPluginRegistrant.ensureInitialized();
    SharedPreferences pref = await SharedPreferences.getInstance();
}
```

**Comment by ekasetiawans** [comment]
@lel101 which platform are you targeting? iOS or Android?

**Comment by lel101** [comment]
@ekasetiawans IOS

**Comment by ekasetiawans** [comment]
@lel101 okay, I will check it after work

**Comment by ekasetiawans** [comment]
hi everyone, sorry for late
I have published the version 2.1.0.

@lel101 your issue is caused by the plugins not being registered in the iOS native side. I have update the version 2.1.0 to remove requirement for it, so I think it will be resolved once you update the dependency version.

**Comment by lel101** [comment]
@ekasetiawans 
I already test it and now it works fine. Thank you so much.

**Comment by nguyenphuc1995** [comment]
What if the plugin dont have registerWith() ?
try
` DartPluginRegistrant.ensureInitialized();`
with no luck, only work when app forground, background, not work when app is killed

**Comment by vietstone-ng** [comment]
Hi, I'm using record (https://pub.dev/packages/record). I tried `DartPluginRegistrant.ensureInitialized()`, and it doesn't has `registerWith()`
Please help.
The exception:
`E/flutter ( 9952): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method start on channel com.llfbandit.record/messages)`
The package's code of v4.4.4: https://github.com/llfbandit/record/tree/404505e308d21cf7f0dc5ec180b213f7c26d3dd7

**Comment by vietstone-ng** [comment]
@nguyenphuc1995 Did you find a way to overcome the problem?

**Comment by jorgemcga** [comment]
I'm facing this kind of error, but it is when I use MethodChannel inside onStart function.
Is there a way to workaround that?

This is my code:
@pragma('vm:entry-point')
Future<void> onStart(ServiceInstance service) async {
  WidgetsFlutterBinding.ensureInitialized();
  DartPluginRegistrant.ensureInitialized();
  RootIsolateToken rootIsolateToken = RootIsolateToken.instance!;
  BackgroundIsolateBinaryMessenger.ensureInitialized(rootIsolateToken);

  const channel = MethodChannel('KotlinChannel');
  try {
    final String result = await channel
        .invokeMethod('startBackgroundTask', {'input': 'Olá do Dart!'});
    debugPrint(result);
  } catch (e) {
    final result = "Erro ao chamar o método Kotlin: '${e}'";
    debugPrint(result);
  }
}
