### ISSUE TITLE
keeps turning on phone LED lights

### ISSUE THREAD

**Issue by MohammadAminZamaniAfshar** [ekasetiawans/flutter_background_service#139]
### i tried all of them and they have this problem

![image](https://user-images.githubusercontent.com/88077166/164943336-072b3c2b-ab1a-424e-aa4a-27bad88ea875.png)

## here is the code
`import 'dart:async';

import 'package:flutter_background_service/flutter_background_service.dart';

FlutterBackgroundService _service = FlutterBackgroundService();

Future<void> initializeBackgroundService() async {
  await _service.configure(
    androidConfiguration: AndroidConfiguration(
      onStart: backgroundTask,
      isForegroundMode: false,
      autoStart: false,
    ),
    iosConfiguration: IosConfiguration(
      onForeground: backgroundTask,
      onBackground: backgroundTask,
      autoStart: false,
    ),
  );
  _service.startService();
}

Future<bool> backgroundTask(ServiceInstance service) {
  Timer.periodic(Duration(seconds: 1), (timer) {
    print('backgroundTask');
  });
  return Future.value(true);
}
`

**Comment by ekasetiawans** [comment]
hi @MohammadAminZamaniAfshar thanks for the report, unfortunately I don't have a device with LEDs to reproduce this issue.

**Comment by MohammadAminZamaniAfshar** [comment]
I fixed it by changing importance of notification in `BackgroundService.java` file
![image](https://user-images.githubusercontent.com/88077166/165711772-3a853db9-0b22-4652-a938-93a6ff58afd0.png)

**Comment by ekasetiawans** [comment]
i think, it can be caused by notification channel priority. Could you try to change the notification priority on the application setting?

**Comment by MohammadAminZamaniAfshar** [comment]
Recentlly i tried the last version of package(2.1.3) and this problem is fixed but not completely
When service starts(no matter on foreground mode or background mode) the phone lights turning on for a few seconds and then they turned off 
I also change the notification priority on the application setting and nothing changed
Only when i turned on save power mode , phone lights didn't turn on when service start


https://user-images.githubusercontent.com/88077166/175516754-70d4779e-2574-495c-aa21-465b647e9d1b.mp4
