### ISSUE TITLE
How to call function in background at every 30 seconds even user is online or offline?

### ISSUE THREAD

**Issue by invennicoofficial** [ekasetiawans/flutter_background_service#140]
Can you reply to me ASAP, I want to call a function in the foreground and background every 30 seconds even when the user is online and offline.

**Comment by ekasetiawans** [comment]
it's can be done using Timer.periodic. However, we can't do it on iOS in background mode because the OS doesn't support long running background tasks.

**Comment by invennicoofficial** [comment]
> it can be done using Timer.periodic. However, we can't do it on iOS in background mode because the OS doesn't support long running background tasks.

Already Implemented Timer but this works only when the device in the foreground state what to do for the background?

**Comment by NOTtheKRish** [comment]
Hi @invennicoofficial ... Did you found the solution to your problem??? Me too facing the same issue... The function gets called in Foreground.... but when the app goes to background... the function doesn't gets called... Kindly let me know, if you found solution...
