### ISSUE TITLE
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method getCurrentPosition on channel flutter.baseflow.com/geolocator)

### ISSUE THREAD

**Issue by Saikiran24** [ekasetiawans/flutter_background_service#141]
Getting this issue when running location in Service

[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method getCurrentPosition on channel flutter.baseflow.com/geolocator)

**Comment by ekasetiawans** [comment]
Duplicated of #138
