### ISSUE TITLE
When starting service from background get UnimplementedError

### ISSUE THREAD

**Issue by RUSSCITY** [ekasetiawans/flutter_background_service#143]
Hello, I try to use your sample code to start service after receiving FCM. It works perfect when the app is in foreground, but when getting FCM from background I get the exception:

```
I/flutter (32288): 1651155541628: Handling a background message: 0:1651155540492810%866d403cf9fd7ecd
E/flutter (32288): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: UnimplementedError
E/flutter (32288): #0      MethodChannelFlutterBackgroundService.configure (package:flutter_background_service_platform_interface/src/method_channel_flutter_background_service.dart:12:5)
E/flutter (32288): #1      FlutterBackgroundService.configure (package:flutter_background_service/flutter_background_service.dart:16:17)
E/flutter (32288): #2      initializeServiceForSocketConnection (package:alltrackervideosecurity/application/socket/background_socket_service.dart:13:17)
E/flutter (32288): #3      handleDataMessage (package:alltrackervideosecurity/application/notifications/notifications_service.dart:127:5)
E/flutter (32288): #4      _firebaseMessagingBackgroundHandler (package:alltrackervideosecurity/application/notifications/notifications_service.dart:107:5)
E/flutter (32288): <asynchronous suspension>
E/flutter (32288): #5      _firebaseMessagingCallbackDispatcher.<anonymous closure> (package:firebase_messaging_platform_interface/src/method_channel/method_channel_messaging.dart:46:9)
E/flutter (32288): <asynchronous suspension>
E/flutter (32288): #6      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:414:42)
E/flutter (32288): <asynchronous suspension>
E/flutter (32288): #7      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:377:22)
E/flutter (32288): <asynchronous suspension>
```

I'm trying to initialize it 1:1 like your sample code:
```
Future<void> initializeServiceForSocketConnection() async {
  final service = FlutterBackgroundService();
  await service.configure(
    androidConfiguration: AndroidConfiguration(
      // this will executed when app is in foreground or background in separated isolate
      onStart: onStart,

      // auto start service
      autoStart: true,
      isForegroundMode: true,
    ),
    iosConfiguration: IosConfiguration(
      // auto start service
      autoStart: true,

      // this will executed when app is in foreground in separated isolate
      onForeground: onStart,

      // you have to enable background fetch capability on xcode project
      onBackground: onIosBackground,
    ),
  );

  if (!await service.isRunning()) {
    service.startService();
  }
}
```

My configurations:
```
[√] Flutter (Channel stable, 2.10.5, on Microsoft Windows [Version 10.0.19043.1645], locale de-DE)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.5)
[√] Android Studio (version 2021.1)
[√] IntelliJ IDEA Ultimate Edition (version 2021.2)
[√] VS Code (version 1.62.3)
[√] Connected device (7 available)
[√] HTTP Host Availability

• No issues found!
```

I'm using:
```
  flutter_background_service: ^2.0.0
```

Please help to solve this! 🙏

**Comment by RUSSCITY** [comment]
@ekasetiawans thank you very much for the fast answer! 
Does it mean I cannot start a background(foreground) service from a background thread? 
Or are there any possibility to trigger UI thread from background?

**Comment by RUSSCITY** [comment]
sorry, I think I understand what you mean. I have to call configure once from main, but can then start the service from background thread. I will try it right now.

**Comment by ekasetiawans** [comment]
we have to call .configure method from the UI at least once until app uninstalled from the phone. After that, the service will automatically start every boot and after a few seconds or minutes when app killed by system.

**Comment by ekasetiawans** [comment]
if you wish to call FlutterBackgroundService.configure from the another isolate, you can trying to calling this as the first command in your isolate method.

```
WidgetsFlutterBinding.ensureInitialized();

if (Platform.isIOS) FlutterBackgroundServiceIOS.registerWith();
if (Platform.isAndroid) FlutterBackgroundServiceAndroid.registerWith();
```

**Comment by RUSSCITY** [comment]
Sadly I had the same problem when calling `startService()` from background thread. I got the `UnimplementedError` even after I did the config from UI thread. 
But your previous suggestion with `registerWith` helped me to fix this problem. I think you can close this issue. Thank you a lot!

**Comment by ekasetiawans** [comment]
@RUSSCITY by default, all methods in FlutterBackgroundService class are only available for main isolate (UI) registered by GeneratedPluginRegistrant class. If you want to use those methods, you need to register the plugin first to create a proper binding with the Platform Channel.

**Comment by ekasetiawans** [comment]
When the current flutter beta channel lands to stable. We can use `DartPluginRegistrant.ensureInitialized()` to register all the plugins we use in the project.

**Comment by RUSSCITY** [comment]
@ekasetiawans  sadly I still have some problems with the plugin, when I try to provide some data to UI. 
I will try to describe the problem as clear as possible. 

1. I get a FCM which start a method in an isolate. 
2. I create then a foreground service (it starts in own isolate) using "registerWith" like described above in your comment. It's "onStart" runs in a new isolate. I can communicate between these two isolates via `invoke` `on`. 
3. But the main UI thread gets no event. I tried `on`, and `StreamBuilder` like in your example (which works fine, because, I think, the service is created from UI isolate. 

Do you think there are some other possibilities I can communicate from service to UI and vice versa?
