### ISSUE TITLE
unable to pass object in invoke method

### ISSUE THREAD

**Issue by EmelianShkira** [ekasetiawans/flutter_background_service#148]
whenever i try to pass object as Value of key in map<string, dynamic> args in invoke method it throw error "converting object to an encodable object failed"
i want to pass instance of my agora client to your plugin.. cause i try to access it from your plugin using state or using navigator key but can't access both of them

**Comment by ekasetiawans** [comment]
Only primitives is supported. See: https://api.flutter.dev/flutter/dart-isolate/SendPort/send.html

**Comment by EmelianShkira** [comment]
so there's no way at all to pass this object?
what about state or navigator key.. also i can't access them from your isolate

**Comment by ekasetiawans** [comment]
@EmelianShkira since it's a Dart Isolate limitation, there's nothing we can do about it.

**Comment by EmelianShkira** [comment]
okay thanks for your help

**Comment by amalinivos** [comment]
@ekasetiawans hi how do you access the data that pass through the invoke method ?

**Comment by kevin4dhd** [comment]
> whenever i try to pass object as Value of key in map<string, dynamic> args in invoke method it throw error "converting object to an encodable object failed" i want to pass instance of my agora client to your plugin.. cause i try to access it from your plugin using state or using navigator key but can't access both of them

Did you manage to solve it? I am looking to implement agora in the background
