### ISSUE TITLE
pub get failed (1; So, because aws_test depends on flutter_background_service ^2.0.0, version solving failed.)

### ISSUE THREAD

**Issue by hailuongsl97** [ekasetiawans/flutter_background_service#150]
please help me to solve the problem

![image](https://user-images.githubusercontent.com/57215412/167369815-fc39688e-7da4-46c2-8b47-5ccba4be6167.png)

**Comment by ekasetiawans** [comment]
Update your flutter sdk to the latest stable version and update the sdk constraint at line 21 to `">=2.16.1 <3.0.0"`
