### ISSUE TITLE
Service restarts automatically at unwanted times

### ISSUE THREAD

**Issue by Teckinfor** [ekasetiawans/flutter_background_service#153]
Hello,

Is it normal that my service restarts by itself when I close the UI or when my phone goes to sleep by itself, or in the morning when I pick up the phone for the first time of the day?

Since it loops over a time interval, I would like to avoid it to restart :/. 

Thanks in advance for your help

**Comment by ekasetiawans** [comment]
hi @Teckinfor, that's normal. Sometimes, the system needs more resources. if no more resources are available, the system will start shutting down background apps. However, our background service is designed to restart after a few seconds or minutes.

**Comment by ekasetiawans** [comment]
If you have any questions (not an issue) you can reach me at https://maseka.dev.
Closing this for now.

**Comment by Teckinfor** [comment]
Thank you for your response.
So it's impossible to avoid it ?

**Comment by ekasetiawans** [comment]
@Teckinfor some device manufacturers have custom android os e.g. MIUI, there is a feature to lock apps without getting killed while system optimization. But unfortunately, we don't have a control to do that programmatically.
