### ISSUE TITLE
app crash when application ForegroundMode

### ISSUE THREAD

**Issue by Fuzelmomin** [ekasetiawans/flutter_background_service#154]
E/AndroidRuntime(15670): FATAL EXCEPTION: main
E/AndroidRuntime(15670): Process: com.example, PID: 15670
E/AndroidRuntime(15670): java.lang.RuntimeException: Unable to destroy activity {com.example/com.example.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.lifecycle.Lifecycle.removeObserver(androidx.lifecycle.LifecycleObserver)' on a null object reference
E/AndroidRuntime(15670): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4648)
E/AndroidRuntime(15670): 	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4666)
E/AndroidRuntime(15670): 	at android.app.ActivityThread.-wrap5(Unknown Source:0)
E/AndroidRuntime(15670): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794)
E/AndroidRuntime(15670): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(15670): 	at android.os.Looper.loop(Looper.java:164)
E/AndroidRuntime(15670): 	at android.app.ActivityThread.main(ActivityThread.java:7025)
E/AndroidRuntime(15670): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(15670): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
E/AndroidRuntime(15670): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
E/AndroidRuntime(15670): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.lifecycle.Lifecycle.removeObserver(androidx.lifecycle.LifecycleObserver)' on a null object reference
E/AndroidRuntime(15670): 	at com.amolg.flutterbarcodescanner.FlutterBarcodeScannerPlugin.clearPluginSetup(FlutterBarcodeScannerPlugin.java:295)
E/AndroidRuntime(15670): 	at com.amolg.flutterbarcodescanner.FlutterBarcodeScannerPlugin.onDetachedFromActivity(FlutterBarcodeScannerPlugin.java:285)
E/AndroidRuntime(15670): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.detachFromActivity(FlutterEngineConnectionRegistry.java:392)
E/AndroidRuntime(15670): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onDetach(FlutterActivityAndFragmentDelegate.java:653)
E/AndroidRuntime(15670): 	at io.flutter.embedding.android.FlutterFragment.onDetach(FlutterFragment.java:844)
E/AndroidRuntime(15670): 	at androidx.fragment.app.Fragment.performDetach(Fragment.java:3229)
E/AndroidRuntime(15670): 	at androidx.fragment.app.FragmentStateManager.detach(FragmentStateManager.java:812)
E/AndroidRuntime(15670): 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:353)
E/AndroidRuntime(15670): 	at androidx.fragment.app.SpecialEffectsController$FragmentStateManagerOperation.complete(SpecialEffectsController.java:742)
E/AndroidRuntime(15670): 	at androidx.fragment.app.SpecialEffectsController$Operation.cancel(SpecialEffectsController.java:594)
E/AndroidRuntime(15670): 	at androidx.fragment.app.SpecialEffectsController.forceCompleteAllOperations(SpecialEffectsController.java:329)
E/AndroidRuntime(15670): 	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3132)
E/AndroidRuntime(15670): 	at androidx.fragment.app.FragmentManager.dispatchDestroy(FragmentManager.java:3107)
E/AndroidRuntime(15670): 	at androidx.fragment.app.FragmentController.dispatchDestroy(FragmentController.java:334)
E/AndroidRuntime(15670): 	at androidx.fragment.app.FragmentActivity.onDestroy(FragmentActivity.java:330)
E/AndroidRuntime(15670): 	at com.example.beta_jellie.MainActivity.onDestroy(MainActivity.kt:163)
E/AndroidRuntime(15670): 	at android.app.Activity.performDestroy(Activity.java:7595)
E/AndroidRuntime(15670): 	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1257)
E/AndroidRuntime(15670): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4635)
E/AndroidRuntime(15670): 	... 9 more

**Comment by mahdinazmi** [comment]
@Fuzelmomin 
Did you solved it ?

**Comment by ekasetiawans** [comment]
It seems you are trying to use barcode scanner within the foreground service which is not allowed. Keep in your mind, you will never be able to use any feature that requires an UI.
