### ISSUE TITLE
Foreground service type - location

### ISSUE THREAD

**Issue by incloudss** [ekasetiawans/flutter_background_service#156]
Hi,

As per [documentation](https://developer.android.com/training/location/permissions), i would like to set foreground service type to 'location' in android manifest. I guess i should fork the project myself and reference package by path, but doing it that way:
![image](https://user-images.githubusercontent.com/78504503/169396726-6fb884f8-86c9-49c5-b1e5-f5eb8f497433.png) causes the build to fail with errors:
![image](https://user-images.githubusercontent.com/78504503/169396827-999557db-63a5-4b52-81f6-5f01157684e4.png)

Could you help me, please?

**Comment by incloudss** [comment]
With dependencies_overrides it builts, but i am not sure it it actually works, because the change in .yaml may be hard to catch. 
![image](https://user-images.githubusercontent.com/78504503/169398973-b5281419-973a-4dcd-b7a5-ed55f1c33c55.png)

Do you think its ok?

**Comment by ekasetiawans** [comment]
its okay, you might override the platform you want to customize as like you do as long it doesn't conflict with another packages in dependencies.

**Comment by ekasetiawans** [comment]
if you only need override the service type in AndroidManifest.xml, you can only just add these lines into your AndroidManifest.xml inside your project.

```xml
<application
...
          <service 
            android:enabled="true"
            android:exported="true"
            android:name="id.flutter.flutter_background_service.BackgroundService"
            android:foregroundServiceType="location"
            />
</application>
```

The android build system should override it automatically.

**Comment by incloudss** [comment]
Thank you very much for help, really appreciate it.
