### ISSUE TITLE
SwiftFlutterBackgroundServicePlugin.swift:42:36: error: value of optional type 'Dictionary<String, Any>?'

### ISSUE THREAD

**Issue by bradolh** [ekasetiawans/flutter_background_service#16]
SwiftFlutterBackgroundServicePlugin.swift:42:36: error: value of optional type 'Dictionary<String, Any>?' must be unwrapped to refer to member 'subscript' of wrapped base type 'Dictionary<String, Any>'
                let callbackHandleID = args["handle"] as? NSNumber

This happen when building for iOS

**Comment by ekasetiawans** [comment]
fixed in `0.0.1+19`
