### ISSUE TITLE
setAutoStartOnBootMode function did not call any invoke

### ISSUE THREAD

**Issue by sanjidbillah** [ekasetiawans/flutter_background_service#160]
Why this function is empty?
is this a mistake or merged with auto start?

https://github.com/ekasetiawans/flutter_background_service/blob/a5f72417f3b3bba8410acb9f5814b9a18f4fbcb6/packages/flutter_background_service_android/lib/flutter_background_service_android.dart#L81

**Comment by ekasetiawans** [comment]
hi @sanjidbillah i can confirm that was a mistake, i'll fix it soon.

**Comment by sanjidbillah** [comment]
@ekasetiawans  you didn't pass any default value.
 If i want to pass any value in `setAutoStartOnBootMode` function how can i do it?

https://github.com/ekasetiawans/flutter_background_service/blob/1c1b4f2c14d4b1680f880f999d7b0877185217ee/packages/flutter_background_service_android/lib/flutter_background_service_android.dart#L182-L184
