### ISSUE TITLE
How to solve frequent awakes warning in samsung phones?

### ISSUE THREAD

**Issue by TimeLord2010** [ekasetiawans/flutter_background_service#162]
There is this message that pop ups from time to time in my phone that says "Frequent awakes".
Users may not like it and the worst is that the OS puts the app to sleep (which means no or very few background processing time).
The user could cancel this, but still a annoyance.

I noticed that "onBackground" function accepts FutureOr<bool>. What does it mean to return true or false?

**Comment by ekasetiawans** [comment]
@TimeLord2010 have you tried to update the flutter_background_service to the latest version. There is a fix to release wake lock in android.

**Comment by TimeLord2010** [comment]
I'm using 2.0.0.
I'll update to the latestest and give some feedback when possible.
