### ISSUE TITLE
service.stopSelf(); crash only ios application after service.StopSelf()

### ISSUE THREAD

**Issue by rupeshgohil** [ekasetiawans/flutter_background_service#164]
after calling the service.StopSelf() method getting the bellow error

`-[__NSCFString setStreamHandler:]: unrecognized selector sent to instance 0x28350bfc0
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFString setStreamHandler:]: unrecognized selector sent to instance 0x28350bfc0'
*** First throw call stack:
(0x180d750fc 0x1995b0d64 0x180e520c4 0x180d0a524 0x180d09660 0x100923584 0x100923de4 0x180d1c714 0x180d3482c 0x10a9ca928 0x103c36974 0x103c39874 0x103c3bdac 0x103c3be50 0x10aec675c 0x10a9ffa58 0x10ad8d914 0x10acb4f20 0x10acb8c84 0x180d8a318 0x180d0ecf0 0x180d094ec 0x180ce7d08 0x180cfb468 0x19c88738c 0x18369d088 0x18341b958 0x1001c832c 0x101911aa4)
libc++abi: terminating with uncaught exception of type NSException
* thread , queue = 'com.apple.main-thread', stop reason = signal SIGABRT
    frame #0: 0x00000001b8411964 libsystem_kernel.dylib`__pthread_kill + 8
libsystem_kernel.dylib`__pthread_kill:
->  0x1b8411964 <+8>:  b.lo   0x1b8411984               ; <+40>
    0x1b8411968 <+12>: pacibsp 
    0x1b841196c <+16>: stp    x29, x30, [sp, #-0x10]!
    0x1b8411970 <+20>: mov    x29, sp
Target 0: (Runner) stopped.`

have any one idea for that please help us

**Comment by ekasetiawans** [comment]
@rupeshgohil  Does this happened in example project?

**Comment by rupeshgohil** [comment]
Hello @ekasetiawans thanks for quickly replay
I have executed uploading media on firebase in background I know that big data dil with background so that it's long running operation. All operation are working fine in both background and foreground. after completed task and i doing manual stop the service that also work fine i tested but getting issue after doing manual stop service in only ios devices i seen error on Appdelegant file and every time getting same above error

I hope you understand my above issue

**Comment by ekasetiawans** [comment]
hi @rupeshgohil if you wish to execute a heavy task in a different "thread", you can using isolate instead. There are some packages at pub.dev look like `flutter_isolate` or you can use `compute()` method that flutter framework provided. The main idea for using background service is for executing long running (android) or periodic (iOS) tasks while app is in background (minimized).

**Comment by rupeshgohil** [comment]
Hi @ekasetiawans thanks I would like to update as per your feedback
