### ISSUE TITLE
FATAL EXCEPTION Context.startForegroundService() did not then call Service.startForeground()

### ISSUE THREAD

**Issue by zommerberg** [ekasetiawans/flutter_background_service#17]
I am getting a random exception from the plugin.
It is hard to reproduce but it happens very often. It happens even if I just leave the app doing nothing or if I hot reload.
Sometimes it happens, sometimes it does not. But it happens even if I don't emit any events, just browse the app.
Also crashes in production.
Here are the logs:
```
I/dset.testApp_de(17971): Thread[7,tid=17982,WaitingInMainSignalCatcherLoop,Thread*=0x7de9511000,peer=0x13bc02c8,"Signal Catcher"]: reacting to signal 3
I/dset.testApp_de(17971):
I/dset.testApp_de(17971): Wrote stack traces to tombstoned
D/AndroidRuntime(17971): Shutting down VM
E/AndroidRuntime(17971): FATAL EXCEPTION: main
E/AndroidRuntime(17971): Process: com.pump.testApp_dev, PID: 17971
E/AndroidRuntime(17971): android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{e5c4382 u0 com.pump.testApp_dev/id.flutter.flutter_background_service.BackgroundService}
E/AndroidRuntime(17971): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1976)
E/AndroidRuntime(17971): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(17971): 	at android.os.Looper.loop(Looper.java:224)
E/AndroidRuntime(17971): 	at android.app.ActivityThread.main(ActivityThread.java:7590)
E/AndroidRuntime(17971): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(17971): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
E/AndroidRuntime(17971): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
I/Process (17971): Sending signal. PID: 17971 SIG: 9
Lost connection to device.
```
I am using the plugin to show a timer sometimes, but by default I need to hide the notification since no timer is running, here is my setup:

```
void timerListener() async {
  WidgetsFlutterBinding.ensureInitialized();
  final service = FlutterBackgroundService();
  //hide the notification 
  service.setForegroundMode(false);
}
```
No need to specify other details of the implementation since the bug happens even if I don't use the timer / emit any events.

**Comment by ekasetiawans** [comment]
hi @zommerberg, try to initialize background service without foreground mode.
`FlutterBackgroundService.initialize(onStart, foreground: false);`

**Comment by zommerberg** [comment]
I think this actually fixes it. Thanks. I will re-open it again if I encounter it again.

**Comment by HitendraRathod10** [comment]
I also getting same issue. can u help me @zommerberg ?
But i used latest version of plug-in So i m confused in 
How to initialize background service without foreground mode??
In my case i m not able to do
FlutterBackgroundService.initialize(onStart, foreground: false);
this.
Because of latest version (May be !)

**Comment by Musta-Pollo** [comment]
Worked for me! Thanks!
