### ISSUE TITLE
After a certain time on iOS, the app stops working in the background.

### ISSUE THREAD

**Issue by ibrahimcss** [ekasetiawans/flutter_background_service#179]
hi i have a function, this function send message to server background,but after a certain time it stops working in the background

**Comment by asashour** [comment]
Next week I plan to test iOS, but on Android so far:

- The service triggers an event every 30 minutes.
- The service stops triggering when the phone is in stand-by/sleep, but works again when the mobile is active.

Providing more details from your side, could help others reproduce the issue or provide hints.

**Comment by ekasetiawans** [comment]
on ios, we use background_fetch or BGTaskScheduler. So, you can look for documentation information and its limitations.

**Comment by ekasetiawans** [comment]
@udiedrichsen iOS doesn't have long running background services like on Android.
