### ISSUE TITLE
slow running of the service

### ISSUE THREAD

**Issue by dmrcierhn** [ekasetiawans/flutter_background_service#18]
When service.sendData and service.setNotificationInfo are used at the same time, my time counter runs slowly. how can i fix this? Thank you

**Comment by ekasetiawans** [comment]
hi @dmrcierhn can you elaborate more?

**Comment by dmrcierhn** [comment]
Of course, I'll share the code I mentioned with you.

service.sendData(
          {"sayac": "${counter}"},
        );
service.setNotificationInfo(
  title: "Arka plan",
  content: "Sayaç ${StopWatchTimer.getDisplayTime(counter)}",
 );

When I use it this way, the text I show in the text widget and the text I show in the notification progress slowly.

and i see this message on the console screen
"Slow Looper main: doFrame is 353ms late because of 1 msg"

**Comment by ekasetiawans** [comment]
how long do you use for each update?

**Comment by dmrcierhn** [comment]
I'm actually using a stopwatch and running these codes within the listening method.
_stopWatchTimer.rawTime.listen((value) {
        counter = _stopWatchTimer.rawTime.value;
        service.sendData(
          {"sayac": "${counter}"},
        );
        service.setNotificationInfo(
          title: "Arka plan",
          content: "Sayaç ${StopWatchTimer.getDisplayTime(counter)}",
        );
      });

like this

**Comment by ekasetiawans** [comment]
I mean, how long does it take for the command inside the listen method to execute? is it under 1 second?

**Comment by dmrcierhn** [comment]
I guess so because it counts with milliseconds

**Comment by ekasetiawans** [comment]
looks like you have to manage further, especially for notification updates. because the command is related to the notification system on android. My advice is to update more than or equal to 1 second.

**Comment by dmrcierhn** [comment]
I guess I need a separate notification management

**Comment by dmrcierhn** [comment]
So how can I cancel the notification in the package?

**Comment by ekasetiawans** [comment]
notification is required when you run service with foreground mode enabled, to run service without notification, just set foreground mode to false when you initialize it.

**Comment by dmrcierhn** [comment]
When I turn it off and on again, I see that the service stops

**Comment by ekasetiawans** [comment]
can you provide the stacktrace?
