### ISSUE TITLE
Set notification channel name in Android

### ISSUE THREAD

**Issue by joonolee** [ekasetiawans/flutter_background_service#180]
1. Currently, the notification channel name is fixed as "Background Service".
How about making it possible to set it as notificationChannelName in AndroidConfiguration ?

2. If isForegroundMode=false in AndroidConfiguration, it seems there is no need to create notificationChannel.
How about modifying createNotificationChannel() to be called only when isForegroundMode=true ?

**Comment by ShekharEnvato** [comment]
Any chance that we can update the default notification attributes

**Comment by ekasetiawans** [comment]
Start from version 2.2.0, you can change the notification channel id, so you can make your own notification channel using external plugin like flutter_local_notification. Keep in your mind, you have to create the notification channel before you call the `configure()` method.

**Comment by ShekharEnvato** [comment]
> Start from version 2.2.0, you can change the notification channel id, so you can make your own notification channel using external plugin like flutter_local_notification. Keep in your mind, you have to create the notification channel before you call the `configure()` method.

can you update the example in read me section as well for this change?

**Comment by ekasetiawans** [comment]
> > Start from version 2.2.0, you can change the notification channel id, so you can make your own notification channel using external plugin like flutter_local_notification. Keep in your mind, you have to create the notification channel before you call the `configure()` method.
> 
> can you update the example in read me section as well for this change?

My appologies, I don't have enough time for now to update the example. But, you can follow the flutterfire documentation to create a notification channel using flutter_local_notifications plugin, you can find it at Notification Channel section here https://firebase.flutter.dev/docs/messaging/notifications
