### ISSUE TITLE
Screen light always on

### ISSUE THREAD

**Issue by GozziCode** [ekasetiawans/flutter_background_service#181]
When the background service starts or if am in the app, the phone screen light doesn't go off except if I lock the phone with the power button myself

**Comment by ekasetiawans** [comment]
I just released flutter_background_service:^2.1.3 to fix this issue, please re-open this issue if the problem persists.

**Comment by GozziCode** [comment]
Alright many thanks, will do pub upgrade, please can you give example of
passing data from the main thread to the background service isolate, I
created future function that returns a Boolean, please how can I pass it,
or any resource I can make use of. I will really appreciate your response.
