### ISSUE TITLE
Stabilize android service

### ISSUE THREAD

**Issue by asashour** [ekasetiawans/flutter_background_service#185]
On using background service, every 5 minutes, to send an HTTP request to an online server, the delays are below.

<details>
<summary>delays</summary>

|Time difference|
|-----------|
0:15:46
0:09:22
0:12:45
0:07:52
0:18:06
0:10:47
0:47:18
0:44:38
0:07:54
1:47:11
1:20:40
2:26:11
0:59:57
0:06:53
0:05:00
0:08:46
0:05:00
0:05:06
0:09:23
0:05:01
0:48:57
0:06:03
0:05:00
0:35:26
0:13:02
0:04:54
0:05:00
0:16:08
0:04:50

</details>

On the other hand, on testing with this Android [repository](https://github.com/robertohuertasm/endless-service) (blog is [here](https://robertohuertas.com/2019/06/29/android_foreground_services/)) for two hours now, the service is sending every 5 minutes (while the phone is in sleep mode).

I guess the service can be enhanced to have the same behavior.

**Comment by ekasetiawans** [comment]
I just shipped version 2.2.1 with PARTIAL_WAKE_LOCK, let me know if this changes works for you.
