### ISSUE TITLE
Add option to set NotificationImportance 

### ISSUE THREAD

**Issue by razfazz** [ekasetiawans/flutter_background_service#187]
I have a use case where i need to set the NotificationImportance to NotificationImportance.HIGH. 
Would be great if you could expose that option and thank you for that great package!

**Comment by dJani97** [comment]
I think it is already exposed
![image](https://user-images.githubusercontent.com/22769564/189503610-0a09231b-0a60-4e69-8a77-36581c236e52.png)

**Comment by ekasetiawans** [comment]
@razfazz since 2.3.0 you will be able to make your own notification channel with custom importance.

**Comment by ekasetiawans** [comment]
@dJani97 that was not from this plugin.

**Comment by dJani97** [comment]
> @dJani97 that was not from this plugin.

Sorry, I see now. I was testing multiple plugins at the time :D
