### ISSUE TITLE
How to receive data from UI to background service?

### ISSUE THREAD

**Issue by arpitsharma007** [ekasetiawans/flutter_background_service#188]
I want to receive map object from UI to background service to call API? Can you please help with the code to show how to do that?

**Comment by Nightwelf** [comment]
you can use 

```Stream<Map<String, dynamic>?> stream = FlutterBackgroundService().on('myEventFromBGService').asBroadcastStream();```

in your bloc logic and in bloc you can use

```
on<MyBlocEvent>(
      (event, emiter) async {
        await emiter.forEach<Map<String, dynamic>?>(
          stream,
          onData: (Map<String, dynamic>? data) {
            try {
              /// some logic
            } catch (e) {
              print(e);
            }
          },
        );
      },
      transformer: sequential(),
    );
```

in service you use

```FlutterBackgroundService().invoke('myEventFromBGService', data.toJson());```
