### ISSUE TITLE
isServiceRunning is not implemented for iOS

### ISSUE THREAD

**Issue by agent3bood** [ekasetiawans/flutter_background_service#19]
Hi

`isServiceRunning` is not implemented for iOS
this make `sendData` from UI to service not working.

This line of code does not return any results

https://github.com/ekasetiawans/flutter_background_service/blob/3d1b34a9d5a674cfaa0ed86de40a3a8a91591141/lib/flutter_background_service.dart#L105

**Comment by ekasetiawans** [comment]
the fix already landed in `flutter_background_service: ^0.0.1+20`
