### ISSUE TITLE
Is there any way to open specific app screen from this background service, when app is closed?

### ISSUE THREAD

**Issue by fahmidul** [ekasetiawans/flutter_background_service#191]
I want to open a screen without clicking on the notification content when the fcm push notification is received. Is there any way to achieve this behavior with this plugin?

**Comment by ekasetiawans** [comment]
Since 2.3.0 you can create a custom notification, so you could be able to handle your own notification click. If you still facing this issue, feel free to leave a comment and I will reopen it.
