### ISSUE TITLE
Add disable/enable notification functionality

### ISSUE THREAD

**Issue by devmuaz** [ekasetiawans/flutter_background_service#196]
Hi, It would be better if this package contains capability of disabling/enabling the notification, since not in all cases the notification is required!

**Comment by ekasetiawans** [comment]
@devmuaz notification is required by android foreground service, if you ran the service as background service then the notification is not required anymore. But, you have to deal with background service limitation from Android Oreo and later.

**Comment by ekasetiawans** [comment]
FYI, some android device manufacturer has build their own custom android OS like MIUI by Xiaomi with additional custom security app that must be grant your app for autostart and background lock manually.
