### ISSUE TITLE
abbility to add buttons to foreground notification.

### ISSUE THREAD

**Issue by Mrbluesky-ai** [ekasetiawans/flutter_background_service#197]
hi, i use this plugin for my app and it works great! but i miss the ability to add buttons to the foreground notification.

**Comment by AbodiSadiqGitHub** [comment]
I have the same Inquiry.

**Comment by ekasetiawans** [comment]
It's not on my plan with this plugin. But, I think I can add a feature to customize the notification id, so we can use another plugin like local notification to create a custom notification with that id.

**Comment by ekasetiawans** [comment]
I just realised that we can update the notification with custom notification that provided by another notification plugin like flutter_local_notifications. But, currently we cannot change the notification id used by foreground service (I have a plan to expose it in future). For now until the plan is released, you can use a static notification id, the value is 99778

**Comment by ekasetiawans** [comment]
I just landed 2.3.x, please read the example for creating custom notification. If you still have an issue, feel free to leave a comment, I will reopen it.
