### ISSUE TITLE
Stop working in the background when you close the app - iOS

### ISSUE THREAD

**Issue by Ignaciomanchu1998** [ekasetiawans/flutter_background_service#198]
I have an app that counts steps. I use this package to run the pedometer method for counting steps but when I close the app, the running process on iOS dies.

Any solution?

**Comment by ekasetiawans** [comment]
If you are using location (gps) you should use background location. iOS doesn't have any background service feature like Android, it's OS level limitation, so we can't achieve that.

**Comment by gairick-saha** [comment]
https://github.com/fluttercommunity/flutter_workmanager/blob/main/IOS_SETUP.md

This information might help you

**Comment by ekasetiawans** [comment]
@gairick-saha job scheduller works like background fetch on ios and android alarm manager, it's executed periodically not a long running service.

**Comment by ekasetiawans** [comment]
@gairick-saha afaik, ios will execute a task in job scheduller in every about 15-20 minutes once and only about 20-30 seconds for each tasks must be completed. You can read the apple documentation about background fetch to make it works.

**Comment by gairick-saha** [comment]
> @gairick-saha afaik, ios will execute a task in job scheduller in every about 15-20 minutes once and only about 20-30 seconds for each tasks must be completed. You can read the apple documentation about background fetch to make it works.

Great! Thanks for the knowledge ❤️
