### ISSUE TITLE
Debug mode work fine but release mode not working

### ISSUE THREAD

**Issue by mohammadhassan1497** [ekasetiawans/flutter_background_service#202]
My app is in production and work fine but now is down without changing any code, and come back to my code running code in debug mode works fine but in release mode not working.

I used
flutter_background_service: ^2.1.3
flutter_background_service_android: ^2.0.3

**show error in releases mode**
I/flutter ( 1941): main
E/flutter ( 1941): [ERROR:flutter/shell/common/shell.cc(93)] Dart Error: Dart_LookupLibrary: library 'package:flutter_background_service_android/flutter_background_servi
ce_android.dart' not found.
E/flutter ( 1941): [ERROR:flutter/runtime/dart_isolate.cc(669)] Could not resolve main entrypoint function.
E/flutter ( 1941): [ERROR:flutter/runtime/dart_isolate.cc(167)] Could not run the run main Dart entrypoint.
E/flutter ( 1941): [ERROR:flutter/runtime/runtime_controller.cc(385)] Could not create root isolate.
E/flutter ( 1941): [ERROR:flutter/shell/common/shell.cc(604)] Could not launch engine with configuration.

**Comment by ekasetiawans** [comment]
could you provider a flutter doctor output?

**Comment by mohammadhassan1497** [comment]
[✓] Flutter (Channel stable, 3.3.1, on macOS 12.5.1 21G83 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.71.0)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!

**Comment by ekasetiawans** [comment]
I just updated flutter_background_service 2.2.0, let me know if this solves your problem.

**Comment by mohammadhassan1497** [comment]
Now work fine in release mode thank you bro

**Comment by ekasetiawans** [comment]
> Now work fine in release mode thank you bro

I'm very happy to know that

**Comment by VladlenRnd** [comment]
I still have this problem

I used
flutter_background_service: ^2.3.5

[√] Flutter (Channel stable, 3.3.2, on Microsoft Windows [Version 10.0.19044.2006], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.18)
[√] Android Studio (version 2021.2)
[√] VS Code (version 1.71.2)
[√] Connected device (4 available)
[√] HTTP Host Availability

**Comment by iamshivkumar** [comment]
@ekasetiawans I am facing the same issue, it works only on debug mode. 
flutter_background_service: ^2.3.5

[✓] Flutter (Channel stable, 3.3.1, on macOS 12.5.1 21G83 darwin-arm, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.71.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

**Comment by MoeezChohan1089** [comment]
hy sir,
Hope you are doing well i am using this pluggin but i am facing same problem that
in debug mode working perfect but in release mode not work it is showing error: 

_runMain.<anonymous closure> (dart:ui/hooks.dart:129)
E/flutter ( 9887): #8      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297)
E/flutter ( 9887): #9      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192)
E/flutter ( 9887): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: NoSuchMethodError: No top-level
getter 'onStart1' declared.
E/flutter ( 9887): Receiver: top-level
E/flutter ( 9887): Tried calling: onStart1
E/flutter ( 9887): #0      NoSuchMethodError._throwNew (dart:core-patch/errors_patch.dart:225)
E/flutter ( 9887): #1      FfiTrampoline___getCallbackFromHandle$Method$FfiNative$Ptr (dart:ffi)
E/flutter ( 9887): #2      _getCallbackFromHandle (dart:ui/natives.dart:141)
E/flutter ( 9887): #3      PluginUtilities.getCallbackFromHandle.<anonymous closure> (dart:ui/plugins.dart:81)
E/flutter ( 9887): #4      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:535)
E/flutter ( 9887): #5      PluginUtilities.getCallbackFromHandle (dart:ui/plugins.dart:80)
E/flutter ( 9887): #6      entrypoint (package:flutter_background_service_android/flutter_background_service_android.dart:1
6)
E/flutter ( 9887): #7      _runMain.<anonymous closure> (dart:ui/hooks.dart:129)
E/flutter ( 9887): #8      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297)
E/flutter ( 9887): #9      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192)


flutter_background_service: ^2.2.2

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.7.12, on Microsoft Windows [Version 10.0.19045.3086], locale en-PK)
[√] Windows Version (Installed version of Windows is version 10 or higher)


how to solve this issue please tell me

**Comment by himanshu447** [comment]
@mohammadhassan1497 what did you do? for running in release mode
