### ISSUE TITLE
Error: lambda expressions are not supported in -source 7

### ISSUE THREAD

**Issue by alfaakhri** [ekasetiawans/flutter_background_service#203]
I'm using package version 2.3.4 and found error in my project when running the project

/Users/gitsindonesia/Documents/development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_background_service_android-2.3.1/android/src/main/java/id/flutter/flutter_background_service/BackgroundService.java:303: error: lambda expressions are not supported in -source 7
                mainHandler.post(() -> {
                                    ^
  (use -source 8 or higher to enable lambda expressions)
/Users/gitsindonesia/Documents/development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_background_service_android-2.3.1/android/src/main/java/id/flutter/flutter_background_service/FlutterBackgroundServicePlugin.java:204: error: lambda expressions are not supported in -source 7
    mainHandler.post(() -> {
                        ^

  (use -source 8 or higher to enable lambda expressions)
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_background_service_android:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

<img width="973" alt="image" src="https://user-images.githubusercontent.com/28076815/190372459-3b1296ab-3c7e-4559-b36d-654e7df3de19.png">

**Comment by icodelifee** [comment]
Same here

**Comment by ekasetiawans** [comment]
This issue is raised same as #204 , you can try this solution https://github.com/ekasetiawans/flutter_background_service/issues/204#issuecomment-1248198172
