### ISSUE TITLE
local variable data is accessed from within inner class; needs to be declared final

### ISSUE THREAD

**Issue by MarsTheMan** [ekasetiawans/flutter_background_service#204]
C:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_background_service_android-2.3.2\android\src\main\java\id\flutter\flutter_background_service\BackgroundService.java:302: error: local variable data is accessed from within inner class; needs to be declared final
                        methodChannel.invokeMethod("onReceiveData", data);

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.3.0, on Microsoft Windows [Version 10.0.22000.978], locale el-GR)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Enterprise 2022 17.3.2)
[√] Android Studio (version 2021.2)
[√] VS Code (version 1.71.1)
[√] Connected device (4 available)
[√] HTTP Host Availability

**Comment by ekasetiawans** [comment]
hi @MarsTheMan, i think your project is using old version of java. You can update your java compatibility to Java 1.8 in android/app/build.gradle and make sure you using gradle version of 7.1.2 in android/build.gradle and also gradle distribution with version gradle-7.4-all.zip in android/gradle/wrapper/gradle-wrapper.properties

You can follow the example project.

**Comment by MohammadAliK** [comment]
@ekasetiawans 
After upgrading java compatibility 1.8 and other thing upgrade as you mentioned. But I get other error:

```
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.40 and higher.
The following dependencies do not satisfy the required version:
project ':flutter_absolute_path' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.31
```

**Comment by ekasetiawans** [comment]
> @ekasetiawans After upgrading java compatibility 1.8 and other thing upgrade as you mentioned. But I get other errors:
> 
> ```
> The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.40 and higher.
> The following dependencies do not satisfy the required version:
> project ':flutter_absolute_path' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.31
> ```
> 
> **Kotlin Version** `ext.kotlin_version = '1.6.10'`

That's not from this plugin, but flutter_absolute_path that using old version of kotlin. Currently, every a new flutter project is using 1.6.10 by default. So, you can try to contact that plugin author to update the version.

**Comment by MohammadAliK** [comment]
> > @ekasetiawans After upgrading java compatibility 1.8 and other thing upgrade as you mentioned. But I get other errors:
> > ```
> > The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.40 and higher.
> > The following dependencies do not satisfy the required version:
> > project ':flutter_absolute_path' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.31
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **Kotlin Version** `ext.kotlin_version = '1.6.10'`
> 
> That's not from this plugin, but flutter_absolute_path that using old version of kotlin. Currently, every a new flutter project is using 1.6.10 by default. So, you can try to contact that plugin author to update the version.

Yes, I resolve this issue by removing that plugin.
