### ISSUE TITLE
[ERROR:flutter/shell/common/shell.cc(93)] Dart Error: Dart_LookupLibrary

### ISSUE THREAD

**Issue by kth7129** [ekasetiawans/flutter_background_service#207]
debug mode works fine but release mode has error

the bug is "[ERROR:flutter/shell/common/shell.cc(93)] Dart Error: Dart_LookupLibrary: library 'package:open_door/resources/static.dart' not found."

"open_door/resources/static.dart"  is where my background service is defined

anyone else having the same problem?

as a special feature, I am using the m1 mac

See below for flutter doctor -v

[✓] Flutter (Channel stable, 3.3.2, on macOS 12.6 21G115 darwin-arm, locale
    ko-KR)
    • Flutter version 3.3.2 on channel stable at
      /Users/brighten/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e3c29ec00c (35 hours ago), 2022-09-14 08:46:55 -0500
    • Engine revision a4ff2c53d8
    • Dart version 2.18.1
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version
    33.0.0-rc3)
    • Android SDK at /Users/brighten/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc3
    • Java binary at: /Volumes/SAMSUNG SSD/응용 프로그램/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A309
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Volumes/SAMSUNG SSD/응용 프로그램/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.71.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (3 available)
    • SM N950N (mobile) • ce10171a15168411047e • android-arm64  • Android 9 (API 28)
    • macOS (desktop)   • macos                • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)      • chrome               • web-javascript • Google Chrome 104.0.5112.101

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by ekasetiawans** [comment]
try to add `@pragma('vm:entry-point')` above your onStart method.
for example:

```dart
@pragma('vm:entry-point')
Future<void> onStart(ServiceInstance service) async {

}

```

**Comment by kth7129** [comment]
oh thanks this works fine.

I will close the issue
