### ISSUE TITLE
BUILD FAILED on Android Flutter v3.3.2 release.  flutter_background_service v2.3.5

### ISSUE THREAD

**Issue by VladlenRnd** [ekasetiawans/flutter_background_service#209]
`C:\Users\user\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\flutter_background_service_android-2.3.2\android\src\main\java\id\flutter\flutter_background_service\BackgroundService.java:302: error: local 
variable data is accessed from within inner class; needs to be declared final
                        methodChannel.invokeMethod("onReceiveData", data);
                                                                    ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_background_service_android:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 52s`

**Comment by ekasetiawans** [comment]
Duplicated of #204
