### ISSUE TITLE
Wrong use of version style

### ISSUE THREAD

**Issue by Fonzeca** [ekasetiawans/flutter_background_service#212]
i write my code on 2.1.3 version of this package. Works perfectly, with sharedPreferences and IsarDb. Then i taste latest version 2.3.5... and i see that not work correctly, no breakpoints too! 

`flutter_background_service: ^2.3.5`

So i try to roolback to 2.1.3 version.

`flutter_background_service: ^2.1.3`

And still errors, and no breakpoints. i faced this along 4 days, tring to fix that "new" errors. After 4 days, i realized of [this post](https://github.com/flutter/flutter/issues/22097#issuecomment-423912378) 

So my pubspec.yaml...

`flutter_background_service: <=2.1.3`

Not work either... So finally try

```
flutter_background_service: <=2.1.3
flutter_background_service_platform_interface: <=2.0.0
flutter_background_service_android: <=2.0.3
flutter_background_service_ios: <=2.1.0
```

And finally rollback was set.

I write this because other people can face this too.

**Comment by ekasetiawans** [comment]
@Fonzeca since 2.3.0, I migrate the background service to the separated android:process, it makes the background service instance has it's own memory allocation from the OS and also doesn't disturbed by UI app. But, the side effect is we can't use breakpoint because we need to attach the debugger to the new running process.

**Comment by Fonzeca** [comment]
Yeah, i understand the new features, but with this separated process, sharedPreferences and IsarDb wont work. So, that was a breaking change, that would be in 3.0.0, not in 2.3.0.

**Comment by ekasetiawans** [comment]
@Fonzeca yeah, I just realized it. I think we should revert to single process instead.

**Comment by ekasetiawans** [comment]
I'd reverted to the single process on 2.4.0.
