### ISSUE TITLE
BootReceiver not trigger if 'Restart' or 'Reboot'

### ISSUE THREAD

**Issue by sytungan** [ekasetiawans/flutter_background_service#215]
Hi, I'm using flutter_background_service 2.3.8. With Android configuration:
```dart
   androidConfiguration: AndroidConfiguration(
      onStart: onStart,
      autoStart: true,
      isForegroundMode: false,
    )
 ```
 Background service works if I turn off and on the device.
 But **not** when trying to Restart or Reboot.
 I think u should add this action to the `<intent-filter>`: 
 ```xml
 <action android:name="android.intent.action.QUICKBOOT_POWERON" /> 
 ```

**Comment by ekasetiawans** [comment]
Thank you for your information, I'll try to add it when I have enough time.

**Comment by ekasetiawans** [comment]
@sytungan I have added the action in version 2.3.9, could you try it? and please let me know if it resolve your issue.

**Comment by sytungan** [comment]
> @sytungan I have added the action in version 2.3.9, could you try it? and please let me know if it resolve your issue.

Oh, it works, thank you for your update.
