### ISSUE TITLE
Asking For background service

### ISSUE THREAD

**Issue by yeminsoe** [ekasetiawans/flutter_background_service#216]
First of all, I would like to thank you for your wonderful thinking about this package and implementing this package. 
This package help me so much in my app.

When I using it, I notice some things. Maybe it is due to my need.

My problem is like below>>

When App goes to Background, the timer did not work for me.
When app goes back to Foreground, timer worked for all the process that need to work times within the background .

SO, do i need to add/implement anything in my app?

**Comment by ekasetiawans** [comment]
Hi @yeminsoe did you read the FAQ section in README? There are some limitations when running as background service due to OS limiation since Android O and device manufacturer.

**Comment by yeminsoe** [comment]
Yes, SIR, I read it.

**Comment by ekasetiawans** [comment]
> Yes, SIR, I read it.

Great! So you need add to your app a guidance for your user to set your app follow that policy, for example in MIUI by Xiaomi, there is a security app to allow app to run automatically, disable battery optimization, etc.

**Comment by hasanm08** [comment]
> 

Should we use this package? ``` disable_battery_optimization: ^1.1.0+1```

**Comment by ekasetiawans** [comment]
@hasanm08 it's up to you to use any other packages

**Comment by hasanm08** [comment]
> 

But I have same issue on ios what should I do?

**Comment by ekasetiawans** [comment]
@hasanm08 iOS doesn't have long running background service capability like Android. Please read README for more information.

**Comment by hasanm08** [comment]
> 

My problem is for respawn service on IOS

**Comment by ekasetiawans** [comment]
@hasanm08 on iOS, this package is using background fetch feature. Take a look for the documentation about it at apple website.
