### ISSUE TITLE
Make a tutorial

### ISSUE THREAD

**Issue by Nedimko123** [ekasetiawans/flutter_background_service#223]
as you know timer.periodic stops when in background or the screen is locked, that is why I need this plugin but how do I do that??

**Comment by ekasetiawans** [comment]
Please read the FAQ and see the example project.

**Comment by Nedimko123** [comment]
I guess we'll just stay at bad documentation.

**Comment by ekasetiawans** [comment]
@Nedimko123 Yes, now you can make your own plugin with better documentation.
