### ISSUE TITLE
Not working on background for ios:::  Could not schedule app refresh: Error Domain=BGTaskSchedulerErrorDomain Code=1 "(null)"

### ISSUE THREAD

**Issue by maleksharo** [ekasetiawans/flutter_background_service#230]

**Comment by ekasetiawans** [comment]
You should add BGTaskSchedulerPermittedIdentifiers to Info.plist, see the README. Note that, BGTaskScheduler is not supported on Simulator. So, you have to test it in real devices.

**Comment by maleksharo** [comment]
I added it as the docs & tested the app on real device but it's still giving the error when set the app on the background

**Comment by ekasetiawans** [comment]
do you using the default task identifier or custom identifier?

**Comment by ekasetiawans** [comment]
as the apple documentation said https://developer.apple.com/documentation/backgroundtasks/bgtaskschedulererrorcode/bgtaskschedulererrorcodeunavailable?language=objc

The Code=1 means BGTaskSchedulerErrorCodeUnavailable, make sure you have enabled the background mode capability for your project from xcode, and re-check your signing certificate that has background modes too.
