### ISSUE TITLE
Kill Service when app is killed

### ISSUE THREAD

**Issue by TheauLep** [ekasetiawans/flutter_background_service#238]
Hey, I need to get something running in background while someone is not using the (just close the app => has not focus on it) so I use the package to do it and it works fine. But I would like to kill the process when the user wants to kill the app (close and kill). 

Is there a way to do it properly ? I was thinking about using didChangeAppLifecycleState() but not sure it works. 

Thanks in advance for help !

**Comment by TheauLep** [comment]
@MohammadAliK  I use didChangeAppLifecycleState() and kill the process when lifecycle is detached but it is not a really proper way. Hope it helps for you

**Comment by MohammadAliK** [comment]
@TheauLep Thanks for the reply. I also try this but not working :(.

**Comment by TheauLep** [comment]
U want me to share u the code I use ? @MohammadAliK

**Comment by MohammadAliK** [comment]
Yes, Please share how you handle this. @TheauLep

**Comment by TheauLep** [comment]
There it is : 
![image](https://user-images.githubusercontent.com/80095528/202802179-b098e48e-86c5-45b2-ae91-f08aeec1571b.png)

![image](https://user-images.githubusercontent.com/80095528/202802204-2006bad5-ab55-4bcc-9976-e533151af1fc.png)

**Comment by MohammadAliK** [comment]
I tried this same way :) but I want to still start service when user is going out side of the screen.
