### ISSUE TITLE
How to set `stopWithTask` on Android service?

### ISSUE THREAD

**Issue by kyle-seongwoo-jun** [ekasetiawans/flutter_background_service#240]
```
<service
    android:name="com.myapp.MyService"
    android:stopWithTask="true" />
```

I just want to stop service when application is killed by swiping from Recent app list. 

but I think there's no way with this package. Is there any way to do this? 

Thank you.

**Comment by ekasetiawans** [comment]
it was the intended behavior, the service will be attempt to respawn when the app is terminated. You can stop the service with stopSelf method from the serviceInstance.

**Comment by ekasetiawans** [comment]
if you wish only execute any task in another isolate and only when app is running. try to use flutter isolate instead.

**Comment by kyle-seongwoo-jun** [comment]
@ekasetiawans I got it, Thanks!
