### ISSUE TITLE
Flutter bloc compatibility

### ISSUE THREAD

**Issue by CaptainKant** [ekasetiawans/flutter_background_service#243]
Hello

Is there a way, in a background service, to call an event that will be handled with flutter_bloc ?

Or if you are not familiar with flutter_bloc : I need a buildContext, even dummy, how can I have it in a backgound service ?

Thx

**Comment by Djihanegh** [comment]
You can not, i faced the same problem, my solution was : Using Isar database to store what i need instead of storing items in state.

**Comment by CaptainKant** [comment]
Thx
It's not a storage problem
It's because all my app logic is implemented with bloc and event workflow
Without faking a buildContext I need to duplicate lot of code to make it accessible in background

**Comment by ekasetiawans** [comment]
No, you can't using any UI object in background.
