### ISSUE TITLE
we cannot stop service when app is relaunch after remove/stop app while service is runing 

### ISSUE THREAD

**Issue by sadaqatdev** [ekasetiawans/flutter_background_service#244]
same issue we cannot stop service when app is relaunch after remove/stop. selfStop is not working as i call it on methods
i call invoke method , but not listen by on method

@pragma('vm:entry-point')
onStartService(ServiceInstance service) async {

service.on("stopBgService").listen((event) async {
dp(msg: "Stop bg Sevice");

await service.stopSelf();

});

}

**Comment by Divit-vaghani** [comment]
Have you find fix for it. If found please share I'm stuck on this issue 🥺.

**Comment by pife00** [comment]
In my case  I build multiples timers using a floating button, activeded and desactived the service, but did not work when I close the app, then, the config

```
await service,config(
     autoStart: true,
      isForegroundMode: true,
)
```

And works for me the service always works

**Comment by RupaliChavan06** [comment]
> reinitialise

Can you share some code of your solution?

**Comment by sadaqatdev** [comment]
await bgSevice.configure(
    iosConfiguration: IosConfiguration(
      autoStart: true,
      onForeground: onStartService,
      onBackground: (e) async {
        // onStartService(e);
        return true;
      },
    ),
    androidConfiguration: AndroidConfiguration(
      onStart: onStartService,
      autoStart: true,
      autoStartOnBoot: false,
      isForegroundMode: true,

      notificationChannelId:
          notificationChannelId, // this must match with notification channel you created above.
      initialNotificationTitle: 'Booking service',
      initialNotificationContent: 'Initializing',
      foregroundServiceNotificationId: notificationId,
    ),
  );
