### ISSUE TITLE
Background service don't work on release mode - No top-level getter 'onStart' declared

### ISSUE THREAD

**Issue by TheauLep** [ekasetiawans/flutter_background_service#246]
Everything works fine on emulator on debug mode, but when we try to build the apk and use the app in release mode, I get this error :

E/flutter (17348): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: NoSuchMethodError: No top-level getter 'onStart' declared.
E/flutter (17348): Receiver: top-level
E/flutter (17348): Tried calling: onStart
E/flutter (17348): #0      NoSuchMethodError._throwNew (dart:core-patch/errors_patch.dart:216)
E/flutter (17348): #1      _getCallbackFromHandle (dart:ui/natives.dart:94)
E/flutter (17348): #2      PluginUtilities.getCallbackFromHandle.<anonymous closure> (dart:ui/plugins.dart:82)
E/flutter (17348): #3      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:527)
E/flutter (17348): #4      PluginUtilities.getCallbackFromHandle (dart:ui/plugins.dart:81)
E/flutter (17348): #5      entrypoint (package:flutter_background_service_android/flutter_background_service_android.dart:16)
E/flutter (17348): #6      _runMain.<anonymous closure> (dart:ui/hooks.dart:132)
E/flutter (17348): #7      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297)
E/flutter (17348): #8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192)
E/flutter (17348): 

Can you please help me ? my code for the background service is done like this : 

Future<void> initializeService() async {
  final service = FlutterBackgroundService();
  await service.configure(
    androidConfiguration: AndroidConfiguration(
      // this will be executed when app is in foreground or background in separated isolate
      onStart: onStart,
      autoStartOnBoot: true,
      // auto start service
      autoStart: true,
      isForegroundMode: true,
      initialNotificationTitle: 'GetHelp',
      initialNotificationContent: "Détection de votre porte-clé",
    ),
    iosConfiguration: IosConfiguration(
      // auto start service
      autoStart: true,

      // this will be executed when app is in foreground in separated isolate
      onForeground: onStart,

      // you have to enable background fetch capability on xcode project
      onBackground: onIosBackground,
    ),
  );
  service.startService();
}

void onStart(ServiceInstance service) async {
  // Only available for flutter 3.0.0 and later
  DartPluginRegistrant.ensureInitialized();

  String str = '';

  DateTime pb = DateTime.now();

  int count = 0;

  if (service is AndroidServiceInstance) {
    service.setAsForegroundService();
  }

  service.on('Kill').listen((event) {
    service.stopSelf();
  });
  (doing smthg ...) 
}
So the method onStart is well created ...

**Comment by TheauLep** [comment]
to everyone with the same issue, it has been solved in the last version : flutter_background_service 2.4.5

Don't forget to put the  @pragma('vm:entry-point') above ur onStart function which gives : 

@pragma('vm:entry-point')
void onStart(ServiceInstance service){
  ...
}

Have a nice day and don't forget that life is good :)

**Comment by himanshu447** [comment]
@TheauLep i had added @pragma but its not working in release mode
