### ISSUE TITLE
not working release mode

### ISSUE THREAD

**Issue by ozbply** [ekasetiawans/flutter_background_service#248]
E/flutter (26475): [ERROR:flutter/shell/common/shell.cc(93)] Dart Error: Dart_LookupLibrary: library 'package:telephony/telephony.dart' not found.
package:telephony/telephony.dart:1
E/flutter (26475): [ERROR:flutter/runtime/dart_isolate.cc(668)] Could not resolve main entrypoint function.
E/flutter (26475): [ERROR:flutter/runtime/dart_isolate.cc(167)] Could not run the run main Dart entrypoint.
E/flutter (26475): [ERROR:flutter/runtime/runtime_controller.cc(385)] Could not create root isolate.
E/flutter (26475): [ERROR:flutter/shell/common/shell.cc(604)] Could not launch engine with configuration.

**Comment by ekasetiawans** [comment]
@ozbply 'package:telephony/telephony.dart' not found. you can read it! that's coming from telephony package.
