### ISSUE TITLE
isServiceRunning

### ISSUE THREAD

**Issue by dmrcierhn** [ekasetiawans/flutter_background_service#25]
isServiceRunning returns true even though the service is not running. How can i fix this ? Thank you!

**Comment by tranice** [comment]
I met the same problem. sometime when restart app , we need to know whether service is running or not ,if running, then to load resources.

**Comment by ekasetiawans** [comment]
The service will continue running until you call stopService () from inside the method you used when initializing the service.

**Comment by tranice** [comment]
in fact ,sometime we didn't start bg service when app was starting such as geo location, so when app is starting we need to know whether  the bg service is running or not , if running ,we need to load some existing resource .  existing functions are excellent ,so it will be great that  add support to check bg service running status .

**Comment by ekasetiawans** [comment]
@tranice I'm not sure you understand what you want. You can't see whether the background service is running or not without the UI. So, if you want to make sure that the service is running, you can simply create a notification. However, if you want to get that status from the UI, you can use isServiceRunning from the UI. You can't use isServiceRunning from within the service itself, because if you do, it means the service is running.

**Comment by ekasetiawans** [comment]
```
void main(){
...
FlutterBackgroundService.initialize(onStart);
...
}

void onStart(){
// everytime commands executed inside this method, its mean the service is running.
}
```

**Comment by PilotJinix** [comment]
emm excuseme
i want to ask something to you

Why i run this flutter service then i try to close my app and open again, but my app cant open? in my display just there are white blank page. how to resolved this issue

**Comment by Surya-ufours** [comment]
Hi @PilotJinix, I am facing the same problem let me know you resolve this issue.

**Comment by ekasetiawans** [comment]
@PilotJinix @Surya-ufours could you provide the flutter doctor output?

**Comment by Surya-ufours** [comment]
Hi @ekasetiawans,
I am using your example app, it's working fine in close app and open again scenario.

This is my flutter doctor output 
```
[✓] Flutter (Channel master, 1.26.0-2.0.pre.14, on Linux, locale en_IN)
    • Flutter version 1.26.0-2.0.pre.14 at /home/ufours14/flutter
    • Framework revision f37969638d (3 months ago), 2020-12-14 22:18:03 -0500
    • Engine revision 1749dbcc1b
    • Dart version 2.12.0 (build 2.12.0-150.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/ufours14/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /home/ufours14/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio
    • Android Studio at /home/ufours14/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (2 available)
    • RMX1911 (mobile) • fe59ac8b • android-arm64  • Android 10 (API 29)
    • Chrome (web)     • chrome   • web-javascript • Google Chrome 88.0.4324.182
```

**Comment by Surya-ufours** [comment]
@PilotJinix @ekasetiawans, I think its working fine in flutter run --release (release build)

**Comment by ekasetiawans** [comment]
@PilotJinix @Surya-ufours I cant reproduce the issue on my machine. I use stable channel (2.0.1). I got an exception, but the display is still working. I have fill an issue to flutter repository https://github.com/flutter/flutter/issues/77680.
