### ISSUE TITLE
The notification does not work for the SM-A710F model phone.

### ISSUE THREAD

**Issue by hesty** [ekasetiawans/flutter_background_service#26]
I use SM-A710F model phone. Notification  does not work this model but works for other models.

**Comment by yakupbaser** [comment]
i tryed on redmi note4.x and i activated the foregroundservice. the notification does not work. But my background function works like a charm. So is it working with foregroundservice or background service?

**Comment by ekasetiawans** [comment]
@yakupbaser have you tried to uninstall and reinstall the app? FYI, only foreground service needs a notification.

**Comment by yakupbaser** [comment]
i uninstalled and installed again. the example is working very well but there is no notification despite i set foregroundservice is true. I guess it works with backgroundservice on some devices

**Comment by ekasetiawans** [comment]
@yakupbaser thank you for the information you provide. unfortunately I don't have that device for debugging. I will leave this issue open until I find the cause.

**Comment by yakupbaser** [comment]
I noticed something. When I use the package below, the notification appears on Redmi and Samsung devices and the service works fine. You can examine the codes and maybe update your package.

https://github.com/SayWut/flutter_foreground_service_plugin

**Comment by ekasetiawans** [comment]
hi @yakupbaser , I have updated the notification channel importance to DEFAULT instead of LOW.
Could you try it? 
Use this git repository in your pubspec.yaml because I don't updated to the pub.dev yet. Thanks

**Comment by yakupbaser** [comment]
Hi @ekasetiawans , The notification appears on the emulator. No notification appears on my phone(Redmi note 4.x). there must be another reason, not channel importance. :(

**Comment by ekasetiawans** [comment]
@yakupbaser I removed the android version check, could you try again?

**Comment by yakupbaser** [comment]
i confirm that. It works on Android 7.1.1 emulator and my redmi note 4.x. with notification. thank you this is awesome. You can update pub.dev.

**Comment by ekasetiawans** [comment]
thanks @yakupbaser
