### ISSUE TITLE
AndroidServiceInstance and isForegroundService() doesn't exist

### ISSUE THREAD

**Issue by ChampiMagic** [ekasetiawans/flutter_background_service#260]
I'am trying to build the example proyect that its upload in dart packages page but I get this error

![Captura de pantalla 2022-12-08 173103](https://user-images.githubusercontent.com/97173716/206561376-1bf7075c-7c74-4a50-9cd5-6415bd9f75e5.png)

I looked for the AndroidServiceInstance class and the isForegroundService method, but I did not find them.

**Comment by Ahsan444** [comment]
add this 
import 'package:flutter_background_service_android/flutter_background_service_android.dart';
