### ISSUE TITLE
Get the global context while background service is running

### ISSUE THREAD

**Issue by bahman2000** [ekasetiawans/flutter_background_service#268]
I'm trying to display an alert dialog inside background service when data is received through a WebSocket (when app is running in the foreground). I know background service ran in isolated process and i can't share reference.

How to get the global context and pass this context to below method?

`showDialog(
      context: ?,
      barrierDismissible: false,
      builder: (BuildContext context) {
        return alert;
      },
    );`

**Comment by ekasetiawans** [comment]
Send the data from the background to the main isolate using invoke method, then you can use context in main isolate.

**Comment by nbpatel94** [comment]
can you please explain more practical way, @ekasetiawans

**Comment by bahman2000** [comment]
@ekasetiawans Thank you for your help.

**Comment by bahman2000** [comment]
@nbpatel94 You can see example code in this link:
[https://pub.dev/packages/flutter_background_service/example](url)

inside service:
`service.invoke(
      'update',
      {
        "current_date": DateTime.now().toIso8601String(),
        "device": device,
      },
    );`
    
    inside page:
    `StreamBuilder<Map<String, dynamic>?>(
              stream: FlutterBackgroundService().on('update'),
              builder: (context, snapshot) {
                if (!snapshot.hasData) {
                  return const Center(
                    child: CircularProgressIndicator(),
                  );
                }

                final data = snapshot.data!;
                String? device = data["device"];
                DateTime? date = DateTime.tryParse(data["current_date"]);
                return Column(
                  children: [
                    Text(device ?? 'Unknown'),
                    Text(date.toString()),
                  ],
                );
              },
            )`

**Comment by bahman2000** [comment]
@ekasetiawans How can we listen for an event from background service and run a task (Instead of create a widget) in main isolate?

For example:
1) receive a text through a web socket (inside background service)
2) save received text in external storage (inside main isolate)

**Comment by nbpatel94** [comment]
> @nbpatel94 You can see example code in this link: [https://pub.dev/packages/flutter_background_service/example](url)
> 
> inside service: ` service.invoke( 'update', { "current_date": DateTime.now().toIso8601String(), "device": device, }, );`
> 
> inside page: `StreamBuilder<Map<String, dynamic>?>( stream: FlutterBackgroundService().on('update'), builder: (context, snapshot) { if (!snapshot.hasData) { return const Center( child: CircularProgressIndicator(), ); } final data = snapshot.data!; String? device = data["device"]; DateTime? date = DateTime.tryParse(data["current_date"]); return Column( children: [ Text(device ?? 'Unknown'), Text(date.toString()), ], ); }, )`

But i don't have a web socket for listen. I have simple GET method rest api for get data for user's vehicle location that i want to get even when the app is in kill state. i mean i have to cal the api even in kill state.

Can you please tell me is it possible with this package, @ekasetiawans @bahman2000 ?

**Comment by bahman2000** [comment]
@nbpatel94  Simply, same as regular call. You can call your get method inside the background service.

**Comment by bahman2000** [comment]
@ekasetiawans Thank you for your response.
