### ISSUE TITLE
Unhandled Exception: MissingPluginException(No implementation found for method sendData on channel id.flutter/background_service_bg)

### ISSUE THREAD

**Issue by indrakumarprajapat** [ekasetiawans/flutter_background_service#27]
I am using particularly for android background service. If I followed same implementation like mention in example its working well. onStart method in main.dart.

I am receiving the error, If I want to use onStart other then in main.dart, either in a separate service or in any other widget class.
```
  Unhandled Exception: MissingPluginException(No implementation found for method sendData on channel id.flutter/background_service_bg)
 MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
```

**Comment by ekasetiawans** [comment]
this can happen if a plugin fails to register to the flutter engine.
As I know, there are several reasons why plugins fail to register to the flutter engine such as Proguard and plugins that have not been migrated to embedding v2.

**Comment by yakupbaser** [comment]
i solved this issue like this: it doesnt matter whether background plugin is registered or not. i am registered anyway. And then i can use sendData without error.

For example:
await FlutterBackgroundService.initialize(backFunc);
FlutterBackgroundService().sendData({"action": "DoSomeThings"});

**Comment by markusnissl** [comment]
I get the same error.

What I did:
I checked out the example project -> it works
I created a file background_main and moved the onStart method into this file -> it works.
I wrapped the onStart method into a class:

```
class BackgroundMain {
  void onStart() {...}
}
```

and called the init like that

```
BackgroundMain backgroundMain = new BackgroundMain();
FlutterBackgroundService.initialize(backgroundMain.onStart);
```
(so the only difference is the class I create first) -> I get the error `Unhandled Exception: MissingPluginException(No implementation found for method sendData on channel id.flutter/background_service_bg)`

Why is the plugin not found, when I wrap it in a class?

Thanks

**Comment by ekasetiawans** [comment]
@markusnissl you have to use top level method on FlutterBackgroundService.initialize, so you can't make onStart() method inside a class.

**Comment by markusnissl** [comment]
@ekasetiawans thanks for the fast answer, do you have any background material / background information why this is the case?

**Comment by ekasetiawans** [comment]
@markusnissl I dont have the links, but you can searching about executing dart callback
