### ISSUE TITLE
PlatformException(100, Failed while read arguments, Caller needs to hold android.permission.SCHEDULE_EXACT_ALARM to set exact alarms., null)

### ISSUE THREAD

**Issue by shajedulislam** [ekasetiawans/flutter_background_service#275]
please check below details to solve this issue:

flutter_background_service_android.dart in FlutterBackgroundServiceAndroid.configure at line 63 within flutter_background_service_android

Happening for Android 12. I think you need to add android.permission.SCHEDULE_EXACT_ALARM in flutter_background_service_android

**Comment by hyeonjeong-roh** [comment]
same here

**Comment by Mubashir-vp** [comment]
Having the same issue anyone found any solutions

**Comment by Mubashir-vp** [comment]
> please check below details to solve this issue:
> 
> flutter_background_service_android.dart in FlutterBackgroundServiceAndroid.configure at line 63 within flutter_background_service_android
> 
> Happening for Android 12. I think you need to add android.permission.SCHEDULE_EXACT_ALARM in flutter_background_service_android

even after putting the permission still the error occurs

**Comment by AdityaDangi68** [comment]
same here

**Comment by cameloott** [comment]
You need to add this line to AndroidManifest.xml

<uses-permission android:name="android.permission.SCHEDULE_EXACT_ALARM" />

Also you need to request "scheduleExactAlarm" from permission_handler if android version 12 or above.

This is the most efficient solution ı found.

**Comment by Wackymax** [comment]
Starting from Android 34 you can no longer add this permission to the manifest if you aren't a calendar based app and you need to request permission from the user. I would suggest that the Watchdog Receiver only activates if permission has been granted that way we can choose when to show the permission to the user in the app. Here is the Android migration guide: https://developer.android.com/about/versions/14/changes/schedule-exact-alarms

@ekasetiawans your thoughts?

**Comment by bawantha** [comment]
> `<uses-permission android:name="android.permission.SCHEDULE_EXACT_ALARM" />`

it is wired how this is not in README

**Comment by Wackymax** [comment]
What if we don't want to add the permission for our app? Would the library still work correctly? Looks like it crashes according to my testsOn 23 Sep 2023, at 12:56, Bawantha Mihiran Rajapaksha ***@***.***> wrote:﻿

<uses-permission android:name="android.permission.SCHEDULE_EXACT_ALARM" />

it is wired how this is not in README

**Comment by raav23ppp** [comment]
For me solution was first create a notification when initialize service:
```
Future<void> initializeService() async {
  final service = FlutterBackgroundService();


  const AndroidNotificationChannel channel = AndroidNotificationChannel(
    "you_can_name_it_whatever1", // id
    'MY FOREGROUND SERVICE', // title
    description:
    'This channel is used for important notifications.', // description
    importance: Importance.low, // importance must be at low or higher level
  );

  final FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin =
  FlutterLocalNotificationsPlugin();

  await flutterLocalNotificationsPlugin
      .resolvePlatformSpecificImplementation<
      AndroidFlutterLocalNotificationsPlugin>()
      ?.createNotificationChannel(channel);

  await service.configure(
    androidConfiguration: AndroidConfiguration(
      onStart: onStart,
      isForegroundMode: true,
      notificationChannelId: 'you_can_name_it_whatever1',
      initialNotificationTitle: 'Background Service Running',
      initialNotificationContent: 'Tracking location...',
      foregroundServiceNotificationId: 888,

    ),
    iosConfiguration: IosConfiguration(
      onForeground: onStart,
      onBackground: onIosBackground,
    ),
  );

  service.startService();
}
```

and after, on manifest check permission, should add:
   <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />

and 
   <service
            android:name="id.flutter.flutter_background_service.BackgroundService"
            android:permission="android.permission.FOREGROUND_SERVICE"
            android:foregroundServiceType="location"//changue for you need
            android:exported="true"
            tools:replace="android:exported" />
