### ISSUE TITLE
W/FlutterJNI(31225): Tried to send a platform message to Flutter, but FlutterJNI was detached from native C++. Could not send. Channel: plugins.flutter.io/connectivity_status. Response ID: 0

### ISSUE THREAD

**Issue by sokunsamnang** [ekasetiawans/flutter_background_service#28]
I want to my app check connectivity to process something in background. but when I killed app, it output this message:

W/FlutterJNI(31225): Tried to send a platform message to Flutter, but FlutterJNI was detached from native C++. Could not send. Channel: plugins.flutter.io/connectivity_status. Response ID: 0

How to fix this??

Thanks!!!

**Comment by ekasetiawans** [comment]
some plugins require an Activity in order to work. Flutter BackgroundService doesn't run an Activity at all, so you can't use plugins that require an Activity.
