### ISSUE TITLE
Application crashes when launching release version

### ISSUE THREAD

**Issue by AyatAliev** [ekasetiawans/flutter_background_service#286]
Help I can not understand the error, I am using the background service flutter as written in the documentation.

When I run the release version on my phone the application crashes, when I remove the service implementation everything works as it should, the interesting thing is that on the debug version everything works as it should. I run the app on flutter run --release version. The release version doesn't show any errors and I can't figure out what's wrong.

![Снимок экрана 2023-02-19 в 20 01 32](https://user-images.githubusercontent.com/26271353/219953112-8b6d449b-3cbc-4c56-9d32-ee492779d3d3.png)
![Снимок экрана 2023-02-19 в 20 01 54](https://user-images.githubusercontent.com/26271353/219953119-ae86a764-5136-4e3c-99a2-9c3a1d74fe6f.png)

**Comment by svenjacobs** [comment]
Have you tried [this](https://pub.dev/packages/flutter_background_service#service-not-running-in-release-mode)?

**Comment by AyatAliev** [comment]
@svenjacobs I figured it out, yes I had to add that thing, but I had errors before that. And I remembered that I was changing the code of this library a couple of days ago and I created the error myself, thank you very much!!!
