### ISSUE TITLE
thread does not close when service stops

### ISSUE THREAD

**Issue by yakupbaser** [ekasetiawans/flutter_background_service#29]
hi, thank you for your background service package. So Is this a bug?

https://user-images.githubusercontent.com/13915117/113737259-8c0a1100-9706-11eb-8096-9481ee34e765.mov

**Comment by ekasetiawans** [comment]
@yakupbaser yes, I can confirm it. thanks

**Comment by ekasetiawans** [comment]
will be fixed in 0.1.1
