### ISSUE TITLE
Not working after building in release mode

### ISSUE THREAD

**Issue by erderis** [ekasetiawans/flutter_background_service#292]
Everything works normally in debug mode, but the app doesn't run anything in the background after building in release mode.

**Comment by jrmanes** [comment]
could you fix that issue?, I'm facing the same... it works only in debug mode, but not in release mode in a real device...

**Comment by erderis** [comment]
> could you fix that issue?, I'm facing the same... it works only in debug mode, but not in release mode in a real device...

Yes, you should marked the onStart function as an entry point for the Dart VM by adding the @pragma('vm:entry-point') line above it.

`
@pragma('vm:entry-point')
void onStart(ServiceInstance service) async {`



When you're developing and running your app in debug mode, the Dart virtual machine (VM) is used for execution. In debug mode, the Dart VM is more permissive and allows for certain dynamic features, like hot-reloading and dynamic code execution.

However, when you build and run your Flutter app in release mode, it undergoes Ahead of Time (AOT) compilation, which compiles the Dart code into native machine code for improved performance. During this compilation process, the Dart compiler performs tree-shaking, which means it tries to eliminate unused code to make the binary more efficient.

If you have a background service or any other code that should run in both debug and release modes, but it's not directly called from the main part of your app, it's possible that the Dart compiler might remove it as part of the tree-shaking optimization in release mode. To prevent this, you mark the function with @pragma('vm:entry-point'), which tells the compiler to keep this function even if it's not directly referenced in your code.

So, if your background service is running in debug mode but not in release mode, adding the @pragma('vm:entry-point') annotation to the relevant function is a way to ensure that it gets included in the release build and continues to run as intended.

**Comment by jrmanes** [comment]
> > could you fix that issue?, I'm facing the same... it works only in debug mode, but not in release mode in a real device...
> 
> Yes, you should marked the onStart function as an entry point for the Dart VM by adding the @pragma('vm:entry-point') line above it.
> 
> ` @pragma('vm:entry-point') void onStart(ServiceInstance service) async {//your code}`
> 
> When you're developing and running your app in debug mode, the Dart virtual machine (VM) is used for execution. In debug mode, the Dart VM is more permissive and allows for certain dynamic features, like hot-reloading and dynamic code execution.
> 
> However, when you build and run your Flutter app in release mode, it undergoes Ahead of Time (AOT) compilation, which compiles the Dart code into native machine code for improved performance. During this compilation process, the Dart compiler performs tree-shaking, which means it tries to eliminate unused code to make the binary more efficient.
> 
> If you have a background service or any other code that should run in both debug and release modes, but it's not directly called from the main part of your app, it's possible that the Dart compiler might remove it as part of the tree-shaking optimization in release mode. To prevent this, you mark the function with @pragma('vm:entry-point'), which tells the compiler to keep this function even if it's not directly referenced in your code.
> 
> So, if your background service is running in debug mode but not in release mode, adding the @pragma('vm:entry-point') annotation to the relevant function is a way to ensure that it gets included in the release build and continues to run as intended.

hey @erderis 
thanks for the explanation mate, appreciate that, now I understand better the workflow.


I added the `@pragma('vm:entry-point')`, but only works in the foreground (in release mode, in debug/simulators works fine even in background), as soon as I exit from the app (not terminating it), the process stops... this works in the simulators (in debug mode), but I cannot test it if I terminate the app on it.

the code looks like:

```dart
// I added also here, just in case
@pragma('vm:entry-point')
initializeApp() async {
  final service = FlutterBackgroundService();

  await service.configure(
    androidConfiguration: AndroidConfiguration(
      onStart: onStart,
      autoStart: true,
      isForegroundMode: true,
    ),
    iosConfiguration: IosConfiguration(
      autoStart: true,
      onForeground: onStart,
      onBackground: onIosBackground,
    ),
  );
  service.startService();
}

@pragma('vm:entry-point')
Future<bool> onIosBackground(ServiceInstance serviceInstance) async {
  return true;
}

@pragma('vm:entry-point')
onStart(ServiceInstance service) async {
  DartPluginRegistrant.ensureInitialized();
  // if (service is AndroidServiceInstance) {
  //   service.on('setAsForeground').listen((event) {
  //     service.setAsForegroundService();
  //   });

  //   service.on('setAsBackground').listen((event) {
  //     service.setAsBackgroundService();
  //   });
  // }

  service.on('stopService').listen((event) {
    service.stopSelf();
  });

// I setted it to 5" to have a quick feedback
  Timer.periodic(const Duration(seconds: 5), (timer) async {
    // if (service is AndroidServiceInstance) {
    //   service.setForegroundNotificationInfo(
    //     title: "My App Service",
    //     content: "Updated at ${DateTime.now()}",
    //   );
    // }

    print('FLUTTER BACKGROUND SERVICE: ${DateTime.now()}');
    await httpReq();

    service.invoke(
      'update',
      {
        "current_date": DateTime.now().toIso8601String(),
      },
    );
  });
}
```

In the `Info.plist` I have (among others):
```
	<key>UIBackgroundModes</key>
	<array>
		<string>fetch</string>
		<string>location</string>
		<string>processing</string>
		<string>remote-notification</string>
	</array>
	<key>BGTaskSchedulerPermittedIdentifiers</key>
	<array>
		<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	</array>
```

I don't have the custom task identifier, so I consider is not needed to add it to the `ios/Runner/AppDelegate.swift`, or is it required?
```swift
SwiftFlutterBackgroundServicePlugin.taskIdentifier = "your.custom.task.identifier"
```

The capabilities in xcode looks like:

<img width="1003" alt="Screenshot 2023-09-20 at 18 05 51" src="https://github.com/ekasetiawans/flutter_background_service/assets/32740567/1f5e4f49-5508-4917-b04d-0646b541fbca">


can you see something wrong or another place that I have to add the `pragma`?

**Comment by erderis** [comment]
> > > could you fix that issue?, I'm facing the same... it works only in debug mode, but not in release mode in a real device...
> > 
> > 
> > Yes, you should marked the onStart function as an entry point for the Dart VM by adding the @pragma('vm:entry-point') line above it.
> > ` @pragma('vm:entry-point') void onStart(ServiceInstance service) async {//your code}`
> > When you're developing and running your app in debug mode, the Dart virtual machine (VM) is used for execution. In debug mode, the Dart VM is more permissive and allows for certain dynamic features, like hot-reloading and dynamic code execution.
> > However, when you build and run your Flutter app in release mode, it undergoes Ahead of Time (AOT) compilation, which compiles the Dart code into native machine code for improved performance. During this compilation process, the Dart compiler performs tree-shaking, which means it tries to eliminate unused code to make the binary more efficient.
> > If you have a background service or any other code that should run in both debug and release modes, but it's not directly called from the main part of your app, it's possible that the Dart compiler might remove it as part of the tree-shaking optimization in release mode. To prevent this, you mark the function with @pragma('vm:entry-point'), which tells the compiler to keep this function even if it's not directly referenced in your code.
> > So, if your background service is running in debug mode but not in release mode, adding the @pragma('vm:entry-point') annotation to the relevant function is a way to ensure that it gets included in the release build and continues to run as intended.
> 
> hey @erderis thanks for the explanation mate, appreciate that, now I understand better the workflow.
> 
> I added the `@pragma('vm:entry-point')`, but only works in the foreground (in release mode, in debug/simulators works fine even in background), as soon as I exit from the app (not terminating it), the process stops... this works in the simulators (in debug mode), but I cannot test it if I terminate the app on it.
> 
> the code looks like:
> 
> ```dart
> // I added also here, just in case
> @pragma('vm:entry-point')
> initializeApp() async {
>   final service = FlutterBackgroundService();
> 
>   await service.configure(
>     androidConfiguration: AndroidConfiguration(
>       onStart: onStart,
>       autoStart: true,
>       isForegroundMode: true,
>     ),
>     iosConfiguration: IosConfiguration(
>       autoStart: true,
>       onForeground: onStart,
>       onBackground: onIosBackground,
>     ),
>   );
>   service.startService();
> }
> 
> @pragma('vm:entry-point')
> Future<bool> onIosBackground(ServiceInstance serviceInstance) async {
>   return true;
> }
> 
> @pragma('vm:entry-point')
> onStart(ServiceInstance service) async {
>   DartPluginRegistrant.ensureInitialized();
>   // if (service is AndroidServiceInstance) {
>   //   service.on('setAsForeground').listen((event) {
>   //     service.setAsForegroundService();
>   //   });
> 
>   //   service.on('setAsBackground').listen((event) {
>   //     service.setAsBackgroundService();
>   //   });
>   // }
> 
>   service.on('stopService').listen((event) {
>     service.stopSelf();
>   });
> 
> // I setted it to 5" to have a quick feedback
>   Timer.periodic(const Duration(seconds: 5), (timer) async {
>     // if (service is AndroidServiceInstance) {
>     //   service.setForegroundNotificationInfo(
>     //     title: "My App Service",
>     //     content: "Updated at ${DateTime.now()}",
>     //   );
>     // }
> 
>     print('FLUTTER BACKGROUND SERVICE: ${DateTime.now()}');
>     await httpReq();
> 
>     service.invoke(
>       'update',
>       {
>         "current_date": DateTime.now().toIso8601String(),
>       },
>     );
>   });
> }
> ```
> 
> In the `Info.plist` I have (among others):
> 
> ```
> 	<key>UIBackgroundModes</key>
> 	<array>
> 		<string>fetch</string>
> 		<string>location</string>
> 		<string>processing</string>
> 		<string>remote-notification</string>
> 	</array>
> 	<key>BGTaskSchedulerPermittedIdentifiers</key>
> 	<array>
> 		<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
> 	</array>
> ```
> 
> I don't have the custom task identifier, so I consider is not needed to add it to the `ios/Runner/AppDelegate.swift`, or is it required?
> 
> ```swift
> SwiftFlutterBackgroundServicePlugin.taskIdentifier = "your.custom.task.identifier"
> ```
> 
> The capabilities in xcode looks like:
> 
> <img alt="Screenshot 2023-09-20 at 18 05 51" width="1003" src="https://user-images.githubusercontent.com/32740567/269348729-1f5e4f49-5508-4917-b04d-0646b541fbca.png">
> can you see something wrong or another place that I have to add the `pragma`?

I haven't had the opportunity to test on iOS previously. Please attempt testing on Android and ensure that you have set the isForegroundMode to false. Let's see if it operates smoothly in this configuration.

**Comment by jrmanes** [comment]
> > > > could you fix that issue?, I'm facing the same... it works only in debug mode, but not in release mode in a real device...
> > > 
> > > 
> > > Yes, you should marked the onStart function as an entry point for the Dart VM by adding the @pragma('vm:entry-point') line above it.
> > > ` @pragma('vm:entry-point') void onStart(ServiceInstance service) async {//your code}`
> > > When you're developing and running your app in debug mode, the Dart virtual machine (VM) is used for execution. In debug mode, the Dart VM is more permissive and allows for certain dynamic features, like hot-reloading and dynamic code execution.
> > > However, when you build and run your Flutter app in release mode, it undergoes Ahead of Time (AOT) compilation, which compiles the Dart code into native machine code for improved performance. During this compilation process, the Dart compiler performs tree-shaking, which means it tries to eliminate unused code to make the binary more efficient.
> > > If you have a background service or any other code that should run in both debug and release modes, but it's not directly called from the main part of your app, it's possible that the Dart compiler might remove it as part of the tree-shaking optimization in release mode. To prevent this, you mark the function with @pragma('vm:entry-point'), which tells the compiler to keep this function even if it's not directly referenced in your code.
> > > So, if your background service is running in debug mode but not in release mode, adding the @pragma('vm:entry-point') annotation to the relevant function is a way to ensure that it gets included in the release build and continues to run as intended.
> > 
> > 
> > hey @erderis thanks for the explanation mate, appreciate that, now I understand better the workflow.
> > I added the `@pragma('vm:entry-point')`, but only works in the foreground (in release mode, in debug/simulators works fine even in background), as soon as I exit from the app (not terminating it), the process stops... this works in the simulators (in debug mode), but I cannot test it if I terminate the app on it.
> > the code looks like:
> > ```dart
> > // I added also here, just in case
> > @pragma('vm:entry-point')
> > initializeApp() async {
> >   final service = FlutterBackgroundService();
> > 
> >   await service.configure(
> >     androidConfiguration: AndroidConfiguration(
> >       onStart: onStart,
> >       autoStart: true,
> >       isForegroundMode: true,
> >     ),
> >     iosConfiguration: IosConfiguration(
> >       autoStart: true,
> >       onForeground: onStart,
> >       onBackground: onIosBackground,
> >     ),
> >   );
> >   service.startService();
> > }
> > 
> > @pragma('vm:entry-point')
> > Future<bool> onIosBackground(ServiceInstance serviceInstance) async {
> >   return true;
> > }
> > 
> > @pragma('vm:entry-point')
> > onStart(ServiceInstance service) async {
> >   DartPluginRegistrant.ensureInitialized();
> >   // if (service is AndroidServiceInstance) {
> >   //   service.on('setAsForeground').listen((event) {
> >   //     service.setAsForegroundService();
> >   //   });
> > 
> >   //   service.on('setAsBackground').listen((event) {
> >   //     service.setAsBackgroundService();
> >   //   });
> >   // }
> > 
> >   service.on('stopService').listen((event) {
> >     service.stopSelf();
> >   });
> > 
> > // I setted it to 5" to have a quick feedback
> >   Timer.periodic(const Duration(seconds: 5), (timer) async {
> >     // if (service is AndroidServiceInstance) {
> >     //   service.setForegroundNotificationInfo(
> >     //     title: "My App Service",
> >     //     content: "Updated at ${DateTime.now()}",
> >     //   );
> >     // }
> > 
> >     print('FLUTTER BACKGROUND SERVICE: ${DateTime.now()}');
> >     await httpReq();
> > 
> >     service.invoke(
> >       'update',
> >       {
> >         "current_date": DateTime.now().toIso8601String(),
> >       },
> >     );
> >   });
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > In the `Info.plist` I have (among others):
> > ```
> > 	<key>UIBackgroundModes</key>
> > 	<array>
> > 		<string>fetch</string>
> > 		<string>location</string>
> > 		<string>processing</string>
> > 		<string>remote-notification</string>
> > 	</array>
> > 	<key>BGTaskSchedulerPermittedIdentifiers</key>
> > 	<array>
> > 		<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
> > 	</array>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I don't have the custom task identifier, so I consider is not needed to add it to the `ios/Runner/AppDelegate.swift`, or is it required?
> > ```swift
> > SwiftFlutterBackgroundServicePlugin.taskIdentifier = "your.custom.task.identifier"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The capabilities in xcode looks like:
> > <img alt="Screenshot 2023-09-20 at 18 05 51" width="1003" src="https://user-images.githubusercontent.com/32740567/269348729-1f5e4f49-5508-4917-b04d-0646b541fbca.png">
> > can you see something wrong or another place that I have to add the `pragma`?
> 
> I haven't had the opportunity to test on iOS previously. Please attempt testing on Android and ensure that you have set the `isForegroundMode: ` to false. Let's see if it operates smoothly in this configuration.

okay, I'll keep you posted 😉

**Comment by himanshu447** [comment]
Hello @jrmanes any luck in IOS release mode?

**Comment by ThanhQuang1410** [comment]
Any luck on this @tty47  ? I am stuck and no solution found 🥲🥲🥲

**Comment by LittleFireflies** [comment]
So, there's still no solution on this package for ios release mode?
