### ISSUE TITLE
V/BackgroundService(21048): Service already running, using existing service

### ISSUE THREAD

**Issue by AmeerSafdar** [ekasetiawans/flutter_background_service#326]
why this issue appears again and again in console?

V/BackgroundService(21048): Service already running, using existing service

**Comment by mozomig** [comment]
I think we need add check service is running in https://github.com/ekasetiawans/flutter_background_service/blob/master/packages/flutter_background_service_android/android/src/main/java/id/flutter/flutter_background_service/WatchdogReceiver.java

Like this (kotlin):
`override fun onReceive(context: Context, intent: Intent) {
        if (intent.action == ACTION_RESPAWN) {
            val config = Config(context)
            var isRunning = false
            val manager = context.getSystemService(Context.ACTIVITY_SERVICE) as am
            for (service in manager.getRunningServices(Int.MAX_VALUE)) {
                if (BackgroundService::class.java.name == service.service.className) {
                    isRunning = true
                }
            }
            if (!config.isManuallyStopped && !isRunning) {
                if (config.isForeground) {
                    ContextCompat.startForegroundService(
                        context,
                        Intent(context, BackgroundService::class.java)
                    )
                } else {
                    context.startService(Intent(context, BackgroundService::class.java))
                }
            }
        }
    }`

and then remove

` 
            if (isRunning.get() || (backgroundEngine != null && !backgroundEngine.getDartExecutor().isExecutingDart())) {
                Log.v(TAG, "Service already running, using existing service");
                return;
            }
`

in https://github.com/ekasetiawans/flutter_background_service/blob/master/packages/flutter_background_service_android/android/src/main/java/id/flutter/flutter_background_service/BackgroundService.java

**Comment by ekasetiawans** [comment]
It's only verbose log, not an error. Just to tell us that the service is running normally.
