### ISSUE TITLE
Background Service Preparing

### ISSUE THREAD

**Issue by natanvalimcardoso** [ekasetiawans/flutter_background_service#328]
I configured ios and android notifications in flutter, but in android this alert is on and in ios it works normally, and all notifications on both platforms work, what could it be?
![issue](https://github.com/ekasetiawans/flutter_background_service/assets/42617787/8384573e-3de7-49dc-a74b-652991717f2a)

**Comment by natanvalimcardoso** [comment]
> [avikorat](/avikorat)

I managed to solve it by simply removing the background code within the application: The documentation puts you to use the background but if you don't use it, you have this problem;

**Comment by bahman2000** [comment]
@natanvalimcardoso Hi, Can you explain more about how you solved the problem?

**Comment by natanvalimcardoso** [comment]
`import 'package:flutter_local_notifications/flutter_local_notifications.dart';

import '../../shared/constants/push_notification_const.dart';
import '../../shared/extensions/string_extension.dart';
import '../../shared/helpers/dynamic_navigation_help.dart';

class NotificationLocal {
  final FlutterLocalNotificationsPlugin notificationsPlugin = FlutterLocalNotificationsPlugin();

  Future<void> initialize() async {
    const AndroidInitializationSettings initializationSettingsAndroid =
        AndroidInitializationSettings('@drawable/ic_launcher_foreground');

    const DarwinInitializationSettings initializationSettingsDarwinIos =
        DarwinInitializationSettings();

    const initializationSettings = InitializationSettings(
      android: initializationSettingsAndroid,
      iOS: initializationSettingsDarwinIos,
    );

    await notificationsPlugin.initialize(
      initializationSettings,
      onDidReceiveNotificationResponse: onDidReceiveNotificationResponse,
    );
  }

  void onDidReceiveNotificationResponse(
    NotificationResponse notificationResponse,
  ) async {
    final String? payload = notificationResponse.payload;
    if (payload != null) {
      final dataMap = payload.parseStringToMap();
      final chatOrderId = dataMap[PushNotificationConst.chatOrderIdPushNotification];
      if (chatOrderId != null) {
        DynamicNavigationHelp.goToChatDelivery(payload: chatOrderId);
        return;
      }
      final campaingId = dataMap[PushNotificationConst.campaignIdNotificationKey];
      if (campaingId != null) {
        DynamicNavigationHelp.goToCoupons(payload: campaingId);
        return;
      }
    }
  }

  NotificationDetails notificationDetails() {
    return const NotificationDetails(
      iOS: DarwinNotificationDetails(
        presentAlert: false,
        presentBadge: true,
        presentSound: true,
      ),
      android: AndroidNotificationDetails(
        'channelId',
        'channelName',
        showWhen: false,
        importance: Importance.high,
        priority: Priority.high,
      ),
    );
  }

  Future showNotification({
    int id = 0,
    String? title,
    String? body,
    String? payload,
  }) async {
    return await notificationsPlugin.show(
      id,
      title,
      body,
      notificationDetails(),
      payload: payload,
    );
  }
}
`

**Comment by natanvalimcardoso** [comment]
@bahman2000
