### ISSUE TITLE
How to communicate between service and UI?

### ISSUE THREAD

**Issue by sanjay23singh** [ekasetiawans/flutter_background_service#34]
I have created a banner which shows up while the user is having a call.
My problem is using this packcage, how  can I show up that banner when the app is closed.

**Comment by ekasetiawans** [comment]
Hi @sanjay23singh closed app don’t have ui, the service runs on the background without ui

**Comment by sanjay23singh** [comment]
> Hi @sanjay23singh closed app don’t have ui, the service runs on the background without ui

How can we show that ui while receiving a call like truecaller

**Comment by X-SLAYER** [comment]
> > Hi @sanjay23singh closed app don’t have ui, the service runs on the background without ui
> 
> How can we show that ui while receiving a call like truecaller

try to use this package it's helpful u can start it from background 
[system_alert_window](https://pub.dev/packages/system_alert_window)
