### ISSUE TITLE
after use Location not working

### ISSUE THREAD

**Issue by kotoSky** [ekasetiawans/flutter_background_service#344]
Flutter version 3.7.12 and 3.10.6.
dependencies:
  flutter_bmflocation: ^3.4.1
  flutter_background_service: ^3.0.2 and 5.0.0

After use the flutter_background_service,the flutter_bmflocation location function in my app became unusable on the interface, but it can still be used in flutter_background_service.

I tried to have the service open in the background and closed in the foreground
service.startService();
service.invoke("onDataReceived", {'action' : 'stopService'}); 
A detailed error has occurred  after  
error log:
`
D/baidu_location_client(26985): baidu location connected ...

W/FlutterJNI(21180): Tried to send a platform message to Flutter, but FlutterJNI was detached from native C++. Could not send. Channel: flutter_bmflocation. Response ID: 3
`

What is the cause and is there a solution

**Comment by Sneh-Paghdal** [comment]
Hello, @kotoSky have you code for IOS?

**Comment by kotoSky** [comment]
> 您好，您是否为 IOS 编写代码？

是安卓平台上报的错误，现在还有一个新的
在我退出app重新进入后抛出异常
`E/flutter ( 3161): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method flutter_bmflocation/seriesLocation on channel flutter_bmflocation)`
