### ISSUE TITLE
Can't get recive data to UI

### ISSUE THREAD

**Issue by CaoGiaHieu-dev** [ekasetiawans/flutter_background_service#35]
Hi , im stuck in this issue when i try to receive data from native . I do as same as your example but my widget can't listen value from stream . It's have value when i log it

**Comment by ajithkgshk** [comment]
I am stuck in a similar issue. Let me know if you were able to fix it.

**Comment by bluemix** [comment]
The same here :/

**Comment by bluemix** [comment]
I checked it. It is in the README.md and in the example of this repo:

> Since the Service using Isolates, You won't be able to share reference between UI and Service. You can communicate between UI and Service using `sendData()` and `onDataReceived`.

**Comment by arpitsharma007** [comment]
How to do that? Can you please help me with the code?

**Comment by bluemix** [comment]
@arpitsharma007 check this example:
https://github.com/ekasetiawans/flutter_background_service/blob/master/packages/flutter_background_service/example/lib/main.dart
