### ISSUE TITLE
 Unhandled Exception: MissingPluginException(No implementation found for method sendData on channel id.flutter/background_service/android/method)

### ISSUE THREAD

**Issue by isaanyoha** [ekasetiawans/flutter_background_service#352]
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method sendData on channel id.flutter/background_service/android/method)
E/flutter (15846): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:308:7)

Please, how do I fix this issue above?
Things I have done:
- flutter clean
- pub get
- invaliated and restarted
- deleted and created Android emulator

I am using:
flutter_background_service: ^5.0.1
sdk: ">=2.18.0 <3.0.0"

**Comment by isaanyoha** [comment]
I found the issue. Closing this...

**Comment by EvertonMJunior** [comment]
Hey, would you care to elaborate how you solved it? I'm currently running into the same error

**Comment by Quoteme** [comment]
> I found the issue. Closing this...

![image](https://github.com/ekasetiawans/flutter_background_service/assets/6796009/7b98b3f8-7a90-42d8-be4f-b613e76b78de)

(Source: https://xkcd.com/979/)

**Comment by AvidanGC** [comment]
It showed me this error:
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method sendData on channel id.flutter/background_service/android/method)
E/flutter ( 4666): #0 MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:320:7)

What I was doing inside my onStart(..) method was calling FlutterBackgroundService().invoke(setAsForeground);
validate that do not call this method. 

I hope this helps you in some way.

**Comment by emilymarquessalum** [comment]
This might possible help someone with the same error -> 
I was using FlutterBackgroundService().invoke and it was giving me that error, however I was running that in foreground... In the app side you use FlutterBackgroundService(), but in the foreground you should use the instance of the service that is provided to you at your "onStartForeground". Changing that fixed it for me.

**Comment by ramaatamai** [comment]
@emilymarquessalum Can you give me the code example please?

**Comment by emilymarquessalum** [comment]
Hey! So, in short
You probably have, for the background service itself, a separate file, yes?

In it, you would have something like this

```dart
// You would call this in your main.dart
void startBackgroundService() {

  FlutterBackgroundService service = FlutterBackgroundService();
  service.startService();
  // ...
}


@pragma('vm:entry-point')
Future<void> onStartForeground(ServiceInstance service) async {
   // ... # What you want to run in the background
}
```

I personally have some additional things related to notifications in the startBackgroundService, but it doesnt matter. 

Everything running from onStartForeground should use that service instance. You could run into some subtle form of making this mistake of using the FlutterBackgroundService().invoke inside it without knowing...  calling that invoke would essencially mean you are trying to communicate with the background.. inside the background. Which is, obviously, a problem.

For example, I used a class in both the app and in background, and that class used FlutterBackgroundService().invoke to notify the background, among many other things.
I would say if your code is clean that is essencially impossible to happen, but sadly my code wasn't. 
So, when it ran in the app itself it worked fine, but when it ran in the background it gave that error. It took me a good while to figure it out...

Try to check where you are running the invokes in the code, to see if there is any chance of this being the problem.

**Comment by ramaatamai** [comment]
@emilymarquessalum Thank you for the reply.😊
