### ISSUE TITLE
Android 14 release mode issuse

### ISSUE THREAD

**Issue by asemanTest** [ekasetiawans/flutter_background_service#378]
Hello. Thank you for your good package
when i use flutter build apk --release i got this error 
i also added this line in AndroidManifest and build.gradle

flutter version=3.13.9
```
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE_SPECIAL_USE" />

    manifestPlaceholders['foregroundServiceType'] = 'specialUse'
```

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_background_service_android:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:C:\Users\alireza\AppData\Local\Pub\Cache\hosted\pub.dev\flutter_background_service_android-6.2.0\android\src\main\Androi
dManifest.xml:10:9-16:15: AAPT: error: 'dollar_openBracket_foregroundServiceType_closeBracket' is incompatible with attribute foreg
roundServiceType (attr) flags [camera=64, connectedDevice=16, dataSync=1, health=256, location=8, mediaPlayback=2, mediaProjection=
32, microphone=128, phoneCall=4, remoteMessaging=512, shortService=2048, specialUse=1073741824, systemExempted=1024].
```

**Comment by MostafaBastawyy** [comment]
i have he same issue

**Comment by luisfelipeas5** [comment]
Is this line on app/build.gradle?
```groovy
    manifestPlaceholders['foregroundServiceType'] = 'specialUse'
```

**Comment by Ellynnn** [comment]
I'm facing the same issue too

**Comment by lionuncle** [comment]
same issue

**Comment by luisfelipeas5** [comment]
Which is the `compileSdkVersion` and `targetSdkVersion` in the`app/build.gradle`?

**Comment by melchorlapinigjr** [comment]
Same issue here. Can't build apk in release mode.

`Doctor summary (to see all details, run flutter doctor -v): ?1  flutter doctor                                                                            2 err  44s  09:38:12 PM 
[✓] Flutter (Channel stable, 3.13.9, on macOS 14.1 23B74 darwin-arm64, locale en-PH)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.83.1)
[✓] Connected device (2 available)
[✓] Network resources

! Doctor found issues in 1 category.
`

 ext {
        compileSdkVersion   = 34 // or higher
        targetSdkVersion    = 34
        minSdkVersion       = 22 // required minimum from flutter toast
        appCompatVersion    = "1.4.2" // required minimum from flutter background geolocation
        playServicesLocationVersion = "21.0.1" // required minimum from flutter background geolocation
    }

**Comment by asemanTest** [comment]
> Which is the `compileSdkVersion` and `targetSdkVersion` in the`app/build.gradle`?

minSdkVersion 21
targetSdkVersion 34
compileSdkVersion 34

**Comment by Supertommino** [comment]
Same issue too

**Comment by SOG-web** [comment]
please am having same issue

**Comment by bahman2000** [comment]
I have the same issue. Any update would be greatly appreciated.

**Comment by Musta-Pollo** [comment]
Or downgrading:
`flutter_background_service_android: 6.0.1`

**Comment by FaizanKadodiya** [comment]
Is there any Complete Solution?

**Comment by ekasetiawans** [comment]
https://github.com/ekasetiawans/flutter_background_service/issues/383#issuecomment-1834255393
