### ISSUE TITLE
Can't change notification icon.

### ISSUE THREAD

**Issue by sabuj0338** [ekasetiawans/flutter_background_service#38]
I did same as you said. I put my app icon to drawable folder like your example but still app icon not changing.

**Comment by ekasetiawans** [comment]
try to add icons to your project like in the folders here
https://github.com/ekasetiawans/flutter_background_service/tree/master/android/src/main/res

**Comment by sabuj0338** [comment]
Maybe I got it. I have another problem. I don't want to show notification badge app icon.
![Screenshot_20210609-123149_One_UI_Home 1](https://user-images.githubusercontent.com/46751691/121306831-2104d280-c921-11eb-891d-3180509e620d.jpg)

**Comment by stephane-segning** [comment]
So for a small procedure, for anyone having the same issue, please just use Android Studio for adding the new notification and verify that the folder `drawable-anydpi-v24` is added with an `xml` file
