### ISSUE TITLE
`MissingPluginException (MissingPluginException(No implementation found for method test on channel com.myexample/test_channel))`

### ISSUE THREAD

**Issue by Quoteme** [ekasetiawans/flutter_background_service#384]
Dear Eka Setiawan Saputra and contributers,

first off, thanks a lot for your plugin! It is really helpful, and you did a great job with it!
I keep running into the following error tough:

```
MissingPluginException (MissingPluginException(No implementation found for method test on channel com.myexample/test_channel))
```

This error happens when I try to call native android/iOS-code through a `MethodChannel` in your background-thread.
I created a minimal, reproducible example (just around 20-30 lines added to your example code) here: https://github.com/Quoteme/flutter_background_service_methodchannel. This only shows the error in an iOS app, but for android it is the same.

### when does the error occur?

In this code, we call our native code from your background service, and it will fail:

```dart
@pragma('vm:entry-point')
void onStart(ServiceInstance service) async {
  // Only available for flutter 3.0.0 and later
  DartPluginRegistrant.ensureInitialized();

  // ❗️❗️❗️ IMPORTANT ❗️❗️❗️
  // here we try to call a method from our methdod-channel and we will fail
  const MethodChannel channel = MethodChannel('com.myexample/test_channel');
  try {
    var test = await channel.invokeMethod('test');
    print(test);
  } catch (e) {
    print(e);
    // -> `MissingPluginException (MissingPluginException(No implementation found for method test on channel com.myexample/test_channel))`
  }
  // ❌❌❌ END OF IMPORTANT ❌❌❌
  ```

source: https://github.com/Quoteme/flutter_background_service_methodchannel/blob/f3f434faf0c9a6c07b0c60adcfe6e57d981a0953/lib/main.dart#L96-L111

To prove that this is actually a problem which only happens inside a background service, we can also run this code on our main thread and see, that it successfully runs:

```dart
class _MyAppState extends State<MyApp> {
  void _testMethodChannel() async {
    // ❗️❗️❗️ IMPORTANT ❗️❗️❗️
    // here we try to call a method from our methdod-channel and we will NOT fail
    const MethodChannel channel = MethodChannel('com.myexample/test_channel');
    try {
      var test = await channel.invokeMethod('test');
      print(test); // -> "Hello from iOS"
    } catch (e) {
      print(e);
    }
    // ❌❌❌ END OF IMPORTANT ❌❌❌
  }

  @override
  void initState() {
    _testMethodChannel();
    super.initState();
  }
  ```

source: https://github.com/Quoteme/flutter_background_service_methodchannel/blob/f3f434faf0c9a6c07b0c60adcfe6e57d981a0953/lib/main.dart#L198-L210

### how did I set up the method-channel in the native code?

This is the complete code I used to create the method channel. It's nothing fancy, just a standard `MethodChannel`:

```swift
import Flutter
import UIKit
import flutter_background_service_ios

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  private var methodChannel: FlutterMethodChannel?

  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    SwiftFlutterBackgroundServicePlugin.taskIdentifier = "your.custom.task.identifier"
    GeneratedPluginRegistrant.register(with: self)
      guard let controller: FlutterViewController = window?.rootViewController as? FlutterViewController else {
            fatalError("Invalid rootViewController")
        }
      methodChannel = FlutterMethodChannel(
      name: "com.myexample/test_channel",
      binaryMessenger: controller.binaryMessenger)
    setupMethodChannel()
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }

    // In this function, we set up our methodchannel, such that we should be able to run
    // ```
    // const MethodChannel channel = MethodChannel('com.myexample/test_channel');
    // try {
    //   await channel.invokeMethod('test');         // -> "Hello from iOS"
    // } catch (e) {
    //   print(e);
    // }
    // ```
    // in our dart code.
    private func setupMethodChannel() {
    methodChannel?.setMethodCallHandler { (call, result) in
      switch call.method {
      case "test":
        result("Hello from iOS")
      default:
        result(FlutterMethodNotImplemented)
      }
    }
  }
}
```

https://github.com/Quoteme/flutter_background_service_methodchannel/blob/f3f434faf0c9a6c07b0c60adcfe6e57d981a0953/ios/Runner/AppDelegate.swift#L1-L45

## My question

Did I maybe miss something during the setup of your plugin?
I would be really glad, if you could help me out a little bit here and show me, how this calling a MethodChannel from your background-service is done correctly.

---

#### Possibly related issues

#290 #201

#### My flutter installation

<details>
<summary><pre>flutter version</pre></summary>
<pre>
$ flutter --version
Flutter 3.13.9 • channel stable • https://github.com/flutter/flutter.git
Framework • revision d211f42860 (3 weeks ago) • 2023-10-25 13:42:25 -0700
Engine • revision 0545f8705d
Tools • Dart 3.1.5 • DevTools 2.25.0
</pre>
</details>

**Comment by ekasetiawans** [comment]
hi @Quoteme since the background service is running on different dart isolate (FlutterEngine), it will not attached with your method channel unless you move your method channel into a new flutter plugin project.

**Comment by BigYajuu** [comment]
@ekasetiawans  So the question now for me is: If I were to build my own method/event channels and I want to keep them alive in foreground, I cannot build these channels in the native code the same as this project, but on a separate plugin project?

Then if I run the plugin project's method channel code inside of the `onStart` method it's gonna work?

Could you elaborate on the concept behind this reason?

@Quoteme Were you able to make it work?

**Comment by BigYajuu** [comment]
> @ekasetiawans So the question now for me is: If I were to build my own method/event channels and I want to keep them alive in foreground, I cannot build these channels in the native code the same as this project, but on a separate plugin project?
> 
> Then if I run the plugin project's method channel code inside of the `onStart` method it's gonna work?
> 
> Could you elaborate on the concept behind this reason?
> 
> @Quoteme Were you able to make it work?

PS: I am not using this Flutter package, but a similar one with mechanisms that resemble this one.

I read #201  - a problem somewhat similar to my usecase. And I don't get this part: 
> If you register your event channel in MainActivity, then it's only available to the main isolate that running the flutter UI.

How does building a new plugin project help this? I mean, if I migrate the method/event channels into a new plugin project, doesn't that make it more difficult for my UI to communicate with that plugin?

**Comment by ekasetiawans** [comment]
> @ekasetiawans So the question now for me is: If I were to build my own method/event channels and I want to keep them alive in foreground, I cannot build these channels in the native code the same as this project, but on a separate plugin project?
> 
> Then if I run the plugin project's method channel code inside of the `onStart` method it's gonna work?
> 
> Could you elaborate on the concept behind this reason?

@BigYajuu If you build your own method channel in your project native code, then flutter tools won’t add your method channel into FlutterPluginRegistrant class. So, it will take more step to register (attach) the method channel to a new flutter engine instance that executes onStart method.

**Comment by ekasetiawans** [comment]
> > @ekasetiawans So the question now for me is: If I were to build my own method/event channels and I want to keep them alive in foreground, I cannot build these channels in the native code the same as this project, but on a separate plugin project?
> > Then if I run the plugin project's method channel code inside of the `onStart` method it's gonna work?
> > Could you elaborate on the concept behind this reason?
> > @Quoteme Were you able to make it work?
> 
> PS: I am not using this Flutter package, but a similar one with mechanisms that resemble this one.
> 
> I read #201 - a problem somewhat similar to my usecase. And I don't get this part:
> 
> > If you register your event channel in MainActivity, then it's only available to the main isolate that running the flutter UI.
> 
> How does building a new plugin project help this? I mean, if I migrate the method/event channels into a new plugin project, doesn't that make it more difficult for my UI to communicate with that plugin?

Moving your method channel to separated flutter plugin, will make flutter tools registers your method channel into FlutterPluginRegistrant in native project when `flutter pub get` executed. So, it will be registered to every new flutter engine instances automatically.

**Comment by BigYajuu** [comment]
@ekasetiawans One more problem: I tried to use `ActivityAware` to obtain the activity information from the native's side, but it couldn't be done because ActivityAware's `onAttachedToActivity` is not being called. Is there any troubleshooting for this?

**Comment by BigYajuu** [comment]
> @ekasetiawans One more problem: I tried to use `ActivityAware` interface to obtain Android activity binding from the native's side, but it couldn't be done because ActivityAware's `onAttachedToActivity` is not being called. Is there any troubleshooting for this?

Nevermind. It seems you can't obtain the Activity via plugin because **there is no need to do that**. You can call `startService` using `context` provided by `onAttachedToEngine`.

**Comment by Quoteme** [comment]
> @ekasetiawans  So the question now for me is: If I were to build my own method/event channels and I want to keep them alive in foreground, I cannot build these channels in the native code the same as this project, but on a separate plugin project?
> 
> Then if I run the plugin project's method channel code inside of the `onStart` method it's gonna work?
> 
> Could you elaborate on the concept behind this reason?
> 
> @Quoteme Were you able to make it work?

Hi! Yes, using a separate flutter plugin which exposed all method channels worked.

**Comment by Gonn01** [comment]
> > @ekasetiawans  So the question now for me is: If I were to build my own method/event channels and I want to keep them alive in foreground, I cannot build these channels in the native code the same as this project, but on a separate plugin project?
> > Then if I run the plugin project's method channel code inside of the `onStart` method it's gonna work?
> > Could you elaborate on the concept behind this reason?
> > @Quoteme Were you able to make it work?
> 
> Hi! Yes, using a separate flutter plugin which exposed all method channels worked.

Hello, i created a flutter package and added it as a dependency to my project, also added the method im trying to call inside the MainActivity.kt of the new flutter package,(i test it by running it and work) but when im trying to call the method on my project throws Unhandled Exception: MissingPluginException(No implementation found for method getLocation on channel location_channel)
Idk what im doing wrong
