### ISSUE TITLE
Can't hide notification badge from app icon.

### ISSUE THREAD

**Issue by sabuj0338** [ekasetiawans/flutter_background_service#39]
I don't want to show notification badge app icon. Like this, I don't want to show this (1) red icon. What can I do?

Please add notification count badge hide option. How to hide notification count badge ->
https://stackoverflow.com/questions/54472497/how-can-i-hide-badge-count-number-when-startforeground

![Screenshot_20210609-123149_One_UI_Home 1](https://user-images.githubusercontent.com/46751691/121319754-5532c000-c92e-11eb-9807-537935643a39.jpg)

**Comment by jakhongirovjasurbek** [comment]
You can disable foreground mode for Android and it will disappear. But, foreground mode will be disabled as well. I suggest you fork and edit in terms of your own willings.
Hope it helps someone.
