### ISSUE TITLE
Error compiling with minimun IOS 10

### ISSUE THREAD

**Issue by wolf9113** [ekasetiawans/flutter_background_service#41]
hi...
i have this issue

Compiling for iOS 9.0, but module 'flutter_background_service' has a minimum deployment target of iOS 10.0: /Users/cesarquattro/Library/Developer/Xcode/DerivedData/Runner-eiedghkkuhmwrmhbelwprmptnqzh/Build/Products/Debug-iphonesimulator/flutter_background_service/flutter_background_service.framework/Modules/flutter_background_service.swiftmodule/x86_64-apple-ios-simulator.swiftmodule

i cant build in 9.0 because google_maps and firebase require minimum IOS 10

what can i do???

**Comment by ekasetiawans** [comment]
you have to build with minimum ios 10.
edit your ios/Podfile
