### ISSUE TITLE
`question` How to Remove the Notification, That may always occur?

### ISSUE THREAD

**Issue by madd-project** [ekasetiawans/flutter_background_service#42]
Hey @ekasetiawans I Loved your ❤️ towards the People who opens the issue inside the `flutter_background_service` 
like how you assisted @arpitjacob in this issue #3. 

Thanks up for the Love for the Opensource, and understanding how weird is using the Work manager plugin is.
Work manager is just don't work up properly with the Hive Db or local Storages, And with this Package, I think I could Create Limitless Things.. Thanks Up @ekasetiawans for understanding the need of this Developer. 💡 

**Question**
Do we have a way, to remove the disturbing notification that comes to the top, which just doesn't remove by itself.

**Comment by ekasetiawans** [comment]
Hi @madd-project , notification is required by foreground service, to remove the notification you can run the service as background service.

Here is the example:

```
FlutterBackgroundService.initialize(yourStartMethod, foreground: false);
```

**Comment by madd-project** [comment]
That is awesome, 
May I also Know that, will the `flutter_background_services` with work like this,

**main.dart:**
```
void main(){
   WidgetsFlutterBinding.ensureInitialized();
   FlutterBackgroundService.initialize(resetToodoleeMidNight, foreground: true);
   runApp(MyApp());
}
```
**function.dart**
```
resetToodoleeMidNight() {
  WidgetsFlutterBinding.ensureInitialized();
  final service = FlutterBackgroundService();
  service.onDataReceived.listen((event) {
    if (event["action"] == "startTimer") {
      cron.schedule(Schedule.parse('*/1 * * * *'), () async {
        todoBox.clear();
        completedBox.clear();
        deleteQuotes();
        boredBox.clear();
        totalTodoCount.value = 10;

        print("everything is deleted");
      });
    }
    if (event["action"] == "stopTimer") {
      cron.close();
      print("timer has stopped");
    }
  });
}
```

**ui.dart**
```
 FloatingActionButton(
                  onPressed: () {
                    FlutterBackgroundService().sendData({"action": "startTimer"});
                   ...
```

I was asking this because, as the WorkManager weirdly works with Local Storages. (ex HiveDb)
Will, there be an issue with the `flutter_background_services` 
I can always devotedly hope, there will be no issues, as looking at the package, it is beautiful to gaze at. 😊❤️

**Comment by ekasetiawans** [comment]
@madd-project you have to manage your service's state too.
sometime os will kill our application and our service for some reason.
but, the service will be restarted immediately and execute your resetToodoleeMidNight() method.
At this time, your application is running without UI and your service will never receive any action for example "startTimer".

You can use shared_preferences plugin to save your service state, then you can reload the preference to resuming previous state.

**Comment by madd-project** [comment]
I am using the `move_to_background` package, is it doing the thing, which you are meaning?
BTW, If not, Can I be provided with the minimal code example.
