### ISSUE TITLE
navigator to method onStart

### ISSUE THREAD

**Issue by siamandkm** [ekasetiawans/flutter_background_service#43]
hi,I want to access the context via the onStart method. To navigate. What do you suggest?
 FlutterBackgroundService.initialize(onStart);

**Comment by ekasetiawans** [comment]
hi @siamandkm you can't access any UI from the service, but you can communicate between them. Note that, it is not guaranteed that your data sent will be received by each other.

**Comment by siamandkm** [comment]
i want to reastart app in the background but i can't,I used many packages, but got no answer
