### ISSUE TITLE
Background service on IOS

### ISSUE THREAD

**Issue by Server48** [ekasetiawans/flutter_background_service#44]
Hello. I was successfully able to integrate my services on android on your plugin. Now there is a task to repeat this on iOS. It was possible to start the background mode of your plugin while the application is running in the foreground, but when I turn it off, the service turns off. Tell me, have you found some optimal solution for this?
IOS still doesn't allow doing anything in the background and need to use APNS?
Could you suggest some solution for my application, I need to check the status of the site in the background, but at least once a minute?

I see you have dealt with this issue a lot, I think you have also come across this - I will be very grateful if you give the broadest possible answer.

**Comment by giorgi19** [comment]
I have same problem. background service is not working if foreground is false.
