### ISSUE TITLE
 background service is not working after reboot.

### ISSUE THREAD

**Issue by SandaruwanFdo** [ekasetiawans/flutter_background_service#45]
Is there any way to configure background service run on android phone startup

**Comment by ekasetiawans** [comment]
This plugin will automatically run the service at startup. But, some custom android OS e.g MIUI (Xiaomi) need to allow auto run explicitly via their setting.

**Comment by SandaruwanFdo** [comment]
Nokia 1.4
Android 10 Go (API Version 29)

foreground service perfectly run at startup.  only issue with background service.

**Comment by agsant** [comment]
Hello guys, is there a function to catch after boot completed?

**Comment by SandaruwanFdo** [comment]
Yes, but seems to be it does not work
