### ISSUE TITLE
Incompatible getter 'foregroundServiceTypes' in `flutter_background_service_android`

### ISSUE THREAD

**Issue by abdelrahman-atef1** [ekasetiawans/flutter_background_service#475]
I am encountering an issue with the `flutter_background_service_android` package (version 6.2.5) due to an inconsistency with the `flutter_background_service_platform_interface` package. Specifically, the `AndroidConfiguration` class in the `flutter_background_service_platform_interface` package seems outdated and lacks the correct getter for `foregroundServiceTypes`.

**Error:**

```
/C:/Users/user/AppData/Local/Pub/Cache/hosted/pub.dev/flutter_background_service_android-6.2.5/lib/flutter_background_service_android.dart:99:28: Error: The getter 'foregroundServiceTypes' isn't defined for the class 'AndroidConfiguration'.
 - 'AndroidConfiguration' is from 'package:flutter_background_service_platform_interface/src/configs.dart' ('/C:/Users/user/AppData/Local/Pub/Cache/hosted/pub.dev/flutter_background_service_platform_interface-5.1.1/lib/src/configs.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'foregroundServiceTypes'.
      androidConfiguration.foregroundServiceTypes!
```

**Issue Explanation:**

The current `AndroidConfiguration` class in `flutter_background_service_platform_interface` (version 5.1.1) defines the following:

```dart
final AndroidForegroundType? foregroundServiceType;
```

However, the `flutter_background_service_android` package expects:

```dart
final List<AndroidForegroundType>? foregroundServiceTypes;
```

This mismatch causes the build to fail, as the `foregroundServiceTypes` getter is not defined in the `flutter_background_service_platform_interface` package.

**Steps to Reproduce:**

1. Add `flutter_background_service: ^5.0.8` to the `pubspec.yaml` file.
2. Attempt to run or build the Flutter project.
3. Observe the error in the console.

**Flutter doctor:**
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.24.1, on Microsoft Windows [Version 10.0.22631.4037], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Build Tools 2019 16.11.35)
[√] Android Studio (version 2024.1)
[√] VS Code (version 1.92.2)
[√] Connected device (4 available)
[√] Network resources
```

**Comment by NeerBhar** [comment]
same here just installed both on my APP and started giving the same error,even Sample code on the flutter_background_service_platform_interface package use the field as List and hence does not work

**Comment by selvam920** [comment]
+1

**Comment by J3S** [comment]
Confirm, I'm seeing that in the [commit](https://github.com/ekasetiawans/flutter_background_service/commit/fbc8f940851907944af27180df4bd8e59f94f28c) of the new release. The release of a new version for the flutter_background_service_platform_interface package that comes with this change was missing. @ekasetiawans

**Comment by NeerBhar** [comment]
thank you !when would that get available ?anyidea

**Comment by J3S** [comment]
As a temporary solution until the release of the new version of the package (flutter_background_service_platform_interface), and the update of the dependencies to this new version, is to directly modify the configs.dart file. Using the image as a reference, change the red lines(your current installed version) to green lines(new version).
![Screenshot from 2024-08-25 09-57-26](https://github.com/user-attachments/assets/be3e743e-5498-4681-a16f-df35fbb28e69)

**Comment by ekasetiawans** [comment]
i just landed the new version, appologize some contributor was forgot to use conventional commit.

**Comment by abdelrahman-atef1** [comment]
Works now using flutter_background_service: 5.0.9
Thx.
