### ISSUE TITLE
Failed to send SMS: MissingPluginException(No implementation found for method sendSms on channel com.sms)

### ISSUE THREAD

**Issue by yashjasoli** [ekasetiawans/flutter_background_service#478]
class SmsService {
  static MethodChannel platform = MethodChannel('com.sms');

  Future<void> sendSms(String phoneNumber, String message) async {
    try {
      await platform.invokeMethod('sendSms', {'phoneNumber': phoneNumber, 'message': message});
      print("SMS sent successfully");
    } catch (e) {
      print('Failed to send SMS: $e');
    }
  }
}

**Comment by Gonn01** [comment]
hi, how do you solved it?
