### ISSUE TITLE
PlatformException on initialize

### ISSUE THREAD

**Issue by wfuener** [ekasetiawans/flutter_background_service#49]
FlutterBackgroundService.initialize is failing with an error message of:   Unhandled Exception: PlatformException(100, Failed read arguments, null, null) at line 62. I'm running version 0.1.5 on android. 

I'm working on finding any information to guide me to an answer to what's going on. Right now I'm guessing it has something to do with my android configurations. Any help is appreciated!

**Comment by ekasetiawans** [comment]
Try to call `WidgetsFlutterBinding.ensureInitialized();` first. If you still facing the issue, try to disable every plugin with package name prior to flutter_background_service ordered by name alphabetically
