### ISSUE TITLE
Callback error: type 'HeadlessTask' is not a subtype of type 'String' of 'taskId'

### ISSUE THREAD

**Issue by yakupbaser** [ekasetiawans/flutter_background_service#50]
Hi, 
With the background service I do the things I want in the background periodically once a minute. The application runs successfully for hours on android device. But sometimes it gives this error . The application does not crash completely, but I am still worried, what could be the reason?

`I/flutter (22601): [BackgroundFetch _headlessCallbackDispather] ‼️ Callback error: type 'HeadlessTask' is not a subtype of type 'String' of 'taskId'
I/flutter (22601): #0      _TypeError._throwNew (dart:core-patch/errors_patch.dart:98:34)
I/flutter (22601): #1      _headlessCallbackDispatcher.<anonymous closure> (package:background_fetch/background_fetch.dart:652:15)
I/flutter (22601): #2      _headlessCallbackDispatcher.<anonymous closure> (package:background_fetch/background_fetch.dart:638:41)
I/flutter (22601): #3      MethodChannel._handleAsMethodCall
package:flutter/…/services/platform_channel.dart:435
I/flutter (22601): #4      MethodChannel.setMethodCallHandler.<anonymous closure>
package:flutter/…/services/platform_channel.dart:382
I/flutter (22601): #5      _DefaultBinaryMessenger.handlePlatformMessage
package:flutter/…/services/binding.dart:284
I/flutter (22601): #6      _invoke3.<anonymous closure> (dart:ui/hooks.dart:223:15)
I/flutter (22601): #7      _rootRun (dart:async/zone.dart:1354:13)
I/flutter (22601): #8      _CustomZone.run (dart:async/zone.dart:1258:19)
I/flutter (22601): #9      _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
I/flutter (22601): #10     _invoke3 (dart:ui/hooks.dart:222:10)
I/flutter (22601): #11     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:520:7)
I/flutter (22601): #12     _dispatchPlatformMessag
`

**Comment by ekasetiawans** [comment]
Seems like you use background_fetch plugin  instead of flutter_background_service.

**Comment by ybaser** [comment]
no i iuse flutter_background_service. I am the last man to deceive you :)
iI still haven't found the solution to the problem.

**Comment by ekasetiawans** [comment]
Your logs tell us everything.  Closing this because it is not part of the plugin.
