### ISSUE TITLE
SharedPreference

### ISSUE THREAD

**Issue by Denish-Borad** [ekasetiawans/flutter_background_service#51]
Can't use Shared Preferences inside it. can anyone please help how can i use sharedpref inside it

**Comment by huseyinemreuslu** [comment]
You can use but, dart codes are isolated. So it means that you will working on memory, not disk. Check that: https://hackernoon.com/an-introduction-to-dart-code-and-isolate-em3j34u1

**Comment by EmanueleVinci** [comment]
You can, just do

`pref.reload();`

 before reading or writing.

**Comment by bhautikcoretus** [comment]
pref.reload(); solution is perfect solution.
Thank you @EmanueleVinci
