### ISSUE TITLE
background service is not working

### ISSUE THREAD

**Issue by arun28082007** [ekasetiawans/flutter_background_service#52]
background service is not working , but foreground service is work perfectly , and service not auto started after boot completed and Nought (7.0)

**Comment by Abdullayev3635** [comment]
I have the same issue

**Comment by Abdullayev3635** [comment]
give you me example code

пн, 30 авг. 2021 г., 15:17 Abdullayev Olloyor ***@***.***>:

**Comment by rrafush** [comment]
same issue, works perfectly in foreground, but its not working in background mode...

**Comment by SandaruwanFdo** [comment]
did anyone try older versions?

**Comment by rrafush** [comment]
> did anyone try older versions?
> 
> In my case both services seem to be starting. but onStart method not fired.

which version are you using?

**Comment by SandaruwanFdo** [comment]
> which version are you using?

latest version 0.1.5

**Comment by rrafush** [comment]
> > which version are you using?
> 
> latest version 0.1.5

and your background task is working? I tried this version and the last one, without success.... mine only works in foreground, Im using flutter logs to see if its working

**Comment by SandaruwanFdo** [comment]
> and your background task is working? I tried this version and the last one, without success.... mine only works in foreground, Im using flutter logs to see if its working

Yes, both services have started. but initialize method not fired by the plugin

**Comment by brenohff** [comment]
Hey, have you tried to initialize this way?

`await FlutterBackgroundService.initialize(onStart, foreground: false, autoStart: true);`

I implemented this plugin last night and merged this plugin [notifications](https://pub.dev/packages/notifications/install) to listen notifications, looks working well

**Comment by SandaruwanFdo** [comment]
@brenohff is that working after boot? can you provide some example code please

**Comment by brenohff** [comment]
@SandaruwanFdo  
To be honest I didn't test after reboot. I'll test and post the result here

**Comment by brenohff** [comment]
@SandaruwanFdo 
I've tried rebootng the device and you're right, the plugin is not working automatically
