### ISSUE TITLE
flutter background service and geofences

### ISSUE THREAD

**Issue by rrafush** [ekasetiawans/flutter_background_service#54]
hey guys, did anyone manage to make this package work with any geofence monitoring package? I'm trying to build an application that sends the user a notification when they get near a specific location (even with the app closed), I tried to do something simple until now with geolocator, but without any success because as soon as the app is minimized it stops the location service, and for what I saw until now, it's not possible to use this with geolocator... I would be very happy if you could share with me some experience with this type of feature, I'm a beginner developer in a rollercoaster of a task lol!
thanks!!

**Comment by zeroasterisk** [comment]
@rrafush have you seen https://medium.com/flutter/executing-dart-in-the-background-with-flutter-plugins-and-geofencing-2b3e40a1a124 ?

I have tried to implement it, but have not completed it.  Considering alternatives brought me here. YMMV

**Comment by rrafush** [comment]
yes! I saw this exceptional article, but he uses a pack created by him and it did not work for me... not to mention that it took days for me to understand not even a third of it lol, I was often bothered by the idea that maybe it was not the packages I used, but my lack of technique and experience that was the real issue.... but at the end I did manage to implement the geolocator pack with flutter background services, but only in foreground mode :)

**Comment by zeroasterisk** [comment]
Ha, similar journey here

Can you share your implementation, for reference?

Can you clarify the "only in foreground mode" statement?

My needs are not about geo fencing, but they do require background service,
on boot, and without UI or app interaction.
