### ISSUE TITLE
Does not work on IOS

### ISSUE THREAD

**Issue by taylanyildiz** [ekasetiawans/flutter_background_service#55]
I want to listen received message from socket but if app closes socket is disconnect. Also it works on android but IOS side have a problem.

**Comment by ekasetiawans** [comment]
There is no background service like android on ios. iOS will terminate app soon after user minimize the app.

**Comment by manishrelani** [comment]
@ekasetiawans then how WhatsApp and other apps keep running even when it terminated in IOS.
Please can you tell me? it will be helpful.

**Comment by taylanyildiz** [comment]
It doesn't work on ios. try  [WorkManager](https://pub.dev/packages/workmanager) every 15 minutes trigger in background

**Comment by manishrelani** [comment]
@taylanyildiz I want to call API every 2 seconds even when the app is terminated. Does it work for that?

**Comment by taylanyildiz** [comment]
@manishrelani It triggers every 15 minutes not 2 seconds. If you read documentation WorkManager, you'll see.
