### ISSUE TITLE
Unhandled Exception: MissingPluginException

### ISSUE THREAD

**Issue by g0coders** [ekasetiawans/flutter_background_service#56]
initializenya bisa, tapi kalau setNotificationInfo dan stopBackgroundService error missingPluginException..

![DeepinScreenshot_xfdesktop_20210903215347](https://user-images.githubusercontent.com/54851209/132025566-5214e124-51b8-42d0-83f8-bf044e210be0.png)

**Comment by ekasetiawans** [comment]
setNotificationInfo dan stopBackgroundService hanya bisa dilakukan dari dalam method background servicenya

**Comment by g0coders** [comment]
Ini mas beberapa ss code saya, yang saya ikuti dari tutorialnya, belum aku ubah dikit.. menyesuaikan structure getx aja.. masis error mas, walaupun stopnya udah di dalam method background servicenya, kenapa ya?

![DeepinScreenshot_xfdesktop_20210904073619](https://user-images.githubusercontent.com/54851209/132076606-5329fa1f-6427-435b-b4b8-5f8135366c0c.png)
![DeepinScreenshot_xfdesktop_20210904073649](https://user-images.githubusercontent.com/54851209/132076618-c0d15d3f-9b52-4267-a7b0-3e8a4c50bdb5.png)
![DeepinScreenshot_xfdesktop_20210904073711](https://user-images.githubusercontent.com/54851209/132076632-c11d83cd-7c1a-40ed-8b7b-9e6c5f793568.png)

**Comment by ekasetiawans** [comment]
method yang digunakan untuk initialize background service harus top level method, tidak boleh berada di dalam class. Jika ingin di dalam class maka harus static method.

**Comment by g0coders** [comment]
sekarang missingPluginException yang method sendData mas, kenapa ya?

**Comment by g0coders** [comment]
udah bisa mas berjalan di background service, tapi setiap initialize muncul log seperti di ss, pas sendData, listennya nggak bekerja, 

![DeepinScreenshot_xfdesktop_20210904165901](https://user-images.githubusercontent.com/54851209/132090540-1def7900-fea5-4341-a663-cbae6747e2c6.png)

**Comment by g0coders** [comment]
solved bisa sendData dan stop service, aku push dan aku pull di folder lain, dan aku run ternyata bisa..jadi sekarang pakai hasil pull dari github, yang folder lama tak hapus..
