### ISSUE TITLE
anyone success foreground service after boot?

### ISSUE THREAD

**Issue by SandaruwanFdo** [ekasetiawans/flutter_background_service#59]
I'm stuck in this notification. any suggestions?

**Background Service
Preparing**

**Comment by brenohff** [comment]
I think you cannot turn the foreground notification off.

if you're using as background, you can initialize with 'foreground' param false

**Comment by SandaruwanFdo** [comment]
Yes, notification is essential for foreground service. although I set the auto start mode true, it's not auto-running after boot

**Comment by josh4500** [comment]
> Yes, notification is essential for foreground service. although I set the auto start mode true, it's not auto-running after boot

Has the issue been solved?

**Comment by SandaruwanFdo** [comment]
@josh4500 Not yet

**Comment by lasd14** [comment]
Someone found a solution? I have the same problem, reboot -> Background Service Preparing

**Comment by lasd14** [comment]
> 

Someone found a solution? I have the same problem, reboot -> Background Service Preparing

**Comment by lasd14** [comment]
#80 Here the solution

**Comment by SandaruwanFdo** [comment]
solved

**Comment by mahdinazmi** [comment]
@SandaruwanFdo 
how did you solve it ?
