### ISSUE TITLE
I can't stop Service in Background

### ISSUE THREAD

**Issue by ferguquang** [ekasetiawans/flutter_background_service#62]
When background service is running, I shutdown background service in function Future.delayed, but event in service.onDataReceived don't receive.
(Device: Samsung Galaxy Note 5, Android 7.0)

**Comment by huseyinemreuslu** [comment]
Any classes you want, you can send message with FlutterBackgroundService().sendData() function, and you can receive with FlutterBackgroundService().receiveFromData.listen(event). If you stop background before receive, it will throw error about " could not send message". There are many way to communicate dart files. You should review this: https://medium.com/47billion/creating-a-bridge-in-flutter-between-dart-and-native-code-in-java-or-objectivec-5f80fd0cd713
After that try to do that, 
Thank you!
