### ISSUE TITLE
compile error in ios

### ISSUE THREAD

**Issue by GerJeffrey** [ekasetiawans/flutter_background_service#64]
Flutter run install app to test iphone device successfully, but compile error in Xcode editor. Xcode seems to not recognize imports flutter_background_service and report No such module 'flutter_background_service' error. Maybe I miss something in iOS configurations? Tks very much!
<img width="1123" alt="截屏2021-10-11 下午4 47 12" src="https://user-images.githubusercontent.com/2101877/136761119-0ff2a2a3-a83a-495d-b1dc-4bae795973a0.png">

**Comment by sonth-bhsoft** [comment]
Hi @GerJeffrey ,
I got the same problem. Can you please tell me how can you solve this?
Thanks!

**Comment by ekasetiawans** [comment]
hi @GerJeffrey have you add flutter_background_service into your pubspec.yaml?
Note that, registering plugin in native side on iOS is currently not necessary since this already executed by the plugin.

**Comment by sonth-bhsoft** [comment]
Hi @ekasetiawans ,
I only add flutter_background_service intomy pubspec.yaml.
It works okay on Android. But I got a Swift Compiler Error "No such module 'flutter_background_service'".
Do you know how to solve this?
Thanks!

**Comment by sonth-bhsoft** [comment]
For anyone who got this issue. You just need to delete the code related to flutter_background_service inside the AppDelegate.swift, and it would work.
