### ISSUE TITLE
Service not Work when app killed

### ISSUE THREAD

**Issue by itsdani121** [ekasetiawans/flutter_background_service#66]
this package works only foreground or background but when app is killed or destroy it did not work, i set notification with timer that show after 5 minute and it works fine with foreground or background but when i killed app it did not work. anybody idea about this. here is code 

             void onStart() async {
      WidgetsFlutterBinding.ensureInitialized();
     final service = FlutterBackgroundService();

     service.setForegroundMode(false);
     Timer.periodic(Duration(seconds: 1), (timer) async {
      if (!(await service.isServiceRunning())) timer.cancel();

        service.sendData(
        {
        "current_date": DateTime.now().toIso8601String(),
        },
      );
     });
    Timer.periodic(Duration(minutes: 5), (timer) async {
      getClassTime();     // for notification function 
     });

  

    service.setNotificationInfo(
      title: "Employee",
     content: "Be Prepare Class Time start very soon... ",
    );
    }

**Comment by CodeLabsInc** [comment]
I dont think it works when app is killed
please correct me if i am wrong.

**Comment by huseyinemreuslu** [comment]
It is actually working on Android background correctly but actually i cannot use on ios. You should review this topics for understanding how dart communicate with android and ios: https://medium.com/@igaurab/event-channels-in-flutter-2b4d0db0ee4f

**Comment by Saikiran24** [comment]
Is the service will work in background when the app is killed with this plugin flutter_background_service, but which function you used since i tried with simple print statement it is not showing in terminated or killed state only showing is runService, if you found the solution please help me on this.
