### ISSUE TITLE
Background Service - Preparing

### ISSUE THREAD

**Issue by imeDevelopers** [ekasetiawans/flutter_background_service#67]
Hello, The service works if we lunched the app for first time also if we removed the app from recent activities it still works, but once the app killed by the system for some reason, the service starts after 30 seconds and don't work, the notification title is (Background Service) and the content is (Preparing) and nothing change, and the system tells you that the service just started "Now" beside the notification even if several minutes are gone, it sounds like the service making auto restart multiple times .. and our code not works at all, so the plugin are useless now .., please check it, thank you.

**Comment by lasd14** [comment]
#80 Here the solution

**Comment by sovoereign** [comment]
The same issue is still persist.

**Comment by huseyinemreuslu** [comment]
The service is running again correctly but you should know it, when service start again only onStart method will work so you should check something there. If you send your sample code i can try to help you.
