### ISSUE TITLE
App Got Killed While Debugging

### ISSUE THREAD

**Issue by proismailshah** [ekasetiawans/flutter_background_service#69]
This is the error,
While working on the App when I hot reload sometimes
E/AndroidRuntime(20156): android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{84fcb07 u0 com.example.makor_habracha/id.flutter.flutter_background_service.BackgroundService}

**Comment by huseyinemreuslu** [comment]
Hot restart cause stop background service but if set_auto_boot control is true, background service start automatically.
