### ISSUE TITLE
Missing plugin exception

### ISSUE THREAD

**Issue by theanhoo** [ekasetiawans/flutter_background_service#71]
Running on Pixel 3a XL, Android 12.
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-x64, locale en-MY)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] IntelliJ IDEA Community Edition (version 2020.3.4)
[✓] VS Code (version 1.62.2)
[✓] Connected device (2 available)

MissingPluginException(No implementation found for method sendData on channel id.flutter/background_service_bg)

I don't seem to have any issue with other plugins. I've tried cleaning it, clearing cache, rebuilding it. Nothing seems to fix this.

Any advice?

Many thanks in advance.

**Comment by huseyinemreuslu** [comment]
Did you set options correctly on AndroidManifest.xml? This should be the problem with method channel.

**Comment by milanobrenovic** [comment]
> 

i have the same problem. what exactly am i supposed to set in the android manifest? this documentation is total crap, it said nothing about that. also im trying to run it on ios emulator so how does android manifest have anything to do with this error?

**Comment by huseyinemreuslu** [comment]
You should initiliaze in main method like that: FlutterBackgroundService.initialize(onStart);

**Comment by PeperMarkreel** [comment]
I got the same error when calling FlutterBackgroundService.initialize(onStart); in the initState of my Stateful Widget. 

When I moved that method call to the main method, before runApp(myApp()); is executed, it works.
