### ISSUE TITLE
How can I customize the notification message?

### ISSUE THREAD

**Issue by EmanueleVinci** [ekasetiawans/flutter_background_service#72]
I have to customize the notification message. How can I do it?

**Comment by huseyinemreuslu** [comment]
You can change notification info with FlutterBackgroundServic.setNotificaitonInfo()

**Comment by Nazarii77** [comment]
how to hide notification on notification click?

**Comment by EmanueleVinci** [comment]
> You can change notification info with FlutterBackgroundServic.setNotificaitonInfo()

Thank you!

**Comment by EmanueleVinci** [comment]
> how to hide notification on notification click?

I don't think you can do it... The only way I know is manually, changing the settings.
