### ISSUE TITLE
how to hide notification on notification click?

### ISSUE THREAD

**Issue by Nazarii77** [ekasetiawans/flutter_background_service#73]
how to hide notification on notification click?

**Comment by huseyinemreuslu** [comment]
You can change for android from library which path is /ekasetiawans/flutter_background_service/blob/master/android/src/main/java/id/flutter/flutter_background_service/BackgroundService.java

**Comment by huseyinemreuslu** [comment]
I am not sure for that but actually ios path can be /ekasetiawans/flutter_background_service/blob/master/ios/Classes/SwiftFlutterBackgroundServicePlugin.swift
Anyway you can change notification setting from hard code. Hope will be helpfull
