### ISSUE TITLE
Background service starts after boot

### ISSUE THREAD

**Issue by bobosette** [ekasetiawans/flutter_background_service#76]
Hi everybody. I don't know if someone have already had this problem, but I noticed that after boot the background service of my app starts but I don't want it. Is there a way to change this behaviour?
Thank you

**Comment by huseyinemreuslu** [comment]
There should be a function like FlutterBackgroundService.setAutoBootMode(). Default value is true, change it to false.

**Comment by bobosette** [comment]
Thank you man

Il Mer 22 Dic 2021, 15:56 Hüseyin Emre ***@***.***> ha
scritto:

**Comment by bobosette** [comment]
Hi tried but it throws an exceptio: missing implementation of method "setautobootmode". How can I fix it?
