### ISSUE TITLE
Is obligatory to use the   FlutterBackgroundService.initialize(onStart); on main.dart?

### ISSUE THREAD

**Issue by lasd14** [ekasetiawans/flutter_background_service#77]
I am working on a GPS App and I am using GEOLOCATOR but I cant achieve to start de notification when the app is up, only if I call the method on main.

Can someone provide me a example implementing the package outside the main?

Thanks! Happy Holidays

**Comment by EmanueleVinci** [comment]
You can start wherever you want, just write a method to call where you need it, like this:

`await YourService.start();`

And inside **your_service.dart**:

```
class YourService{
    Future<void> start() async {
      await FlutterBackgroundService.initialize(onStart,
          autoStart: true, foreground: true);
    }
}

onStart() {
  // Declare this outside the class (global method), or it doesn't work (don't know why)
}
```

**Comment by lasd14** [comment]
@EmanueleVinci Thanks bro!
