### ISSUE TITLE
How to set title and description for notification

### ISSUE THREAD

**Issue by ljsharp** [ekasetiawans/flutter_background_service#78]
I set the title and description - 

```
     service.setNotificationInfo(
        title: "Happy Message",
        content: "Tap to return to the app.",
      );
```
it displays **Background Service and preparing** respectively.
I want to set the title and description for notification so how can I do that, please?

**Comment by huseyinemreuslu** [comment]
You should call from onStart method to set notification info. When app starts, it called onStart method first. Check example. Good luck
