### ISSUE TITLE
PlatformException on initialize on Android 12

### ISSUE THREAD

**Issue by StorozhevS** [ekasetiawans/flutter_background_service#79]
I'm trying run exemple on device with Android 12. 
Using 0.1.6 version of flutter_background_service.

When called FlutterBackgroundService.initialize an error occurs:
`Unhandled Exception: PlatformException(100, Failed read arguments, null)`

On device whith Android 10 works perfect.

**Comment by huseyinemreuslu** [comment]
I am not sure about but it looks like permission problem: Did you add these permissions in your AndroidManifest;  
 ​    <​uses-permission​ ​android​:​name​=​"​android.permission.FOREGROUND_SERVICE​"​/> 
 ​    <​uses-permission​ ​android​:​name​=​"​android.permission.RECEIVE_BOOT_COMPLETED​"​/> 
 ​    <​uses-permission​ ​android​:​name​=​"​android.permission.WAKE_LOCK​"​/>

**Comment by StorozhevS** [comment]
These permissions are present in the manifest.
The error only occurs on a device/emulator with Android 12.
On Android 10, 11 works fine.

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(100, Failed read arguments, null, null)
JSONMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:155:7)
MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
 <asynchronous suspension>
FlutterBackgroundService.initialize (package:flutter_background_service/flutter_background_service.dart:62:15)
```

**Comment by ekasetiawans** [comment]
I have made a fix in version 0.1.7, please try and close this issue if it is solved. thanks.

**Comment by StorozhevS** [comment]
Yes, 0.1.7 works on Android 12. Thanks.

**Comment by micodev** [comment]
#226

**Comment by mraslamiii** [comment]
> Yes, 0.1.7 works on Android 12. Thanks.

how did you solve it?

**Comment by cmedamine** [comment]
@ekasetiawans the issue is happening again in version `flutter_background_service: ^5.0.6`, the plugin does not work in android 12
