### ISSUE TITLE
Background Service Preparing Android 10+

### ISSUE THREAD

**Issue by lasd14** [ekasetiawans/flutter_background_service#80]
Hi everyone, I am making test of the package, all is fine but I found something that doesn work like it supposed to be, when I reboot my phone I get the notification but this notification only says Background Service Preparing, I do not know why this is happening and see that other people are having the same error. Any solution?

Thanks

**Comment by ekasetiawans** [comment]
I have made a fix in version 0.1.7, please try and close this issue if it is solved. thanks.

**Comment by iamsaikat** [comment]
Still getting same issue. It's working first time only, after that getting notification only says Background Service Preparing.

**Comment by ekasetiawans** [comment]
@iamsaikat if you run in debug mode from vscode or android studio, then you have to stop the app first then run the app manually from the device home screen. Because the callback handle that required by isolate is different. Please try it with android emulator with stock android OS from google or android sdk.

**Comment by iamsaikat** [comment]
@ekasetiawans I run the app manually from the device as you mentioned, but still getting same notification. I am using emulator with stock android 11 OS.

**Comment by ekasetiawans** [comment]
@iamsaikat is example project has same issue?

**Comment by lasd14** [comment]
@ekasetiawans @iamsaikat I ran the application on physical devices and the functionality to restart the phone and start the service automatically is working correctly, I do this test with the demo application and my own application and in both the "Preparing" error was solved.

Physical device: Samsung A03

**Comment by theappideasankit** [comment]
i found same issue in letest version

**Comment by myanimeh** [comment]
@theappideasankit
 Same problem here ! Did you figure out ? I don't know how to fix this
It keeps printing
 ```D/BackgroundService(15312): runService
E/BackgroundService(15312): callback handle not found
D/BackgroundService(15312): runService
E/BackgroundService(15312): callback handle not found```

**Comment by ekasetiawans** [comment]
When callback handle not found, the only reason is there is a difference between current flutter binary with saved configuration on first app launch. It should be solved when we launch the app to call FlutterBackgroundService.configure at leat once after updated the app.

**Comment by amazement1** [comment]
@ekasetiawans  I don't quite get it. But I had tried swiping away the app and re-launch it. the notification shows same thing 
"Background service Preparing".  
BTW I call the startService on a detail page not home page

**Comment by ekasetiawans** [comment]
@amazement1 did you call FlutterBackgroundService.configure on main() method?

**Comment by bahman2000** [comment]
@ekasetiawans I'm using `flutter_background_service: ^5.0.4` and I have the same issue. When I run in debug mode from android studio, I getting notification only says Background Service Preparing.

``` 
Future<void> configureAndStartService() async {
    final service = FlutterBackgroundService();
    await service.configure(
      androidConfiguration: AndroidConfiguration(
        onStart: onStart,
        autoStart: true,
        isForegroundMode: true,
      ),
      iosConfiguration: IosConfiguration(
        autoStart: true,
        onForeground: onStart,
        onBackground: onIosBackground,
      ),
    );
    service.startService();
  }
