### ISSUE TITLE
try to run example

### ISSUE THREAD

**Issue by nadeemZe** [ekasetiawans/flutter_background_service#82]
Build failed with this error:
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_background_service-0.2.2\android\src\main\java\id\flutter\flutter_background_service\BackgroundService.java:58: error: cannot find symbol
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S){
                                                        ^
  symbol:   variable S
  location: class VERSION_CODES
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_background_service-0.2.2\android\src\main\java\id\flutter\flutter_background_service\BackgroundService.java:59: error: cannot find symbol
            PendingIntent pIntent = PendingIntent.getBroadcast(context, 111, intent, PendingIntent.FLAG_UPDATE_CURRENT | PendingIntent.FLAG_MUTABLE);
                                                                                          ^
  symbol:   variable FLAG_MUTABLE
  location: class PendingIntent

**Comment by ekasetiawans** [comment]
@nadeemZe update your android sdk to the latest version

**Comment by nadeemZe** [comment]
@ekasetiawans it works thnx
