### ISSUE TITLE
MissingPluginException(No implementation found for method isAvailable on channel plugins.pauldemarco.com/flutter_blue/methods)

### ISSUE THREAD

**Issue by myogesh7** [ekasetiawans/flutter_background_service#83]
I want to connect to bleDevice from the service thread, but every time I try do so I get **MissingPluginException(No implementation found for method isAvailable on channel plugins.pauldemarco.com/flutter_blue/methods)**

**Comment by ekasetiawans** [comment]
did you call `WidgetsFlutterBinding.ensureInitialized();`?

**Comment by myogesh7** [comment]
yes, inside of onStart() method

**Comment by ekasetiawans** [comment]
@myogesh7 have a look at https://github.com/pauldemarco/flutter_blue/blob/master/android/src/main/java/com/pauldemarco/flutter_blue/FlutterBluePlugin.java
the plugin you're using requires an Activity, and you can't use it in background services because background services don't have it.

**Comment by myogesh7** [comment]
so can you suggest how can I ble device as a service.

**Comment by ekasetiawans** [comment]
@myogesh7 unfortunately I don't have any suggestions about the ble plugin working in background services. Maybe you can start writing your own platform code.

**Comment by myogesh7** [comment]
thanks you..
