### ISSUE TITLE
Why does the app keep working in the background even in foreground mode? and a few other questions

### ISSUE THREAD

**Issue by manaswii** [ekasetiawans/flutter_background_service#84]
I have a few questions regarding the Library:

1. Does the app auto switch between foreground or background mode or do I have to do it manually?
2. Is there a function to check what mode the service is running on?
3. I made my service run in foreground using a button then i closed the app from the recent applications but my service was still running the operations. I was expecting the service to stop running after i put the app in foreground mode and closed the app and if it doesn't work that way then what is the difference between the two modes
4. When running in background mode my app crashed when i closed the app, can it be because i'm accessing global variables in my dart code. although it doesn't crash when using the global variables in foreground mode even after closing the app.
I did read up on isolates but then why doesn't the app crash in foreground mode is my doubt

Here's my repo- https://github.com/manaswii/flutter-background-service

I'm new to flutter so i apologize for any stupid questions in advance

**Comment by ekasetiawans** [comment]
hi @manaswii, You have to understand what a service is and how it works.

this is a good article that might make you understand more about it
https://developer.android.com/guide/components/services

**Comment by manaswii** [comment]
thank you, it was of great help.
