### ISSUE TITLE
Ios background servive ( Not Issue )

### ISSUE THREAD

**Issue by huseyinemreuslu** [ekasetiawans/flutter_background_service#88]
I have use that plugin for a long time. Is there any solution for Ios Background Service Processing ? I do not mean that background fetch.

**Comment by ekasetiawans** [comment]
@huseyinemreuslu unfortunately there is no background service (like Android) on iOS. We can't do anything, because the operating system doesn't allow us to run any task in the background for a long time.

**Comment by huseyinemreuslu** [comment]
I think that like that but i was not sure thanks.

**Comment by hitarthparmar0412** [comment]
Can we do this using method channeling, get Latitude and longitude from AppDelegate in dart code and send to the socket?
