### ISSUE TITLE
error app in after boot <app keep stoping>

### ISSUE THREAD

**Issue by rezadevelopers2** [ekasetiawans/flutter_background_service#91]

**Comment by claudneysessa** [comment]
I have the same problem, when I restart the device it gives the error, if I open the application it works normally again

**Comment by claudneysessa** [comment]
> I have the same problem, when I restart the device it gives the error, if I open the application it works normally again ![Screenshot_1644552106](https://user-images.githubusercontent.com/12506432/153535762-c4f3f83e-8d5c-43d6-99ff-6855a67a2571.png)

import 'dart:async';

import 'package:flutter/material.dart';
import 'package:flutter_background_service/flutter_background_service.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';

void startNotificationInBackground(String valor) {
  FlutterLocalNotificationsPlugin flutterNotificationPlugin = FlutterLocalNotificationsPlugin();

  var androidPlatformChannelSpecifics = const AndroidNotificationDetails(
    'Notification Channel ID',
    'Channel Name',
    playSound: false,
    importance: Importance.low,
    priority: Priority.low,
  );

  var iOSPlatformChannelSpecifics = const IOSNotificationDetails(presentSound: false);

  var platformChannelSpecifics =
      NotificationDetails(android: androidPlatformChannelSpecifics, iOS: iOSPlatformChannelSpecifics);

  flutterNotificationPlugin.show(
    0,
    'New Alert',
    valor,
    platformChannelSpecifics,
    payload: 'No Sound',
  );
}

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  initializeService();
  runApp(MyApp());
}

Future<void> initializeService() async {
  final service = FlutterBackgroundService();
  await service.configure(
    androidConfiguration: AndroidConfiguration(
      // this will executed when app is in foreground or background in separated isolate
      onStart: onStart,

      // auto start service
      autoStart: true,
      isForegroundMode: true,
    ),
    iosConfiguration: IosConfiguration(
      // auto start service
      autoStart: true,

      // this will executed when app is in foreground in separated isolate
      onForeground: onStart,

      // you have to enable background fetch capability on xcode project
      onBackground: onIosBackground,
    ),
  );
}

// to ensure this executed
// run app from xcode, then from xcode menu, select Simulate Background Fetch
void onIosBackground() {
  WidgetsFlutterBinding.ensureInitialized();
  print('FLUTTER BACKGROUND FETCH');
}

void onStart() {
  try {
    WidgetsFlutterBinding.ensureInitialized();
    final service = FlutterBackgroundService();

    service.onDataReceived.listen((event) {
      if (event!["action"] == "setAsForeground") {
        service.setForegroundMode(true);
        return;
      }

      if (event["action"] == "setAsBackground") {
        service.setForegroundMode(false);
      }

      if (event["action"] == "stopService") {
        service.stopBackgroundService();
      }
    });

    // bring to foreground
    service.setForegroundMode(true);

    Timer.periodic(
      Duration(seconds: 20),
      (timer) async {
        if (!(await service.isServiceRunning())) timer.cancel();

        service.setNotificationInfo(
          title: "My App Service",
          content: "Updated at ${DateTime.now()}",
        );

        service.sendData(
          {"current_date": DateTime.now().toIso8601String()},
        );

        //startNotificationInBackground(DateTime.now().toIso8601String());
      },
    );
  } catch (e) {
    print('object');
  }
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  String text = "Stop Service";
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Service App'),
        ),
        body: Column(
          children: [
            StreamBuilder<Map<String, dynamic>?>(
              stream: FlutterBackgroundService().onDataReceived,
              builder: (context, snapshot) {
                if (!snapshot.hasData) {
                  return Center(
                    child: CircularProgressIndicator(),
                  );
                }

                final data = snapshot.data!;
                DateTime? date = DateTime.tryParse(data["current_date"]);
                return Text(date.toString());
              },
            ),
            ElevatedButton(
              child: Text("Foreground Mode"),
              onPressed: () {
                FlutterBackgroundService().sendData({"action": "setAsForeground"});
              },
            ),
            ElevatedButton(
              child: Text("Background Mode"),
              onPressed: () {
                FlutterBackgroundService().sendData({"action": "setAsBackground"});
              },
            ),
            ElevatedButton(
              child: Text(text),
              onPressed: () async {
                final service = FlutterBackgroundService();
                var isRunning = await service.isServiceRunning();
                if (isRunning) {
                  service.sendData(
                    {"action": "stopService"},
                  );
                } else {
                  service.start();
                }

                if (!isRunning) {
                  text = 'Stop Service';
                } else {
                  text = 'Start Service';
                }
                setState(() {});
              },
            ),
          ],
        ),
        floatingActionButton: FloatingActionButton(
          onPressed: () {
            FlutterBackgroundService().sendData({
              "hello": "world",
            });
          },
          child: Icon(Icons.play_arrow),
        ),
      ),
    );
  }
}

**Comment by Henk-Keijzer** [comment]
I have the same problem. Both on the app I am developing as well as on the example app from pub.dev. Device is running Android 12.

**Comment by rhbrunetto** [comment]
Same problem here. Any updates on this?

**Comment by abbiyuarsyah** [comment]
> Edit: I was able to fix it by editing `BackgroundService.java` line 203, adding:
> 
> ```java
> FlutterInjector.instance().flutterLoader().startInitialization(getApplicationContext());
> ```
> 
> right before the `ensureInitializationComplete` method calling.
> 
> I added this once this exception was being thrown on startup: `java.lang.IllegalStateException: ensureInitializationComplete must be called after startInitialization`

I have this problem too and follow this way, and the error is gone

**Comment by ekasetiawans** [comment]
its may caused by Flutter framework doesn't initialized yet, try to update AndroidManifest looks like :

```
<application
name: "io.flutter.app.FlutterApplication"
```

**Comment by ekasetiawans** [comment]
hi everyone, I have published version 0.2.6 to fix this issue

**Comment by Henk-Keijzer** [comment]
Thank you!!!
