### ISSUE TITLE
Global Variable are not updating inside the onStart() function

### ISSUE THREAD

**Issue by nasu1128** [ekasetiawans/flutter_background_service#93]
Hi, I was trying to implement a background service for Bluetooth device value monitoring. But after I work on some link-up progress for the global variables, it is not working on the background service.

![image](https://user-images.githubusercontent.com/68841201/151754682-c97ac74f-00c2-44a1-ad04-84dea280e4c2.png)
The above image is printing the value of StreamBuilder and global variable value, the code are here:
```
StreamBuilder<Map<String, dynamic>>(
     stream: FlutterBackgroundService().onDataReceived,
     builder: (context, snapshot) {
       if (!snapshot.hasData) {
         return Center(
           child: CircularProgressIndicator(),
         );
       }

       print(snapshot.data);
       final data = snapshot.data;
       BluetoothDevice test = data["btd"];
       if(test != null){
         return Text(test.name);
       }
       else{
         return Text("No device found");
       }

     },
   ),
Text(
     globals.listeningDevice.id.toString(),
),
```

And the onStart function are as follows:
```
void onStart() {
  WidgetsFlutterBinding.ensureInitialized();
  final service = FlutterBackgroundService();
  BluetoothDevice listeningDevice;
  service.onDataReceived.listen((event) {
    if (event["action"] == "setAsForeground") {
      service.setForegroundMode(true);
      return;
    }

    if(event["device"] != null){
      service.stopBackgroundService();
      listeningDevice = event["device"];
      service.start();
    }

    if (event["action"] == "setAsBackground") {
      service.setForegroundMode(false);
    }

    if (event["action"] == "stopService") {
      service.stopBackgroundService();
    }

    print(event["current_date"]);
  });

  // bring to foreground
  service.setForegroundMode(true);
  Timer.periodic(Duration(seconds: 1), (timer) async {
    if (!(await service.isServiceRunning())) timer.cancel();
    service.setNotificationInfo(
      title: "My App Service",
      content: "Updated at ${DateTime.now()} + ${globals.listeningDevice}",
    );

    service.sendData(
      {"btd" : globals.listeningDevice},
    );
  });
}
```

I was also trying to use event["device"] to update a local variable in onStart, but it seems doesn't work too, is there any method for updating the variable value in onStart which have to be listened to? Thank you.

**Comment by ekasetiawans** [comment]
@nasu1128 Background service ran in isolated process, you can't share reference, only primitive type allowed such as String, int, double, bool.

**Comment by nasu1128** [comment]
> @nasu1128 Background service ran in isolated process, you can't share reference, only primitive type allowed such as String, int, double, bool.

I see, thank you. So in this case how am I supposed to keep on monitoring the value sent from the Bluetooth device? If I create a Timer on another page to keep pushing the value to the background service, would the timer stop when I make the application in the background?

**Comment by ekasetiawans** [comment]
you can serialize the data sent by bluetooth device to json string or Map<String, dynamic> (the dynamic also must be primitive type), then deserialize it on UI (main isolate).
