### ISSUE TITLE
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method printReceipt on channel bluetooth_print/methods)

### ISSUE THREAD

**Issue by gfsoluzioni** [ekasetiawans/flutter_background_service#94]
Hi, because when I try to run the bluetoothPrint plugin print command from onStart I get the following error: [ERROR: flutter / lib / ui / ui_dart_state.cc (209)] Unhandled Exception: MissingPluginException (No implementation found for method printReceipt on channel bluetooth_print / methods)

How can I solve this problem to launch, when the app is closed, a print command through this plugin? Thank you

**Comment by ekasetiawans** [comment]
looks like the bluetooth print plugin you're using needs a UI, for example for permission requests. Background services don't allow anything that requires a UI.

**Comment by mpcreza** [comment]
Hi, i get same error with ffmpeg_kit_flutter plugin and i don't think so this plugin required UI.

**Comment by mpcreza** [comment]
@ekasetiawans do you have any idea?

**Comment by ekasetiawans** [comment]
https://github.com/tanersener/ffmpeg-kit/blob/main/flutter/flutter/android/src/main/java/com/arthenica/ffmpegkit/flutter/FFmpegKitFlutterPlugin.java
