### ISSUE TITLE
 [ERROR: flutter / lib / ui / ui_dart_state.cc (209)] Unhandled Exception: MissingPluginException 

### ISSUE THREAD

**Issue by gfsoluzioni** [ekasetiawans/flutter_background_service#95]
Hi, because when I try to run the bluetoothPrint plugin print command from onStart I get the following error: [ERROR: flutter / lib / ui / ui_dart_state.cc (209)] Unhandled Exception: MissingPluginException (No implementation found for method printReceipt on channel bluetooth_print / methods)

How can I solve this problem to launch, when the app is closed, a print command through this plugin? Thank you

**Comment by ekasetiawans** [comment]
Duplicate #94
